// Generated by scripts/generate-ocpp.ts. Do not edit.

import authorizeRequestV16Schema from "../../../vendor/ocpp-schemas/v16/Authorize.json";
import authorizeResponseV16Schema from "../../../vendor/ocpp-schemas/v16/AuthorizeResponse.json";
import bootNotificationRequestV16Schema from "../../../vendor/ocpp-schemas/v16/BootNotification.json";
import bootNotificationResponseV16Schema from "../../../vendor/ocpp-schemas/v16/BootNotificationResponse.json";
import cancelReservationRequestV16Schema from "../../../vendor/ocpp-schemas/v16/CancelReservation.json";
import cancelReservationResponseV16Schema from "../../../vendor/ocpp-schemas/v16/CancelReservationResponse.json";
import certificateSignedRequestV16Schema from "../../../vendor/ocpp-schemas/v16/CertificateSigned.json";
import certificateSignedResponseV16Schema from "../../../vendor/ocpp-schemas/v16/CertificateSignedResponse.json";
import changeAvailabilityRequestV16Schema from "../../../vendor/ocpp-schemas/v16/ChangeAvailability.json";
import changeAvailabilityResponseV16Schema from "../../../vendor/ocpp-schemas/v16/ChangeAvailabilityResponse.json";
import changeConfigurationRequestV16Schema from "../../../vendor/ocpp-schemas/v16/ChangeConfiguration.json";
import changeConfigurationResponseV16Schema from "../../../vendor/ocpp-schemas/v16/ChangeConfigurationResponse.json";
import clearCacheRequestV16Schema from "../../../vendor/ocpp-schemas/v16/ClearCache.json";
import clearCacheResponseV16Schema from "../../../vendor/ocpp-schemas/v16/ClearCacheResponse.json";
import clearChargingProfileRequestV16Schema from "../../../vendor/ocpp-schemas/v16/ClearChargingProfile.json";
import clearChargingProfileResponseV16Schema from "../../../vendor/ocpp-schemas/v16/ClearChargingProfileResponse.json";
import dataTransferRequestV16Schema from "../../../vendor/ocpp-schemas/v16/DataTransfer.json";
import dataTransferResponseV16Schema from "../../../vendor/ocpp-schemas/v16/DataTransferResponse.json";
import deleteCertificateRequestV16Schema from "../../../vendor/ocpp-schemas/v16/DeleteCertificate.json";
import deleteCertificateResponseV16Schema from "../../../vendor/ocpp-schemas/v16/DeleteCertificateResponse.json";
import diagnosticsStatusNotificationRequestV16Schema from "../../../vendor/ocpp-schemas/v16/DiagnosticsStatusNotification.json";
import diagnosticsStatusNotificationResponseV16Schema from "../../../vendor/ocpp-schemas/v16/DiagnosticsStatusNotificationResponse.json";
import extendedTriggerMessageRequestV16Schema from "../../../vendor/ocpp-schemas/v16/ExtendedTriggerMessage.json";
import extendedTriggerMessageResponseV16Schema from "../../../vendor/ocpp-schemas/v16/ExtendedTriggerMessageResponse.json";
import firmwareStatusNotificationRequestV16Schema from "../../../vendor/ocpp-schemas/v16/FirmwareStatusNotification.json";
import firmwareStatusNotificationResponseV16Schema from "../../../vendor/ocpp-schemas/v16/FirmwareStatusNotificationResponse.json";
import getCompositeScheduleRequestV16Schema from "../../../vendor/ocpp-schemas/v16/GetCompositeSchedule.json";
import getCompositeScheduleResponseV16Schema from "../../../vendor/ocpp-schemas/v16/GetCompositeScheduleResponse.json";
import getConfigurationRequestV16Schema from "../../../vendor/ocpp-schemas/v16/GetConfiguration.json";
import getConfigurationResponseV16Schema from "../../../vendor/ocpp-schemas/v16/GetConfigurationResponse.json";
import getDiagnosticsRequestV16Schema from "../../../vendor/ocpp-schemas/v16/GetDiagnostics.json";
import getDiagnosticsResponseV16Schema from "../../../vendor/ocpp-schemas/v16/GetDiagnosticsResponse.json";
import getInstalledCertificateIdsRequestV16Schema from "../../../vendor/ocpp-schemas/v16/GetInstalledCertificateIds.json";
import getInstalledCertificateIdsResponseV16Schema from "../../../vendor/ocpp-schemas/v16/GetInstalledCertificateIdsResponse.json";
import getLocalListVersionRequestV16Schema from "../../../vendor/ocpp-schemas/v16/GetLocalListVersion.json";
import getLocalListVersionResponseV16Schema from "../../../vendor/ocpp-schemas/v16/GetLocalListVersionResponse.json";
import getLogRequestV16Schema from "../../../vendor/ocpp-schemas/v16/GetLog.json";
import getLogResponseV16Schema from "../../../vendor/ocpp-schemas/v16/GetLogResponse.json";
import heartbeatRequestV16Schema from "../../../vendor/ocpp-schemas/v16/Heartbeat.json";
import heartbeatResponseV16Schema from "../../../vendor/ocpp-schemas/v16/HeartbeatResponse.json";
import installCertificateRequestV16Schema from "../../../vendor/ocpp-schemas/v16/InstallCertificate.json";
import installCertificateResponseV16Schema from "../../../vendor/ocpp-schemas/v16/InstallCertificateResponse.json";
import logStatusNotificationRequestV16Schema from "../../../vendor/ocpp-schemas/v16/LogStatusNotification.json";
import logStatusNotificationResponseV16Schema from "../../../vendor/ocpp-schemas/v16/LogStatusNotificationResponse.json";
import meterValuesRequestV16Schema from "../../../vendor/ocpp-schemas/v16/MeterValues.json";
import meterValuesResponseV16Schema from "../../../vendor/ocpp-schemas/v16/MeterValuesResponse.json";
import remoteStartTransactionRequestV16Schema from "../../../vendor/ocpp-schemas/v16/RemoteStartTransaction.json";
import remoteStartTransactionResponseV16Schema from "../../../vendor/ocpp-schemas/v16/RemoteStartTransactionResponse.json";
import remoteStopTransactionRequestV16Schema from "../../../vendor/ocpp-schemas/v16/RemoteStopTransaction.json";
import remoteStopTransactionResponseV16Schema from "../../../vendor/ocpp-schemas/v16/RemoteStopTransactionResponse.json";
import reserveNowRequestV16Schema from "../../../vendor/ocpp-schemas/v16/ReserveNow.json";
import reserveNowResponseV16Schema from "../../../vendor/ocpp-schemas/v16/ReserveNowResponse.json";
import resetRequestV16Schema from "../../../vendor/ocpp-schemas/v16/Reset.json";
import resetResponseV16Schema from "../../../vendor/ocpp-schemas/v16/ResetResponse.json";
import securityEventNotificationRequestV16Schema from "../../../vendor/ocpp-schemas/v16/SecurityEventNotification.json";
import securityEventNotificationResponseV16Schema from "../../../vendor/ocpp-schemas/v16/SecurityEventNotificationResponse.json";
import sendLocalListRequestV16Schema from "../../../vendor/ocpp-schemas/v16/SendLocalList.json";
import sendLocalListResponseV16Schema from "../../../vendor/ocpp-schemas/v16/SendLocalListResponse.json";
import setChargingProfileRequestV16Schema from "../../../vendor/ocpp-schemas/v16/SetChargingProfile.json";
import setChargingProfileResponseV16Schema from "../../../vendor/ocpp-schemas/v16/SetChargingProfileResponse.json";
import signCertificateRequestV16Schema from "../../../vendor/ocpp-schemas/v16/SignCertificate.json";
import signCertificateResponseV16Schema from "../../../vendor/ocpp-schemas/v16/SignCertificateResponse.json";
import signedFirmwareStatusNotificationRequestV16Schema from "../../../vendor/ocpp-schemas/v16/SignedFirmwareStatusNotification.json";
import signedFirmwareStatusNotificationResponseV16Schema from "../../../vendor/ocpp-schemas/v16/SignedFirmwareStatusNotificationResponse.json";
import signedUpdateFirmwareRequestV16Schema from "../../../vendor/ocpp-schemas/v16/SignedUpdateFirmware.json";
import signedUpdateFirmwareResponseV16Schema from "../../../vendor/ocpp-schemas/v16/SignedUpdateFirmwareResponse.json";
import startTransactionRequestV16Schema from "../../../vendor/ocpp-schemas/v16/StartTransaction.json";
import startTransactionResponseV16Schema from "../../../vendor/ocpp-schemas/v16/StartTransactionResponse.json";
import statusNotificationRequestV16Schema from "../../../vendor/ocpp-schemas/v16/StatusNotification.json";
import statusNotificationResponseV16Schema from "../../../vendor/ocpp-schemas/v16/StatusNotificationResponse.json";
import stopTransactionRequestV16Schema from "../../../vendor/ocpp-schemas/v16/StopTransaction.json";
import stopTransactionResponseV16Schema from "../../../vendor/ocpp-schemas/v16/StopTransactionResponse.json";
import triggerMessageRequestV16Schema from "../../../vendor/ocpp-schemas/v16/TriggerMessage.json";
import triggerMessageResponseV16Schema from "../../../vendor/ocpp-schemas/v16/TriggerMessageResponse.json";
import unlockConnectorRequestV16Schema from "../../../vendor/ocpp-schemas/v16/UnlockConnector.json";
import unlockConnectorResponseV16Schema from "../../../vendor/ocpp-schemas/v16/UnlockConnectorResponse.json";
import updateFirmwareRequestV16Schema from "../../../vendor/ocpp-schemas/v16/UpdateFirmware.json";
import updateFirmwareResponseV16Schema from "../../../vendor/ocpp-schemas/v16/UpdateFirmwareResponse.json";

export const v16Schemas: Record<string, object> = {
  authorizeRequestV16: authorizeRequestV16Schema,
  authorizeResponseV16: authorizeResponseV16Schema,
  bootNotificationRequestV16: bootNotificationRequestV16Schema,
  bootNotificationResponseV16: bootNotificationResponseV16Schema,
  cancelReservationRequestV16: cancelReservationRequestV16Schema,
  cancelReservationResponseV16: cancelReservationResponseV16Schema,
  certificateSignedRequestV16: certificateSignedRequestV16Schema,
  certificateSignedResponseV16: certificateSignedResponseV16Schema,
  changeAvailabilityRequestV16: changeAvailabilityRequestV16Schema,
  changeAvailabilityResponseV16: changeAvailabilityResponseV16Schema,
  changeConfigurationRequestV16: changeConfigurationRequestV16Schema,
  changeConfigurationResponseV16: changeConfigurationResponseV16Schema,
  clearCacheRequestV16: clearCacheRequestV16Schema,
  clearCacheResponseV16: clearCacheResponseV16Schema,
  clearChargingProfileRequestV16: clearChargingProfileRequestV16Schema,
  clearChargingProfileResponseV16: clearChargingProfileResponseV16Schema,
  dataTransferRequestV16: dataTransferRequestV16Schema,
  dataTransferResponseV16: dataTransferResponseV16Schema,
  deleteCertificateRequestV16: deleteCertificateRequestV16Schema,
  deleteCertificateResponseV16: deleteCertificateResponseV16Schema,
  diagnosticsStatusNotificationRequestV16:
    diagnosticsStatusNotificationRequestV16Schema,
  diagnosticsStatusNotificationResponseV16:
    diagnosticsStatusNotificationResponseV16Schema,
  extendedTriggerMessageRequestV16: extendedTriggerMessageRequestV16Schema,
  extendedTriggerMessageResponseV16: extendedTriggerMessageResponseV16Schema,
  firmwareStatusNotificationRequestV16:
    firmwareStatusNotificationRequestV16Schema,
  firmwareStatusNotificationResponseV16:
    firmwareStatusNotificationResponseV16Schema,
  getCompositeScheduleRequestV16: getCompositeScheduleRequestV16Schema,
  getCompositeScheduleResponseV16: getCompositeScheduleResponseV16Schema,
  getConfigurationRequestV16: getConfigurationRequestV16Schema,
  getConfigurationResponseV16: getConfigurationResponseV16Schema,
  getDiagnosticsRequestV16: getDiagnosticsRequestV16Schema,
  getDiagnosticsResponseV16: getDiagnosticsResponseV16Schema,
  getInstalledCertificateIdsRequestV16:
    getInstalledCertificateIdsRequestV16Schema,
  getInstalledCertificateIdsResponseV16:
    getInstalledCertificateIdsResponseV16Schema,
  getLocalListVersionRequestV16: getLocalListVersionRequestV16Schema,
  getLocalListVersionResponseV16: getLocalListVersionResponseV16Schema,
  getLogRequestV16: getLogRequestV16Schema,
  getLogResponseV16: getLogResponseV16Schema,
  heartbeatRequestV16: heartbeatRequestV16Schema,
  heartbeatResponseV16: heartbeatResponseV16Schema,
  installCertificateRequestV16: installCertificateRequestV16Schema,
  installCertificateResponseV16: installCertificateResponseV16Schema,
  logStatusNotificationRequestV16: logStatusNotificationRequestV16Schema,
  logStatusNotificationResponseV16: logStatusNotificationResponseV16Schema,
  meterValuesRequestV16: meterValuesRequestV16Schema,
  meterValuesResponseV16: meterValuesResponseV16Schema,
  remoteStartTransactionRequestV16: remoteStartTransactionRequestV16Schema,
  remoteStartTransactionResponseV16: remoteStartTransactionResponseV16Schema,
  remoteStopTransactionRequestV16: remoteStopTransactionRequestV16Schema,
  remoteStopTransactionResponseV16: remoteStopTransactionResponseV16Schema,
  reserveNowRequestV16: reserveNowRequestV16Schema,
  reserveNowResponseV16: reserveNowResponseV16Schema,
  resetRequestV16: resetRequestV16Schema,
  resetResponseV16: resetResponseV16Schema,
  securityEventNotificationRequestV16:
    securityEventNotificationRequestV16Schema,
  securityEventNotificationResponseV16:
    securityEventNotificationResponseV16Schema,
  sendLocalListRequestV16: sendLocalListRequestV16Schema,
  sendLocalListResponseV16: sendLocalListResponseV16Schema,
  setChargingProfileRequestV16: setChargingProfileRequestV16Schema,
  setChargingProfileResponseV16: setChargingProfileResponseV16Schema,
  signCertificateRequestV16: signCertificateRequestV16Schema,
  signCertificateResponseV16: signCertificateResponseV16Schema,
  signedFirmwareStatusNotificationRequestV16:
    signedFirmwareStatusNotificationRequestV16Schema,
  signedFirmwareStatusNotificationResponseV16:
    signedFirmwareStatusNotificationResponseV16Schema,
  signedUpdateFirmwareRequestV16: signedUpdateFirmwareRequestV16Schema,
  signedUpdateFirmwareResponseV16: signedUpdateFirmwareResponseV16Schema,
  startTransactionRequestV16: startTransactionRequestV16Schema,
  startTransactionResponseV16: startTransactionResponseV16Schema,
  statusNotificationRequestV16: statusNotificationRequestV16Schema,
  statusNotificationResponseV16: statusNotificationResponseV16Schema,
  stopTransactionRequestV16: stopTransactionRequestV16Schema,
  stopTransactionResponseV16: stopTransactionResponseV16Schema,
  triggerMessageRequestV16: triggerMessageRequestV16Schema,
  triggerMessageResponseV16: triggerMessageResponseV16Schema,
  unlockConnectorRequestV16: unlockConnectorRequestV16Schema,
  unlockConnectorResponseV16: unlockConnectorResponseV16Schema,
  updateFirmwareRequestV16: updateFirmwareRequestV16Schema,
  updateFirmwareResponseV16: updateFirmwareResponseV16Schema,
};
