// Generated by scripts/generate-ocpp.ts. Do not edit.

import { validateOCPPPayload } from "../validate";
import { v16Schemas } from "./schemas";
import type { AuthorizeRequestV16 } from "./types/authorize-request";
import type { AuthorizeResponseV16 } from "./types/authorize-response";
import type { BootNotificationRequestV16 } from "./types/boot-notification-request";
import type { BootNotificationResponseV16 } from "./types/boot-notification-response";
import type { CancelReservationRequestV16 } from "./types/cancel-reservation-request";
import type { CancelReservationResponseV16 } from "./types/cancel-reservation-response";
import type { CertificateSignedRequestV16 } from "./types/certificate-signed-request";
import type { CertificateSignedResponseV16 } from "./types/certificate-signed-response";
import type { ChangeAvailabilityRequestV16 } from "./types/change-availability-request";
import type { ChangeAvailabilityResponseV16 } from "./types/change-availability-response";
import type { ChangeConfigurationRequestV16 } from "./types/change-configuration-request";
import type { ChangeConfigurationResponseV16 } from "./types/change-configuration-response";
import type { ClearCacheRequestV16 } from "./types/clear-cache-request";
import type { ClearCacheResponseV16 } from "./types/clear-cache-response";
import type { ClearChargingProfileRequestV16 } from "./types/clear-charging-profile-request";
import type { ClearChargingProfileResponseV16 } from "./types/clear-charging-profile-response";
import type { DataTransferRequestV16 } from "./types/data-transfer-request";
import type { DataTransferResponseV16 } from "./types/data-transfer-response";
import type { DeleteCertificateRequestV16 } from "./types/delete-certificate-request";
import type { DeleteCertificateResponseV16 } from "./types/delete-certificate-response";
import type { DiagnosticsStatusNotificationRequestV16 } from "./types/diagnostics-status-notification-request";
import type { DiagnosticsStatusNotificationResponseV16 } from "./types/diagnostics-status-notification-response";
import type { ExtendedTriggerMessageRequestV16 } from "./types/extended-trigger-message-request";
import type { ExtendedTriggerMessageResponseV16 } from "./types/extended-trigger-message-response";
import type { FirmwareStatusNotificationRequestV16 } from "./types/firmware-status-notification-request";
import type { FirmwareStatusNotificationResponseV16 } from "./types/firmware-status-notification-response";
import type { GetCompositeScheduleRequestV16 } from "./types/get-composite-schedule-request";
import type { GetCompositeScheduleResponseV16 } from "./types/get-composite-schedule-response";
import type { GetConfigurationRequestV16 } from "./types/get-configuration-request";
import type { GetConfigurationResponseV16 } from "./types/get-configuration-response";
import type { GetDiagnosticsRequestV16 } from "./types/get-diagnostics-request";
import type { GetDiagnosticsResponseV16 } from "./types/get-diagnostics-response";
import type { GetInstalledCertificateIdsRequestV16 } from "./types/get-installed-certificate-ids-request";
import type { GetInstalledCertificateIdsResponseV16 } from "./types/get-installed-certificate-ids-response";
import type { GetLocalListVersionRequestV16 } from "./types/get-local-list-version-request";
import type { GetLocalListVersionResponseV16 } from "./types/get-local-list-version-response";
import type { GetLogRequestV16 } from "./types/get-log-request";
import type { GetLogResponseV16 } from "./types/get-log-response";
import type { HeartbeatRequestV16 } from "./types/heartbeat-request";
import type { HeartbeatResponseV16 } from "./types/heartbeat-response";
import type { InstallCertificateRequestV16 } from "./types/install-certificate-request";
import type { InstallCertificateResponseV16 } from "./types/install-certificate-response";
import type { LogStatusNotificationRequestV16 } from "./types/log-status-notification-request";
import type { LogStatusNotificationResponseV16 } from "./types/log-status-notification-response";
import type { MeterValuesRequestV16 } from "./types/meter-values-request";
import type { MeterValuesResponseV16 } from "./types/meter-values-response";
import type { RemoteStartTransactionRequestV16 } from "./types/remote-start-transaction-request";
import type { RemoteStartTransactionResponseV16 } from "./types/remote-start-transaction-response";
import type { RemoteStopTransactionRequestV16 } from "./types/remote-stop-transaction-request";
import type { RemoteStopTransactionResponseV16 } from "./types/remote-stop-transaction-response";
import type { ReserveNowRequestV16 } from "./types/reserve-now-request";
import type { ReserveNowResponseV16 } from "./types/reserve-now-response";
import type { ResetRequestV16 } from "./types/reset-request";
import type { ResetResponseV16 } from "./types/reset-response";
import type { SecurityEventNotificationRequestV16 } from "./types/security-event-notification-request";
import type { SecurityEventNotificationResponseV16 } from "./types/security-event-notification-response";
import type { SendLocalListRequestV16 } from "./types/send-local-list-request";
import type { SendLocalListResponseV16 } from "./types/send-local-list-response";
import type { SetChargingProfileRequestV16 } from "./types/set-charging-profile-request";
import type { SetChargingProfileResponseV16 } from "./types/set-charging-profile-response";
import type { SignCertificateRequestV16 } from "./types/sign-certificate-request";
import type { SignCertificateResponseV16 } from "./types/sign-certificate-response";
import type { SignedFirmwareStatusNotificationRequestV16 } from "./types/signed-firmware-status-notification-request";
import type { SignedFirmwareStatusNotificationResponseV16 } from "./types/signed-firmware-status-notification-response";
import type { SignedUpdateFirmwareRequestV16 } from "./types/signed-update-firmware-request";
import type { SignedUpdateFirmwareResponseV16 } from "./types/signed-update-firmware-response";
import type { StartTransactionRequestV16 } from "./types/start-transaction-request";
import type { StartTransactionResponseV16 } from "./types/start-transaction-response";
import type { StatusNotificationRequestV16 } from "./types/status-notification-request";
import type { StatusNotificationResponseV16 } from "./types/status-notification-response";
import type { StopTransactionRequestV16 } from "./types/stop-transaction-request";
import type { StopTransactionResponseV16 } from "./types/stop-transaction-response";
import type { TriggerMessageRequestV16 } from "./types/trigger-message-request";
import type { TriggerMessageResponseV16 } from "./types/trigger-message-response";
import type { UnlockConnectorRequestV16 } from "./types/unlock-connector-request";
import type { UnlockConnectorResponseV16 } from "./types/unlock-connector-response";
import type { UpdateFirmwareRequestV16 } from "./types/update-firmware-request";
import type { UpdateFirmwareResponseV16 } from "./types/update-firmware-response";

export const isValidAuthorizeRequestV16 = (
  data: unknown,
): data is AuthorizeRequestV16 =>
  validateOCPPPayload(v16Schemas.authorizeRequestV16, data);

export const isValidAuthorizeResponseV16 = (
  data: unknown,
): data is AuthorizeResponseV16 =>
  validateOCPPPayload(v16Schemas.authorizeResponseV16, data);

export const isValidBootNotificationRequestV16 = (
  data: unknown,
): data is BootNotificationRequestV16 =>
  validateOCPPPayload(v16Schemas.bootNotificationRequestV16, data);

export const isValidBootNotificationResponseV16 = (
  data: unknown,
): data is BootNotificationResponseV16 =>
  validateOCPPPayload(v16Schemas.bootNotificationResponseV16, data);

export const isValidCancelReservationRequestV16 = (
  data: unknown,
): data is CancelReservationRequestV16 =>
  validateOCPPPayload(v16Schemas.cancelReservationRequestV16, data);

export const isValidCancelReservationResponseV16 = (
  data: unknown,
): data is CancelReservationResponseV16 =>
  validateOCPPPayload(v16Schemas.cancelReservationResponseV16, data);

export const isValidCertificateSignedRequestV16 = (
  data: unknown,
): data is CertificateSignedRequestV16 =>
  validateOCPPPayload(v16Schemas.certificateSignedRequestV16, data);

export const isValidCertificateSignedResponseV16 = (
  data: unknown,
): data is CertificateSignedResponseV16 =>
  validateOCPPPayload(v16Schemas.certificateSignedResponseV16, data);

export const isValidChangeAvailabilityRequestV16 = (
  data: unknown,
): data is ChangeAvailabilityRequestV16 =>
  validateOCPPPayload(v16Schemas.changeAvailabilityRequestV16, data);

export const isValidChangeAvailabilityResponseV16 = (
  data: unknown,
): data is ChangeAvailabilityResponseV16 =>
  validateOCPPPayload(v16Schemas.changeAvailabilityResponseV16, data);

export const isValidChangeConfigurationRequestV16 = (
  data: unknown,
): data is ChangeConfigurationRequestV16 =>
  validateOCPPPayload(v16Schemas.changeConfigurationRequestV16, data);

export const isValidChangeConfigurationResponseV16 = (
  data: unknown,
): data is ChangeConfigurationResponseV16 =>
  validateOCPPPayload(v16Schemas.changeConfigurationResponseV16, data);

export const isValidClearCacheRequestV16 = (
  data: unknown,
): data is ClearCacheRequestV16 =>
  validateOCPPPayload(v16Schemas.clearCacheRequestV16, data);

export const isValidClearCacheResponseV16 = (
  data: unknown,
): data is ClearCacheResponseV16 =>
  validateOCPPPayload(v16Schemas.clearCacheResponseV16, data);

export const isValidClearChargingProfileRequestV16 = (
  data: unknown,
): data is ClearChargingProfileRequestV16 =>
  validateOCPPPayload(v16Schemas.clearChargingProfileRequestV16, data);

export const isValidClearChargingProfileResponseV16 = (
  data: unknown,
): data is ClearChargingProfileResponseV16 =>
  validateOCPPPayload(v16Schemas.clearChargingProfileResponseV16, data);

export const isValidDataTransferRequestV16 = (
  data: unknown,
): data is DataTransferRequestV16 =>
  validateOCPPPayload(v16Schemas.dataTransferRequestV16, data);

export const isValidDataTransferResponseV16 = (
  data: unknown,
): data is DataTransferResponseV16 =>
  validateOCPPPayload(v16Schemas.dataTransferResponseV16, data);

export const isValidDeleteCertificateRequestV16 = (
  data: unknown,
): data is DeleteCertificateRequestV16 =>
  validateOCPPPayload(v16Schemas.deleteCertificateRequestV16, data);

export const isValidDeleteCertificateResponseV16 = (
  data: unknown,
): data is DeleteCertificateResponseV16 =>
  validateOCPPPayload(v16Schemas.deleteCertificateResponseV16, data);

export const isValidDiagnosticsStatusNotificationRequestV16 = (
  data: unknown,
): data is DiagnosticsStatusNotificationRequestV16 =>
  validateOCPPPayload(v16Schemas.diagnosticsStatusNotificationRequestV16, data);

export const isValidDiagnosticsStatusNotificationResponseV16 = (
  data: unknown,
): data is DiagnosticsStatusNotificationResponseV16 =>
  validateOCPPPayload(
    v16Schemas.diagnosticsStatusNotificationResponseV16,
    data,
  );

export const isValidExtendedTriggerMessageRequestV16 = (
  data: unknown,
): data is ExtendedTriggerMessageRequestV16 =>
  validateOCPPPayload(v16Schemas.extendedTriggerMessageRequestV16, data);

export const isValidExtendedTriggerMessageResponseV16 = (
  data: unknown,
): data is ExtendedTriggerMessageResponseV16 =>
  validateOCPPPayload(v16Schemas.extendedTriggerMessageResponseV16, data);

export const isValidFirmwareStatusNotificationRequestV16 = (
  data: unknown,
): data is FirmwareStatusNotificationRequestV16 =>
  validateOCPPPayload(v16Schemas.firmwareStatusNotificationRequestV16, data);

export const isValidFirmwareStatusNotificationResponseV16 = (
  data: unknown,
): data is FirmwareStatusNotificationResponseV16 =>
  validateOCPPPayload(v16Schemas.firmwareStatusNotificationResponseV16, data);

export const isValidGetCompositeScheduleRequestV16 = (
  data: unknown,
): data is GetCompositeScheduleRequestV16 =>
  validateOCPPPayload(v16Schemas.getCompositeScheduleRequestV16, data);

export const isValidGetCompositeScheduleResponseV16 = (
  data: unknown,
): data is GetCompositeScheduleResponseV16 =>
  validateOCPPPayload(v16Schemas.getCompositeScheduleResponseV16, data);

export const isValidGetConfigurationRequestV16 = (
  data: unknown,
): data is GetConfigurationRequestV16 =>
  validateOCPPPayload(v16Schemas.getConfigurationRequestV16, data);

export const isValidGetConfigurationResponseV16 = (
  data: unknown,
): data is GetConfigurationResponseV16 =>
  validateOCPPPayload(v16Schemas.getConfigurationResponseV16, data);

export const isValidGetDiagnosticsRequestV16 = (
  data: unknown,
): data is GetDiagnosticsRequestV16 =>
  validateOCPPPayload(v16Schemas.getDiagnosticsRequestV16, data);

export const isValidGetDiagnosticsResponseV16 = (
  data: unknown,
): data is GetDiagnosticsResponseV16 =>
  validateOCPPPayload(v16Schemas.getDiagnosticsResponseV16, data);

export const isValidGetInstalledCertificateIdsRequestV16 = (
  data: unknown,
): data is GetInstalledCertificateIdsRequestV16 =>
  validateOCPPPayload(v16Schemas.getInstalledCertificateIdsRequestV16, data);

export const isValidGetInstalledCertificateIdsResponseV16 = (
  data: unknown,
): data is GetInstalledCertificateIdsResponseV16 =>
  validateOCPPPayload(v16Schemas.getInstalledCertificateIdsResponseV16, data);

export const isValidGetLocalListVersionRequestV16 = (
  data: unknown,
): data is GetLocalListVersionRequestV16 =>
  validateOCPPPayload(v16Schemas.getLocalListVersionRequestV16, data);

export const isValidGetLocalListVersionResponseV16 = (
  data: unknown,
): data is GetLocalListVersionResponseV16 =>
  validateOCPPPayload(v16Schemas.getLocalListVersionResponseV16, data);

export const isValidGetLogRequestV16 = (
  data: unknown,
): data is GetLogRequestV16 =>
  validateOCPPPayload(v16Schemas.getLogRequestV16, data);

export const isValidGetLogResponseV16 = (
  data: unknown,
): data is GetLogResponseV16 =>
  validateOCPPPayload(v16Schemas.getLogResponseV16, data);

export const isValidHeartbeatRequestV16 = (
  data: unknown,
): data is HeartbeatRequestV16 =>
  validateOCPPPayload(v16Schemas.heartbeatRequestV16, data);

export const isValidHeartbeatResponseV16 = (
  data: unknown,
): data is HeartbeatResponseV16 =>
  validateOCPPPayload(v16Schemas.heartbeatResponseV16, data);

export const isValidInstallCertificateRequestV16 = (
  data: unknown,
): data is InstallCertificateRequestV16 =>
  validateOCPPPayload(v16Schemas.installCertificateRequestV16, data);

export const isValidInstallCertificateResponseV16 = (
  data: unknown,
): data is InstallCertificateResponseV16 =>
  validateOCPPPayload(v16Schemas.installCertificateResponseV16, data);

export const isValidLogStatusNotificationRequestV16 = (
  data: unknown,
): data is LogStatusNotificationRequestV16 =>
  validateOCPPPayload(v16Schemas.logStatusNotificationRequestV16, data);

export const isValidLogStatusNotificationResponseV16 = (
  data: unknown,
): data is LogStatusNotificationResponseV16 =>
  validateOCPPPayload(v16Schemas.logStatusNotificationResponseV16, data);

export const isValidMeterValuesRequestV16 = (
  data: unknown,
): data is MeterValuesRequestV16 =>
  validateOCPPPayload(v16Schemas.meterValuesRequestV16, data);

export const isValidMeterValuesResponseV16 = (
  data: unknown,
): data is MeterValuesResponseV16 =>
  validateOCPPPayload(v16Schemas.meterValuesResponseV16, data);

export const isValidRemoteStartTransactionRequestV16 = (
  data: unknown,
): data is RemoteStartTransactionRequestV16 =>
  validateOCPPPayload(v16Schemas.remoteStartTransactionRequestV16, data);

export const isValidRemoteStartTransactionResponseV16 = (
  data: unknown,
): data is RemoteStartTransactionResponseV16 =>
  validateOCPPPayload(v16Schemas.remoteStartTransactionResponseV16, data);

export const isValidRemoteStopTransactionRequestV16 = (
  data: unknown,
): data is RemoteStopTransactionRequestV16 =>
  validateOCPPPayload(v16Schemas.remoteStopTransactionRequestV16, data);

export const isValidRemoteStopTransactionResponseV16 = (
  data: unknown,
): data is RemoteStopTransactionResponseV16 =>
  validateOCPPPayload(v16Schemas.remoteStopTransactionResponseV16, data);

export const isValidReserveNowRequestV16 = (
  data: unknown,
): data is ReserveNowRequestV16 =>
  validateOCPPPayload(v16Schemas.reserveNowRequestV16, data);

export const isValidReserveNowResponseV16 = (
  data: unknown,
): data is ReserveNowResponseV16 =>
  validateOCPPPayload(v16Schemas.reserveNowResponseV16, data);

export const isValidResetRequestV16 = (
  data: unknown,
): data is ResetRequestV16 =>
  validateOCPPPayload(v16Schemas.resetRequestV16, data);

export const isValidResetResponseV16 = (
  data: unknown,
): data is ResetResponseV16 =>
  validateOCPPPayload(v16Schemas.resetResponseV16, data);

export const isValidSecurityEventNotificationRequestV16 = (
  data: unknown,
): data is SecurityEventNotificationRequestV16 =>
  validateOCPPPayload(v16Schemas.securityEventNotificationRequestV16, data);

export const isValidSecurityEventNotificationResponseV16 = (
  data: unknown,
): data is SecurityEventNotificationResponseV16 =>
  validateOCPPPayload(v16Schemas.securityEventNotificationResponseV16, data);

export const isValidSendLocalListRequestV16 = (
  data: unknown,
): data is SendLocalListRequestV16 =>
  validateOCPPPayload(v16Schemas.sendLocalListRequestV16, data);

export const isValidSendLocalListResponseV16 = (
  data: unknown,
): data is SendLocalListResponseV16 =>
  validateOCPPPayload(v16Schemas.sendLocalListResponseV16, data);

export const isValidSetChargingProfileRequestV16 = (
  data: unknown,
): data is SetChargingProfileRequestV16 =>
  validateOCPPPayload(v16Schemas.setChargingProfileRequestV16, data);

export const isValidSetChargingProfileResponseV16 = (
  data: unknown,
): data is SetChargingProfileResponseV16 =>
  validateOCPPPayload(v16Schemas.setChargingProfileResponseV16, data);

export const isValidSignCertificateRequestV16 = (
  data: unknown,
): data is SignCertificateRequestV16 =>
  validateOCPPPayload(v16Schemas.signCertificateRequestV16, data);

export const isValidSignCertificateResponseV16 = (
  data: unknown,
): data is SignCertificateResponseV16 =>
  validateOCPPPayload(v16Schemas.signCertificateResponseV16, data);

export const isValidSignedFirmwareStatusNotificationRequestV16 = (
  data: unknown,
): data is SignedFirmwareStatusNotificationRequestV16 =>
  validateOCPPPayload(
    v16Schemas.signedFirmwareStatusNotificationRequestV16,
    data,
  );

export const isValidSignedFirmwareStatusNotificationResponseV16 = (
  data: unknown,
): data is SignedFirmwareStatusNotificationResponseV16 =>
  validateOCPPPayload(
    v16Schemas.signedFirmwareStatusNotificationResponseV16,
    data,
  );

export const isValidSignedUpdateFirmwareRequestV16 = (
  data: unknown,
): data is SignedUpdateFirmwareRequestV16 =>
  validateOCPPPayload(v16Schemas.signedUpdateFirmwareRequestV16, data);

export const isValidSignedUpdateFirmwareResponseV16 = (
  data: unknown,
): data is SignedUpdateFirmwareResponseV16 =>
  validateOCPPPayload(v16Schemas.signedUpdateFirmwareResponseV16, data);

export const isValidStartTransactionRequestV16 = (
  data: unknown,
): data is StartTransactionRequestV16 =>
  validateOCPPPayload(v16Schemas.startTransactionRequestV16, data);

export const isValidStartTransactionResponseV16 = (
  data: unknown,
): data is StartTransactionResponseV16 =>
  validateOCPPPayload(v16Schemas.startTransactionResponseV16, data);

export const isValidStatusNotificationRequestV16 = (
  data: unknown,
): data is StatusNotificationRequestV16 =>
  validateOCPPPayload(v16Schemas.statusNotificationRequestV16, data);

export const isValidStatusNotificationResponseV16 = (
  data: unknown,
): data is StatusNotificationResponseV16 =>
  validateOCPPPayload(v16Schemas.statusNotificationResponseV16, data);

export const isValidStopTransactionRequestV16 = (
  data: unknown,
): data is StopTransactionRequestV16 =>
  validateOCPPPayload(v16Schemas.stopTransactionRequestV16, data);

export const isValidStopTransactionResponseV16 = (
  data: unknown,
): data is StopTransactionResponseV16 =>
  validateOCPPPayload(v16Schemas.stopTransactionResponseV16, data);

export const isValidTriggerMessageRequestV16 = (
  data: unknown,
): data is TriggerMessageRequestV16 =>
  validateOCPPPayload(v16Schemas.triggerMessageRequestV16, data);

export const isValidTriggerMessageResponseV16 = (
  data: unknown,
): data is TriggerMessageResponseV16 =>
  validateOCPPPayload(v16Schemas.triggerMessageResponseV16, data);

export const isValidUnlockConnectorRequestV16 = (
  data: unknown,
): data is UnlockConnectorRequestV16 =>
  validateOCPPPayload(v16Schemas.unlockConnectorRequestV16, data);

export const isValidUnlockConnectorResponseV16 = (
  data: unknown,
): data is UnlockConnectorResponseV16 =>
  validateOCPPPayload(v16Schemas.unlockConnectorResponseV16, data);

export const isValidUpdateFirmwareRequestV16 = (
  data: unknown,
): data is UpdateFirmwareRequestV16 =>
  validateOCPPPayload(v16Schemas.updateFirmwareRequestV16, data);

export const isValidUpdateFirmwareResponseV16 = (
  data: unknown,
): data is UpdateFirmwareResponseV16 =>
  validateOCPPPayload(v16Schemas.updateFirmwareResponseV16, data);

export const actionValidatorV16: Record<string, (data: unknown) => boolean> = {
  Authorize: isValidAuthorizeRequestV16,
  BootNotification: isValidBootNotificationRequestV16,
  CancelReservation: isValidCancelReservationRequestV16,
  CertificateSigned: isValidCertificateSignedRequestV16,
  ChangeAvailability: isValidChangeAvailabilityRequestV16,
  ChangeConfiguration: isValidChangeConfigurationRequestV16,
  ClearCache: isValidClearCacheRequestV16,
  ClearChargingProfile: isValidClearChargingProfileRequestV16,
  DataTransfer: isValidDataTransferRequestV16,
  DeleteCertificate: isValidDeleteCertificateRequestV16,
  DiagnosticsStatusNotification: isValidDiagnosticsStatusNotificationRequestV16,
  ExtendedTriggerMessage: isValidExtendedTriggerMessageRequestV16,
  FirmwareStatusNotification: isValidFirmwareStatusNotificationRequestV16,
  GetCompositeSchedule: isValidGetCompositeScheduleRequestV16,
  GetConfiguration: isValidGetConfigurationRequestV16,
  GetDiagnostics: isValidGetDiagnosticsRequestV16,
  GetInstalledCertificateIds: isValidGetInstalledCertificateIdsRequestV16,
  GetLocalListVersion: isValidGetLocalListVersionRequestV16,
  GetLog: isValidGetLogRequestV16,
  Heartbeat: isValidHeartbeatRequestV16,
  InstallCertificate: isValidInstallCertificateRequestV16,
  LogStatusNotification: isValidLogStatusNotificationRequestV16,
  MeterValues: isValidMeterValuesRequestV16,
  RemoteStartTransaction: isValidRemoteStartTransactionRequestV16,
  RemoteStopTransaction: isValidRemoteStopTransactionRequestV16,
  ReserveNow: isValidReserveNowRequestV16,
  Reset: isValidResetRequestV16,
  SecurityEventNotification: isValidSecurityEventNotificationRequestV16,
  SendLocalList: isValidSendLocalListRequestV16,
  SetChargingProfile: isValidSetChargingProfileRequestV16,
  SignCertificate: isValidSignCertificateRequestV16,
  SignedFirmwareStatusNotification:
    isValidSignedFirmwareStatusNotificationRequestV16,
  SignedUpdateFirmware: isValidSignedUpdateFirmwareRequestV16,
  StartTransaction: isValidStartTransactionRequestV16,
  StatusNotification: isValidStatusNotificationRequestV16,
  StopTransaction: isValidStopTransactionRequestV16,
  TriggerMessage: isValidTriggerMessageRequestV16,
  UnlockConnector: isValidUnlockConnectorRequestV16,
  UpdateFirmware: isValidUpdateFirmwareRequestV16,
};
