// Generated by scripts/generate-ocpp.ts. Do not edit.

import adjustPeriodicEventStreamRequestV21Schema from "../../../vendor/ocpp-schemas/v21/AdjustPeriodicEventStreamRequest.json";
import adjustPeriodicEventStreamResponseV21Schema from "../../../vendor/ocpp-schemas/v21/AdjustPeriodicEventStreamResponse.json";
import aFRRSignalRequestV21Schema from "../../../vendor/ocpp-schemas/v21/AFRRSignalRequest.json";
import aFRRSignalResponseV21Schema from "../../../vendor/ocpp-schemas/v21/AFRRSignalResponse.json";
import authorizeRequestV21Schema from "../../../vendor/ocpp-schemas/v21/AuthorizeRequest.json";
import authorizeResponseV21Schema from "../../../vendor/ocpp-schemas/v21/AuthorizeResponse.json";
import batterySwapRequestV21Schema from "../../../vendor/ocpp-schemas/v21/BatterySwapRequest.json";
import batterySwapResponseV21Schema from "../../../vendor/ocpp-schemas/v21/BatterySwapResponse.json";
import bootNotificationRequestV21Schema from "../../../vendor/ocpp-schemas/v21/BootNotificationRequest.json";
import bootNotificationResponseV21Schema from "../../../vendor/ocpp-schemas/v21/BootNotificationResponse.json";
import cancelReservationRequestV21Schema from "../../../vendor/ocpp-schemas/v21/CancelReservationRequest.json";
import cancelReservationResponseV21Schema from "../../../vendor/ocpp-schemas/v21/CancelReservationResponse.json";
import certificateSignedRequestV21Schema from "../../../vendor/ocpp-schemas/v21/CertificateSignedRequest.json";
import certificateSignedResponseV21Schema from "../../../vendor/ocpp-schemas/v21/CertificateSignedResponse.json";
import changeAvailabilityRequestV21Schema from "../../../vendor/ocpp-schemas/v21/ChangeAvailabilityRequest.json";
import changeAvailabilityResponseV21Schema from "../../../vendor/ocpp-schemas/v21/ChangeAvailabilityResponse.json";
import changeTransactionTariffRequestV21Schema from "../../../vendor/ocpp-schemas/v21/ChangeTransactionTariffRequest.json";
import changeTransactionTariffResponseV21Schema from "../../../vendor/ocpp-schemas/v21/ChangeTransactionTariffResponse.json";
import clearCacheRequestV21Schema from "../../../vendor/ocpp-schemas/v21/ClearCacheRequest.json";
import clearCacheResponseV21Schema from "../../../vendor/ocpp-schemas/v21/ClearCacheResponse.json";
import clearChargingProfileRequestV21Schema from "../../../vendor/ocpp-schemas/v21/ClearChargingProfileRequest.json";
import clearChargingProfileResponseV21Schema from "../../../vendor/ocpp-schemas/v21/ClearChargingProfileResponse.json";
import clearDERControlRequestV21Schema from "../../../vendor/ocpp-schemas/v21/ClearDERControlRequest.json";
import clearDERControlResponseV21Schema from "../../../vendor/ocpp-schemas/v21/ClearDERControlResponse.json";
import clearDisplayMessageRequestV21Schema from "../../../vendor/ocpp-schemas/v21/ClearDisplayMessageRequest.json";
import clearDisplayMessageResponseV21Schema from "../../../vendor/ocpp-schemas/v21/ClearDisplayMessageResponse.json";
import clearedChargingLimitRequestV21Schema from "../../../vendor/ocpp-schemas/v21/ClearedChargingLimitRequest.json";
import clearedChargingLimitResponseV21Schema from "../../../vendor/ocpp-schemas/v21/ClearedChargingLimitResponse.json";
import clearTariffsRequestV21Schema from "../../../vendor/ocpp-schemas/v21/ClearTariffsRequest.json";
import clearTariffsResponseV21Schema from "../../../vendor/ocpp-schemas/v21/ClearTariffsResponse.json";
import clearVariableMonitoringRequestV21Schema from "../../../vendor/ocpp-schemas/v21/ClearVariableMonitoringRequest.json";
import clearVariableMonitoringResponseV21Schema from "../../../vendor/ocpp-schemas/v21/ClearVariableMonitoringResponse.json";
import closePeriodicEventStreamRequestV21Schema from "../../../vendor/ocpp-schemas/v21/ClosePeriodicEventStreamRequest.json";
import closePeriodicEventStreamResponseV21Schema from "../../../vendor/ocpp-schemas/v21/ClosePeriodicEventStreamResponse.json";
import costUpdatedRequestV21Schema from "../../../vendor/ocpp-schemas/v21/CostUpdatedRequest.json";
import costUpdatedResponseV21Schema from "../../../vendor/ocpp-schemas/v21/CostUpdatedResponse.json";
import customerInformationRequestV21Schema from "../../../vendor/ocpp-schemas/v21/CustomerInformationRequest.json";
import customerInformationResponseV21Schema from "../../../vendor/ocpp-schemas/v21/CustomerInformationResponse.json";
import dataTransferRequestV21Schema from "../../../vendor/ocpp-schemas/v21/DataTransferRequest.json";
import dataTransferResponseV21Schema from "../../../vendor/ocpp-schemas/v21/DataTransferResponse.json";
import deleteCertificateRequestV21Schema from "../../../vendor/ocpp-schemas/v21/DeleteCertificateRequest.json";
import deleteCertificateResponseV21Schema from "../../../vendor/ocpp-schemas/v21/DeleteCertificateResponse.json";
import firmwareStatusNotificationRequestV21Schema from "../../../vendor/ocpp-schemas/v21/FirmwareStatusNotificationRequest.json";
import firmwareStatusNotificationResponseV21Schema from "../../../vendor/ocpp-schemas/v21/FirmwareStatusNotificationResponse.json";
import get15118EVCertificateRequestV21Schema from "../../../vendor/ocpp-schemas/v21/Get15118EVCertificateRequest.json";
import get15118EVCertificateResponseV21Schema from "../../../vendor/ocpp-schemas/v21/Get15118EVCertificateResponse.json";
import getBaseReportRequestV21Schema from "../../../vendor/ocpp-schemas/v21/GetBaseReportRequest.json";
import getBaseReportResponseV21Schema from "../../../vendor/ocpp-schemas/v21/GetBaseReportResponse.json";
import getCertificateChainStatusRequestV21Schema from "../../../vendor/ocpp-schemas/v21/GetCertificateChainStatusRequest.json";
import getCertificateChainStatusResponseV21Schema from "../../../vendor/ocpp-schemas/v21/GetCertificateChainStatusResponse.json";
import getCertificateStatusRequestV21Schema from "../../../vendor/ocpp-schemas/v21/GetCertificateStatusRequest.json";
import getCertificateStatusResponseV21Schema from "../../../vendor/ocpp-schemas/v21/GetCertificateStatusResponse.json";
import getChargingProfilesRequestV21Schema from "../../../vendor/ocpp-schemas/v21/GetChargingProfilesRequest.json";
import getChargingProfilesResponseV21Schema from "../../../vendor/ocpp-schemas/v21/GetChargingProfilesResponse.json";
import getCompositeScheduleRequestV21Schema from "../../../vendor/ocpp-schemas/v21/GetCompositeScheduleRequest.json";
import getCompositeScheduleResponseV21Schema from "../../../vendor/ocpp-schemas/v21/GetCompositeScheduleResponse.json";
import getDERControlRequestV21Schema from "../../../vendor/ocpp-schemas/v21/GetDERControlRequest.json";
import getDERControlResponseV21Schema from "../../../vendor/ocpp-schemas/v21/GetDERControlResponse.json";
import getDisplayMessagesRequestV21Schema from "../../../vendor/ocpp-schemas/v21/GetDisplayMessagesRequest.json";
import getDisplayMessagesResponseV21Schema from "../../../vendor/ocpp-schemas/v21/GetDisplayMessagesResponse.json";
import getInstalledCertificateIdsRequestV21Schema from "../../../vendor/ocpp-schemas/v21/GetInstalledCertificateIdsRequest.json";
import getInstalledCertificateIdsResponseV21Schema from "../../../vendor/ocpp-schemas/v21/GetInstalledCertificateIdsResponse.json";
import getLocalListVersionRequestV21Schema from "../../../vendor/ocpp-schemas/v21/GetLocalListVersionRequest.json";
import getLocalListVersionResponseV21Schema from "../../../vendor/ocpp-schemas/v21/GetLocalListVersionResponse.json";
import getLogRequestV21Schema from "../../../vendor/ocpp-schemas/v21/GetLogRequest.json";
import getLogResponseV21Schema from "../../../vendor/ocpp-schemas/v21/GetLogResponse.json";
import getMonitoringReportRequestV21Schema from "../../../vendor/ocpp-schemas/v21/GetMonitoringReportRequest.json";
import getMonitoringReportResponseV21Schema from "../../../vendor/ocpp-schemas/v21/GetMonitoringReportResponse.json";
import getPeriodicEventStreamRequestV21Schema from "../../../vendor/ocpp-schemas/v21/GetPeriodicEventStreamRequest.json";
import getPeriodicEventStreamResponseV21Schema from "../../../vendor/ocpp-schemas/v21/GetPeriodicEventStreamResponse.json";
import getReportRequestV21Schema from "../../../vendor/ocpp-schemas/v21/GetReportRequest.json";
import getReportResponseV21Schema from "../../../vendor/ocpp-schemas/v21/GetReportResponse.json";
import getTariffsRequestV21Schema from "../../../vendor/ocpp-schemas/v21/GetTariffsRequest.json";
import getTariffsResponseV21Schema from "../../../vendor/ocpp-schemas/v21/GetTariffsResponse.json";
import getTransactionStatusRequestV21Schema from "../../../vendor/ocpp-schemas/v21/GetTransactionStatusRequest.json";
import getTransactionStatusResponseV21Schema from "../../../vendor/ocpp-schemas/v21/GetTransactionStatusResponse.json";
import getVariablesRequestV21Schema from "../../../vendor/ocpp-schemas/v21/GetVariablesRequest.json";
import getVariablesResponseV21Schema from "../../../vendor/ocpp-schemas/v21/GetVariablesResponse.json";
import heartbeatRequestV21Schema from "../../../vendor/ocpp-schemas/v21/HeartbeatRequest.json";
import heartbeatResponseV21Schema from "../../../vendor/ocpp-schemas/v21/HeartbeatResponse.json";
import installCertificateRequestV21Schema from "../../../vendor/ocpp-schemas/v21/InstallCertificateRequest.json";
import installCertificateResponseV21Schema from "../../../vendor/ocpp-schemas/v21/InstallCertificateResponse.json";
import logStatusNotificationRequestV21Schema from "../../../vendor/ocpp-schemas/v21/LogStatusNotificationRequest.json";
import logStatusNotificationResponseV21Schema from "../../../vendor/ocpp-schemas/v21/LogStatusNotificationResponse.json";
import meterValuesRequestV21Schema from "../../../vendor/ocpp-schemas/v21/MeterValuesRequest.json";
import meterValuesResponseV21Schema from "../../../vendor/ocpp-schemas/v21/MeterValuesResponse.json";
import notifyAllowedEnergyTransferRequestV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyAllowedEnergyTransferRequest.json";
import notifyAllowedEnergyTransferResponseV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyAllowedEnergyTransferResponse.json";
import notifyChargingLimitRequestV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyChargingLimitRequest.json";
import notifyChargingLimitResponseV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyChargingLimitResponse.json";
import notifyCustomerInformationRequestV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyCustomerInformationRequest.json";
import notifyCustomerInformationResponseV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyCustomerInformationResponse.json";
import notifyDERAlarmRequestV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyDERAlarmRequest.json";
import notifyDERAlarmResponseV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyDERAlarmResponse.json";
import notifyDERStartStopRequestV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyDERStartStopRequest.json";
import notifyDERStartStopResponseV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyDERStartStopResponse.json";
import notifyDisplayMessagesRequestV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyDisplayMessagesRequest.json";
import notifyDisplayMessagesResponseV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyDisplayMessagesResponse.json";
import notifyEVChargingNeedsRequestV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyEVChargingNeedsRequest.json";
import notifyEVChargingNeedsResponseV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyEVChargingNeedsResponse.json";
import notifyEVChargingScheduleRequestV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyEVChargingScheduleRequest.json";
import notifyEVChargingScheduleResponseV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyEVChargingScheduleResponse.json";
import notifyEventRequestV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyEventRequest.json";
import notifyEventResponseV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyEventResponse.json";
import notifyMonitoringReportRequestV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyMonitoringReportRequest.json";
import notifyMonitoringReportResponseV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyMonitoringReportResponse.json";
import notifyPeriodicEventStreamRequestV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyPeriodicEventStream.json";
import notifyPriorityChargingRequestV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyPriorityChargingRequest.json";
import notifyPriorityChargingResponseV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyPriorityChargingResponse.json";
import notifyReportRequestV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyReportRequest.json";
import notifyReportResponseV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyReportResponse.json";
import notifySettlementRequestV21Schema from "../../../vendor/ocpp-schemas/v21/NotifySettlementRequest.json";
import notifySettlementResponseV21Schema from "../../../vendor/ocpp-schemas/v21/NotifySettlementResponse.json";
import notifyWebPaymentStartedRequestV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyWebPaymentStartedRequest.json";
import notifyWebPaymentStartedResponseV21Schema from "../../../vendor/ocpp-schemas/v21/NotifyWebPaymentStartedResponse.json";
import openPeriodicEventStreamRequestV21Schema from "../../../vendor/ocpp-schemas/v21/OpenPeriodicEventStreamRequest.json";
import openPeriodicEventStreamResponseV21Schema from "../../../vendor/ocpp-schemas/v21/OpenPeriodicEventStreamResponse.json";
import publishFirmwareRequestV21Schema from "../../../vendor/ocpp-schemas/v21/PublishFirmwareRequest.json";
import publishFirmwareResponseV21Schema from "../../../vendor/ocpp-schemas/v21/PublishFirmwareResponse.json";
import publishFirmwareStatusNotificationRequestV21Schema from "../../../vendor/ocpp-schemas/v21/PublishFirmwareStatusNotificationRequest.json";
import publishFirmwareStatusNotificationResponseV21Schema from "../../../vendor/ocpp-schemas/v21/PublishFirmwareStatusNotificationResponse.json";
import pullDynamicScheduleUpdateRequestV21Schema from "../../../vendor/ocpp-schemas/v21/PullDynamicScheduleUpdateRequest.json";
import pullDynamicScheduleUpdateResponseV21Schema from "../../../vendor/ocpp-schemas/v21/PullDynamicScheduleUpdateResponse.json";
import reportChargingProfilesRequestV21Schema from "../../../vendor/ocpp-schemas/v21/ReportChargingProfilesRequest.json";
import reportChargingProfilesResponseV21Schema from "../../../vendor/ocpp-schemas/v21/ReportChargingProfilesResponse.json";
import reportDERControlRequestV21Schema from "../../../vendor/ocpp-schemas/v21/ReportDERControlRequest.json";
import reportDERControlResponseV21Schema from "../../../vendor/ocpp-schemas/v21/ReportDERControlResponse.json";
import requestBatterySwapRequestV21Schema from "../../../vendor/ocpp-schemas/v21/RequestBatterySwapRequest.json";
import requestBatterySwapResponseV21Schema from "../../../vendor/ocpp-schemas/v21/RequestBatterySwapResponse.json";
import requestStartTransactionRequestV21Schema from "../../../vendor/ocpp-schemas/v21/RequestStartTransactionRequest.json";
import requestStartTransactionResponseV21Schema from "../../../vendor/ocpp-schemas/v21/RequestStartTransactionResponse.json";
import requestStopTransactionRequestV21Schema from "../../../vendor/ocpp-schemas/v21/RequestStopTransactionRequest.json";
import requestStopTransactionResponseV21Schema from "../../../vendor/ocpp-schemas/v21/RequestStopTransactionResponse.json";
import reservationStatusUpdateRequestV21Schema from "../../../vendor/ocpp-schemas/v21/ReservationStatusUpdateRequest.json";
import reservationStatusUpdateResponseV21Schema from "../../../vendor/ocpp-schemas/v21/ReservationStatusUpdateResponse.json";
import reserveNowRequestV21Schema from "../../../vendor/ocpp-schemas/v21/ReserveNowRequest.json";
import reserveNowResponseV21Schema from "../../../vendor/ocpp-schemas/v21/ReserveNowResponse.json";
import resetRequestV21Schema from "../../../vendor/ocpp-schemas/v21/ResetRequest.json";
import resetResponseV21Schema from "../../../vendor/ocpp-schemas/v21/ResetResponse.json";
import securityEventNotificationRequestV21Schema from "../../../vendor/ocpp-schemas/v21/SecurityEventNotificationRequest.json";
import securityEventNotificationResponseV21Schema from "../../../vendor/ocpp-schemas/v21/SecurityEventNotificationResponse.json";
import sendLocalListRequestV21Schema from "../../../vendor/ocpp-schemas/v21/SendLocalListRequest.json";
import sendLocalListResponseV21Schema from "../../../vendor/ocpp-schemas/v21/SendLocalListResponse.json";
import setChargingProfileRequestV21Schema from "../../../vendor/ocpp-schemas/v21/SetChargingProfileRequest.json";
import setChargingProfileResponseV21Schema from "../../../vendor/ocpp-schemas/v21/SetChargingProfileResponse.json";
import setDefaultTariffRequestV21Schema from "../../../vendor/ocpp-schemas/v21/SetDefaultTariffRequest.json";
import setDefaultTariffResponseV21Schema from "../../../vendor/ocpp-schemas/v21/SetDefaultTariffResponse.json";
import setDERControlRequestV21Schema from "../../../vendor/ocpp-schemas/v21/SetDERControlRequest.json";
import setDERControlResponseV21Schema from "../../../vendor/ocpp-schemas/v21/SetDERControlResponse.json";
import setDisplayMessageRequestV21Schema from "../../../vendor/ocpp-schemas/v21/SetDisplayMessageRequest.json";
import setDisplayMessageResponseV21Schema from "../../../vendor/ocpp-schemas/v21/SetDisplayMessageResponse.json";
import setMonitoringBaseRequestV21Schema from "../../../vendor/ocpp-schemas/v21/SetMonitoringBaseRequest.json";
import setMonitoringBaseResponseV21Schema from "../../../vendor/ocpp-schemas/v21/SetMonitoringBaseResponse.json";
import setMonitoringLevelRequestV21Schema from "../../../vendor/ocpp-schemas/v21/SetMonitoringLevelRequest.json";
import setMonitoringLevelResponseV21Schema from "../../../vendor/ocpp-schemas/v21/SetMonitoringLevelResponse.json";
import setNetworkProfileRequestV21Schema from "../../../vendor/ocpp-schemas/v21/SetNetworkProfileRequest.json";
import setNetworkProfileResponseV21Schema from "../../../vendor/ocpp-schemas/v21/SetNetworkProfileResponse.json";
import setVariableMonitoringRequestV21Schema from "../../../vendor/ocpp-schemas/v21/SetVariableMonitoringRequest.json";
import setVariableMonitoringResponseV21Schema from "../../../vendor/ocpp-schemas/v21/SetVariableMonitoringResponse.json";
import setVariablesRequestV21Schema from "../../../vendor/ocpp-schemas/v21/SetVariablesRequest.json";
import setVariablesResponseV21Schema from "../../../vendor/ocpp-schemas/v21/SetVariablesResponse.json";
import signCertificateRequestV21Schema from "../../../vendor/ocpp-schemas/v21/SignCertificateRequest.json";
import signCertificateResponseV21Schema from "../../../vendor/ocpp-schemas/v21/SignCertificateResponse.json";
import statusNotificationRequestV21Schema from "../../../vendor/ocpp-schemas/v21/StatusNotificationRequest.json";
import statusNotificationResponseV21Schema from "../../../vendor/ocpp-schemas/v21/StatusNotificationResponse.json";
import transactionEventRequestV21Schema from "../../../vendor/ocpp-schemas/v21/TransactionEventRequest.json";
import transactionEventResponseV21Schema from "../../../vendor/ocpp-schemas/v21/TransactionEventResponse.json";
import triggerMessageRequestV21Schema from "../../../vendor/ocpp-schemas/v21/TriggerMessageRequest.json";
import triggerMessageResponseV21Schema from "../../../vendor/ocpp-schemas/v21/TriggerMessageResponse.json";
import unlockConnectorRequestV21Schema from "../../../vendor/ocpp-schemas/v21/UnlockConnectorRequest.json";
import unlockConnectorResponseV21Schema from "../../../vendor/ocpp-schemas/v21/UnlockConnectorResponse.json";
import unpublishFirmwareRequestV21Schema from "../../../vendor/ocpp-schemas/v21/UnpublishFirmwareRequest.json";
import unpublishFirmwareResponseV21Schema from "../../../vendor/ocpp-schemas/v21/UnpublishFirmwareResponse.json";
import updateDynamicScheduleRequestV21Schema from "../../../vendor/ocpp-schemas/v21/UpdateDynamicScheduleRequest.json";
import updateDynamicScheduleResponseV21Schema from "../../../vendor/ocpp-schemas/v21/UpdateDynamicScheduleResponse.json";
import updateFirmwareRequestV21Schema from "../../../vendor/ocpp-schemas/v21/UpdateFirmwareRequest.json";
import updateFirmwareResponseV21Schema from "../../../vendor/ocpp-schemas/v21/UpdateFirmwareResponse.json";
import usePriorityChargingRequestV21Schema from "../../../vendor/ocpp-schemas/v21/UsePriorityChargingRequest.json";
import usePriorityChargingResponseV21Schema from "../../../vendor/ocpp-schemas/v21/UsePriorityChargingResponse.json";
import vatNumberValidationRequestV21Schema from "../../../vendor/ocpp-schemas/v21/VatNumberValidationRequest.json";
import vatNumberValidationResponseV21Schema from "../../../vendor/ocpp-schemas/v21/VatNumberValidationResponse.json";

export const v21Schemas: Record<string, object> = {
  adjustPeriodicEventStreamRequestV21:
    adjustPeriodicEventStreamRequestV21Schema,
  adjustPeriodicEventStreamResponseV21:
    adjustPeriodicEventStreamResponseV21Schema,
  aFRRSignalRequestV21: aFRRSignalRequestV21Schema,
  aFRRSignalResponseV21: aFRRSignalResponseV21Schema,
  authorizeRequestV21: authorizeRequestV21Schema,
  authorizeResponseV21: authorizeResponseV21Schema,
  batterySwapRequestV21: batterySwapRequestV21Schema,
  batterySwapResponseV21: batterySwapResponseV21Schema,
  bootNotificationRequestV21: bootNotificationRequestV21Schema,
  bootNotificationResponseV21: bootNotificationResponseV21Schema,
  cancelReservationRequestV21: cancelReservationRequestV21Schema,
  cancelReservationResponseV21: cancelReservationResponseV21Schema,
  certificateSignedRequestV21: certificateSignedRequestV21Schema,
  certificateSignedResponseV21: certificateSignedResponseV21Schema,
  changeAvailabilityRequestV21: changeAvailabilityRequestV21Schema,
  changeAvailabilityResponseV21: changeAvailabilityResponseV21Schema,
  changeTransactionTariffRequestV21: changeTransactionTariffRequestV21Schema,
  changeTransactionTariffResponseV21: changeTransactionTariffResponseV21Schema,
  clearCacheRequestV21: clearCacheRequestV21Schema,
  clearCacheResponseV21: clearCacheResponseV21Schema,
  clearChargingProfileRequestV21: clearChargingProfileRequestV21Schema,
  clearChargingProfileResponseV21: clearChargingProfileResponseV21Schema,
  clearDERControlRequestV21: clearDERControlRequestV21Schema,
  clearDERControlResponseV21: clearDERControlResponseV21Schema,
  clearDisplayMessageRequestV21: clearDisplayMessageRequestV21Schema,
  clearDisplayMessageResponseV21: clearDisplayMessageResponseV21Schema,
  clearedChargingLimitRequestV21: clearedChargingLimitRequestV21Schema,
  clearedChargingLimitResponseV21: clearedChargingLimitResponseV21Schema,
  clearTariffsRequestV21: clearTariffsRequestV21Schema,
  clearTariffsResponseV21: clearTariffsResponseV21Schema,
  clearVariableMonitoringRequestV21: clearVariableMonitoringRequestV21Schema,
  clearVariableMonitoringResponseV21: clearVariableMonitoringResponseV21Schema,
  closePeriodicEventStreamRequestV21: closePeriodicEventStreamRequestV21Schema,
  closePeriodicEventStreamResponseV21:
    closePeriodicEventStreamResponseV21Schema,
  costUpdatedRequestV21: costUpdatedRequestV21Schema,
  costUpdatedResponseV21: costUpdatedResponseV21Schema,
  customerInformationRequestV21: customerInformationRequestV21Schema,
  customerInformationResponseV21: customerInformationResponseV21Schema,
  dataTransferRequestV21: dataTransferRequestV21Schema,
  dataTransferResponseV21: dataTransferResponseV21Schema,
  deleteCertificateRequestV21: deleteCertificateRequestV21Schema,
  deleteCertificateResponseV21: deleteCertificateResponseV21Schema,
  firmwareStatusNotificationRequestV21:
    firmwareStatusNotificationRequestV21Schema,
  firmwareStatusNotificationResponseV21:
    firmwareStatusNotificationResponseV21Schema,
  get15118EVCertificateRequestV21: get15118EVCertificateRequestV21Schema,
  get15118EVCertificateResponseV21: get15118EVCertificateResponseV21Schema,
  getBaseReportRequestV21: getBaseReportRequestV21Schema,
  getBaseReportResponseV21: getBaseReportResponseV21Schema,
  getCertificateChainStatusRequestV21:
    getCertificateChainStatusRequestV21Schema,
  getCertificateChainStatusResponseV21:
    getCertificateChainStatusResponseV21Schema,
  getCertificateStatusRequestV21: getCertificateStatusRequestV21Schema,
  getCertificateStatusResponseV21: getCertificateStatusResponseV21Schema,
  getChargingProfilesRequestV21: getChargingProfilesRequestV21Schema,
  getChargingProfilesResponseV21: getChargingProfilesResponseV21Schema,
  getCompositeScheduleRequestV21: getCompositeScheduleRequestV21Schema,
  getCompositeScheduleResponseV21: getCompositeScheduleResponseV21Schema,
  getDERControlRequestV21: getDERControlRequestV21Schema,
  getDERControlResponseV21: getDERControlResponseV21Schema,
  getDisplayMessagesRequestV21: getDisplayMessagesRequestV21Schema,
  getDisplayMessagesResponseV21: getDisplayMessagesResponseV21Schema,
  getInstalledCertificateIdsRequestV21:
    getInstalledCertificateIdsRequestV21Schema,
  getInstalledCertificateIdsResponseV21:
    getInstalledCertificateIdsResponseV21Schema,
  getLocalListVersionRequestV21: getLocalListVersionRequestV21Schema,
  getLocalListVersionResponseV21: getLocalListVersionResponseV21Schema,
  getLogRequestV21: getLogRequestV21Schema,
  getLogResponseV21: getLogResponseV21Schema,
  getMonitoringReportRequestV21: getMonitoringReportRequestV21Schema,
  getMonitoringReportResponseV21: getMonitoringReportResponseV21Schema,
  getPeriodicEventStreamRequestV21: getPeriodicEventStreamRequestV21Schema,
  getPeriodicEventStreamResponseV21: getPeriodicEventStreamResponseV21Schema,
  getReportRequestV21: getReportRequestV21Schema,
  getReportResponseV21: getReportResponseV21Schema,
  getTariffsRequestV21: getTariffsRequestV21Schema,
  getTariffsResponseV21: getTariffsResponseV21Schema,
  getTransactionStatusRequestV21: getTransactionStatusRequestV21Schema,
  getTransactionStatusResponseV21: getTransactionStatusResponseV21Schema,
  getVariablesRequestV21: getVariablesRequestV21Schema,
  getVariablesResponseV21: getVariablesResponseV21Schema,
  heartbeatRequestV21: heartbeatRequestV21Schema,
  heartbeatResponseV21: heartbeatResponseV21Schema,
  installCertificateRequestV21: installCertificateRequestV21Schema,
  installCertificateResponseV21: installCertificateResponseV21Schema,
  logStatusNotificationRequestV21: logStatusNotificationRequestV21Schema,
  logStatusNotificationResponseV21: logStatusNotificationResponseV21Schema,
  meterValuesRequestV21: meterValuesRequestV21Schema,
  meterValuesResponseV21: meterValuesResponseV21Schema,
  notifyAllowedEnergyTransferRequestV21:
    notifyAllowedEnergyTransferRequestV21Schema,
  notifyAllowedEnergyTransferResponseV21:
    notifyAllowedEnergyTransferResponseV21Schema,
  notifyChargingLimitRequestV21: notifyChargingLimitRequestV21Schema,
  notifyChargingLimitResponseV21: notifyChargingLimitResponseV21Schema,
  notifyCustomerInformationRequestV21:
    notifyCustomerInformationRequestV21Schema,
  notifyCustomerInformationResponseV21:
    notifyCustomerInformationResponseV21Schema,
  notifyDERAlarmRequestV21: notifyDERAlarmRequestV21Schema,
  notifyDERAlarmResponseV21: notifyDERAlarmResponseV21Schema,
  notifyDERStartStopRequestV21: notifyDERStartStopRequestV21Schema,
  notifyDERStartStopResponseV21: notifyDERStartStopResponseV21Schema,
  notifyDisplayMessagesRequestV21: notifyDisplayMessagesRequestV21Schema,
  notifyDisplayMessagesResponseV21: notifyDisplayMessagesResponseV21Schema,
  notifyEVChargingNeedsRequestV21: notifyEVChargingNeedsRequestV21Schema,
  notifyEVChargingNeedsResponseV21: notifyEVChargingNeedsResponseV21Schema,
  notifyEVChargingScheduleRequestV21: notifyEVChargingScheduleRequestV21Schema,
  notifyEVChargingScheduleResponseV21:
    notifyEVChargingScheduleResponseV21Schema,
  notifyEventRequestV21: notifyEventRequestV21Schema,
  notifyEventResponseV21: notifyEventResponseV21Schema,
  notifyMonitoringReportRequestV21: notifyMonitoringReportRequestV21Schema,
  notifyMonitoringReportResponseV21: notifyMonitoringReportResponseV21Schema,
  notifyPeriodicEventStreamRequestV21:
    notifyPeriodicEventStreamRequestV21Schema,
  notifyPriorityChargingRequestV21: notifyPriorityChargingRequestV21Schema,
  notifyPriorityChargingResponseV21: notifyPriorityChargingResponseV21Schema,
  notifyReportRequestV21: notifyReportRequestV21Schema,
  notifyReportResponseV21: notifyReportResponseV21Schema,
  notifySettlementRequestV21: notifySettlementRequestV21Schema,
  notifySettlementResponseV21: notifySettlementResponseV21Schema,
  notifyWebPaymentStartedRequestV21: notifyWebPaymentStartedRequestV21Schema,
  notifyWebPaymentStartedResponseV21: notifyWebPaymentStartedResponseV21Schema,
  openPeriodicEventStreamRequestV21: openPeriodicEventStreamRequestV21Schema,
  openPeriodicEventStreamResponseV21: openPeriodicEventStreamResponseV21Schema,
  publishFirmwareRequestV21: publishFirmwareRequestV21Schema,
  publishFirmwareResponseV21: publishFirmwareResponseV21Schema,
  publishFirmwareStatusNotificationRequestV21:
    publishFirmwareStatusNotificationRequestV21Schema,
  publishFirmwareStatusNotificationResponseV21:
    publishFirmwareStatusNotificationResponseV21Schema,
  pullDynamicScheduleUpdateRequestV21:
    pullDynamicScheduleUpdateRequestV21Schema,
  pullDynamicScheduleUpdateResponseV21:
    pullDynamicScheduleUpdateResponseV21Schema,
  reportChargingProfilesRequestV21: reportChargingProfilesRequestV21Schema,
  reportChargingProfilesResponseV21: reportChargingProfilesResponseV21Schema,
  reportDERControlRequestV21: reportDERControlRequestV21Schema,
  reportDERControlResponseV21: reportDERControlResponseV21Schema,
  requestBatterySwapRequestV21: requestBatterySwapRequestV21Schema,
  requestBatterySwapResponseV21: requestBatterySwapResponseV21Schema,
  requestStartTransactionRequestV21: requestStartTransactionRequestV21Schema,
  requestStartTransactionResponseV21: requestStartTransactionResponseV21Schema,
  requestStopTransactionRequestV21: requestStopTransactionRequestV21Schema,
  requestStopTransactionResponseV21: requestStopTransactionResponseV21Schema,
  reservationStatusUpdateRequestV21: reservationStatusUpdateRequestV21Schema,
  reservationStatusUpdateResponseV21: reservationStatusUpdateResponseV21Schema,
  reserveNowRequestV21: reserveNowRequestV21Schema,
  reserveNowResponseV21: reserveNowResponseV21Schema,
  resetRequestV21: resetRequestV21Schema,
  resetResponseV21: resetResponseV21Schema,
  securityEventNotificationRequestV21:
    securityEventNotificationRequestV21Schema,
  securityEventNotificationResponseV21:
    securityEventNotificationResponseV21Schema,
  sendLocalListRequestV21: sendLocalListRequestV21Schema,
  sendLocalListResponseV21: sendLocalListResponseV21Schema,
  setChargingProfileRequestV21: setChargingProfileRequestV21Schema,
  setChargingProfileResponseV21: setChargingProfileResponseV21Schema,
  setDefaultTariffRequestV21: setDefaultTariffRequestV21Schema,
  setDefaultTariffResponseV21: setDefaultTariffResponseV21Schema,
  setDERControlRequestV21: setDERControlRequestV21Schema,
  setDERControlResponseV21: setDERControlResponseV21Schema,
  setDisplayMessageRequestV21: setDisplayMessageRequestV21Schema,
  setDisplayMessageResponseV21: setDisplayMessageResponseV21Schema,
  setMonitoringBaseRequestV21: setMonitoringBaseRequestV21Schema,
  setMonitoringBaseResponseV21: setMonitoringBaseResponseV21Schema,
  setMonitoringLevelRequestV21: setMonitoringLevelRequestV21Schema,
  setMonitoringLevelResponseV21: setMonitoringLevelResponseV21Schema,
  setNetworkProfileRequestV21: setNetworkProfileRequestV21Schema,
  setNetworkProfileResponseV21: setNetworkProfileResponseV21Schema,
  setVariableMonitoringRequestV21: setVariableMonitoringRequestV21Schema,
  setVariableMonitoringResponseV21: setVariableMonitoringResponseV21Schema,
  setVariablesRequestV21: setVariablesRequestV21Schema,
  setVariablesResponseV21: setVariablesResponseV21Schema,
  signCertificateRequestV21: signCertificateRequestV21Schema,
  signCertificateResponseV21: signCertificateResponseV21Schema,
  statusNotificationRequestV21: statusNotificationRequestV21Schema,
  statusNotificationResponseV21: statusNotificationResponseV21Schema,
  transactionEventRequestV21: transactionEventRequestV21Schema,
  transactionEventResponseV21: transactionEventResponseV21Schema,
  triggerMessageRequestV21: triggerMessageRequestV21Schema,
  triggerMessageResponseV21: triggerMessageResponseV21Schema,
  unlockConnectorRequestV21: unlockConnectorRequestV21Schema,
  unlockConnectorResponseV21: unlockConnectorResponseV21Schema,
  unpublishFirmwareRequestV21: unpublishFirmwareRequestV21Schema,
  unpublishFirmwareResponseV21: unpublishFirmwareResponseV21Schema,
  updateDynamicScheduleRequestV21: updateDynamicScheduleRequestV21Schema,
  updateDynamicScheduleResponseV21: updateDynamicScheduleResponseV21Schema,
  updateFirmwareRequestV21: updateFirmwareRequestV21Schema,
  updateFirmwareResponseV21: updateFirmwareResponseV21Schema,
  usePriorityChargingRequestV21: usePriorityChargingRequestV21Schema,
  usePriorityChargingResponseV21: usePriorityChargingResponseV21Schema,
  vatNumberValidationRequestV21: vatNumberValidationRequestV21Schema,
  vatNumberValidationResponseV21: vatNumberValidationResponseV21Schema,
};
