// Generated by scripts/generate-ocpp.ts. Do not edit.

import { validateOCPPPayload } from "../validate";
import { v21Schemas } from "./schemas";
import type { AdjustPeriodicEventStreamRequestV21 } from "./types/adjust-periodic-event-stream-request";
import type { AdjustPeriodicEventStreamResponseV21 } from "./types/adjust-periodic-event-stream-response";
import type { AFRRSignalRequestV21 } from "./types/afrr-signal-request";
import type { AFRRSignalResponseV21 } from "./types/afrr-signal-response";
import type { AuthorizeRequestV21 } from "./types/authorize-request";
import type { AuthorizeResponseV21 } from "./types/authorize-response";
import type { BatterySwapRequestV21 } from "./types/battery-swap-request";
import type { BatterySwapResponseV21 } from "./types/battery-swap-response";
import type { BootNotificationRequestV21 } from "./types/boot-notification-request";
import type { BootNotificationResponseV21 } from "./types/boot-notification-response";
import type { CancelReservationRequestV21 } from "./types/cancel-reservation-request";
import type { CancelReservationResponseV21 } from "./types/cancel-reservation-response";
import type { CertificateSignedRequestV21 } from "./types/certificate-signed-request";
import type { CertificateSignedResponseV21 } from "./types/certificate-signed-response";
import type { ChangeAvailabilityRequestV21 } from "./types/change-availability-request";
import type { ChangeAvailabilityResponseV21 } from "./types/change-availability-response";
import type { ChangeTransactionTariffRequestV21 } from "./types/change-transaction-tariff-request";
import type { ChangeTransactionTariffResponseV21 } from "./types/change-transaction-tariff-response";
import type { ClearCacheRequestV21 } from "./types/clear-cache-request";
import type { ClearCacheResponseV21 } from "./types/clear-cache-response";
import type { ClearChargingProfileRequestV21 } from "./types/clear-charging-profile-request";
import type { ClearChargingProfileResponseV21 } from "./types/clear-charging-profile-response";
import type { ClearDERControlRequestV21 } from "./types/clear-der-control-request";
import type { ClearDERControlResponseV21 } from "./types/clear-der-control-response";
import type { ClearDisplayMessageRequestV21 } from "./types/clear-display-message-request";
import type { ClearDisplayMessageResponseV21 } from "./types/clear-display-message-response";
import type { ClearedChargingLimitRequestV21 } from "./types/cleared-charging-limit-request";
import type { ClearedChargingLimitResponseV21 } from "./types/cleared-charging-limit-response";
import type { ClearTariffsRequestV21 } from "./types/clear-tariffs-request";
import type { ClearTariffsResponseV21 } from "./types/clear-tariffs-response";
import type { ClearVariableMonitoringRequestV21 } from "./types/clear-variable-monitoring-request";
import type { ClearVariableMonitoringResponseV21 } from "./types/clear-variable-monitoring-response";
import type { ClosePeriodicEventStreamRequestV21 } from "./types/close-periodic-event-stream-request";
import type { ClosePeriodicEventStreamResponseV21 } from "./types/close-periodic-event-stream-response";
import type { CostUpdatedRequestV21 } from "./types/cost-updated-request";
import type { CostUpdatedResponseV21 } from "./types/cost-updated-response";
import type { CustomerInformationRequestV21 } from "./types/customer-information-request";
import type { CustomerInformationResponseV21 } from "./types/customer-information-response";
import type { DataTransferRequestV21 } from "./types/data-transfer-request";
import type { DataTransferResponseV21 } from "./types/data-transfer-response";
import type { DeleteCertificateRequestV21 } from "./types/delete-certificate-request";
import type { DeleteCertificateResponseV21 } from "./types/delete-certificate-response";
import type { FirmwareStatusNotificationRequestV21 } from "./types/firmware-status-notification-request";
import type { FirmwareStatusNotificationResponseV21 } from "./types/firmware-status-notification-response";
import type { Get15118EVCertificateRequestV21 } from "./types/get15118-ev-certificate-request";
import type { Get15118EVCertificateResponseV21 } from "./types/get15118-ev-certificate-response";
import type { GetBaseReportRequestV21 } from "./types/get-base-report-request";
import type { GetBaseReportResponseV21 } from "./types/get-base-report-response";
import type { GetCertificateChainStatusRequestV21 } from "./types/get-certificate-chain-status-request";
import type { GetCertificateChainStatusResponseV21 } from "./types/get-certificate-chain-status-response";
import type { GetCertificateStatusRequestV21 } from "./types/get-certificate-status-request";
import type { GetCertificateStatusResponseV21 } from "./types/get-certificate-status-response";
import type { GetChargingProfilesRequestV21 } from "./types/get-charging-profiles-request";
import type { GetChargingProfilesResponseV21 } from "./types/get-charging-profiles-response";
import type { GetCompositeScheduleRequestV21 } from "./types/get-composite-schedule-request";
import type { GetCompositeScheduleResponseV21 } from "./types/get-composite-schedule-response";
import type { GetDERControlRequestV21 } from "./types/get-der-control-request";
import type { GetDERControlResponseV21 } from "./types/get-der-control-response";
import type { GetDisplayMessagesRequestV21 } from "./types/get-display-messages-request";
import type { GetDisplayMessagesResponseV21 } from "./types/get-display-messages-response";
import type { GetInstalledCertificateIdsRequestV21 } from "./types/get-installed-certificate-ids-request";
import type { GetInstalledCertificateIdsResponseV21 } from "./types/get-installed-certificate-ids-response";
import type { GetLocalListVersionRequestV21 } from "./types/get-local-list-version-request";
import type { GetLocalListVersionResponseV21 } from "./types/get-local-list-version-response";
import type { GetLogRequestV21 } from "./types/get-log-request";
import type { GetLogResponseV21 } from "./types/get-log-response";
import type { GetMonitoringReportRequestV21 } from "./types/get-monitoring-report-request";
import type { GetMonitoringReportResponseV21 } from "./types/get-monitoring-report-response";
import type { GetPeriodicEventStreamRequestV21 } from "./types/get-periodic-event-stream-request";
import type { GetPeriodicEventStreamResponseV21 } from "./types/get-periodic-event-stream-response";
import type { GetReportRequestV21 } from "./types/get-report-request";
import type { GetReportResponseV21 } from "./types/get-report-response";
import type { GetTariffsRequestV21 } from "./types/get-tariffs-request";
import type { GetTariffsResponseV21 } from "./types/get-tariffs-response";
import type { GetTransactionStatusRequestV21 } from "./types/get-transaction-status-request";
import type { GetTransactionStatusResponseV21 } from "./types/get-transaction-status-response";
import type { GetVariablesRequestV21 } from "./types/get-variables-request";
import type { GetVariablesResponseV21 } from "./types/get-variables-response";
import type { HeartbeatRequestV21 } from "./types/heartbeat-request";
import type { HeartbeatResponseV21 } from "./types/heartbeat-response";
import type { InstallCertificateRequestV21 } from "./types/install-certificate-request";
import type { InstallCertificateResponseV21 } from "./types/install-certificate-response";
import type { LogStatusNotificationRequestV21 } from "./types/log-status-notification-request";
import type { LogStatusNotificationResponseV21 } from "./types/log-status-notification-response";
import type { MeterValuesRequestV21 } from "./types/meter-values-request";
import type { MeterValuesResponseV21 } from "./types/meter-values-response";
import type { NotifyAllowedEnergyTransferRequestV21 } from "./types/notify-allowed-energy-transfer-request";
import type { NotifyAllowedEnergyTransferResponseV21 } from "./types/notify-allowed-energy-transfer-response";
import type { NotifyChargingLimitRequestV21 } from "./types/notify-charging-limit-request";
import type { NotifyChargingLimitResponseV21 } from "./types/notify-charging-limit-response";
import type { NotifyCustomerInformationRequestV21 } from "./types/notify-customer-information-request";
import type { NotifyCustomerInformationResponseV21 } from "./types/notify-customer-information-response";
import type { NotifyDERAlarmRequestV21 } from "./types/notify-der-alarm-request";
import type { NotifyDERAlarmResponseV21 } from "./types/notify-der-alarm-response";
import type { NotifyDERStartStopRequestV21 } from "./types/notify-der-start-stop-request";
import type { NotifyDERStartStopResponseV21 } from "./types/notify-der-start-stop-response";
import type { NotifyDisplayMessagesRequestV21 } from "./types/notify-display-messages-request";
import type { NotifyDisplayMessagesResponseV21 } from "./types/notify-display-messages-response";
import type { NotifyEVChargingNeedsRequestV21 } from "./types/notify-ev-charging-needs-request";
import type { NotifyEVChargingNeedsResponseV21 } from "./types/notify-ev-charging-needs-response";
import type { NotifyEVChargingScheduleRequestV21 } from "./types/notify-ev-charging-schedule-request";
import type { NotifyEVChargingScheduleResponseV21 } from "./types/notify-ev-charging-schedule-response";
import type { NotifyEventRequestV21 } from "./types/notify-event-request";
import type { NotifyEventResponseV21 } from "./types/notify-event-response";
import type { NotifyMonitoringReportRequestV21 } from "./types/notify-monitoring-report-request";
import type { NotifyMonitoringReportResponseV21 } from "./types/notify-monitoring-report-response";
import type { NotifyPeriodicEventStreamRequestV21 } from "./types/notify-periodic-event-stream-request";
import type { NotifyPriorityChargingRequestV21 } from "./types/notify-priority-charging-request";
import type { NotifyPriorityChargingResponseV21 } from "./types/notify-priority-charging-response";
import type { NotifyReportRequestV21 } from "./types/notify-report-request";
import type { NotifyReportResponseV21 } from "./types/notify-report-response";
import type { NotifySettlementRequestV21 } from "./types/notify-settlement-request";
import type { NotifySettlementResponseV21 } from "./types/notify-settlement-response";
import type { NotifyWebPaymentStartedRequestV21 } from "./types/notify-web-payment-started-request";
import type { NotifyWebPaymentStartedResponseV21 } from "./types/notify-web-payment-started-response";
import type { OpenPeriodicEventStreamRequestV21 } from "./types/open-periodic-event-stream-request";
import type { OpenPeriodicEventStreamResponseV21 } from "./types/open-periodic-event-stream-response";
import type { PublishFirmwareRequestV21 } from "./types/publish-firmware-request";
import type { PublishFirmwareResponseV21 } from "./types/publish-firmware-response";
import type { PublishFirmwareStatusNotificationRequestV21 } from "./types/publish-firmware-status-notification-request";
import type { PublishFirmwareStatusNotificationResponseV21 } from "./types/publish-firmware-status-notification-response";
import type { PullDynamicScheduleUpdateRequestV21 } from "./types/pull-dynamic-schedule-update-request";
import type { PullDynamicScheduleUpdateResponseV21 } from "./types/pull-dynamic-schedule-update-response";
import type { ReportChargingProfilesRequestV21 } from "./types/report-charging-profiles-request";
import type { ReportChargingProfilesResponseV21 } from "./types/report-charging-profiles-response";
import type { ReportDERControlRequestV21 } from "./types/report-der-control-request";
import type { ReportDERControlResponseV21 } from "./types/report-der-control-response";
import type { RequestBatterySwapRequestV21 } from "./types/request-battery-swap-request";
import type { RequestBatterySwapResponseV21 } from "./types/request-battery-swap-response";
import type { RequestStartTransactionRequestV21 } from "./types/request-start-transaction-request";
import type { RequestStartTransactionResponseV21 } from "./types/request-start-transaction-response";
import type { RequestStopTransactionRequestV21 } from "./types/request-stop-transaction-request";
import type { RequestStopTransactionResponseV21 } from "./types/request-stop-transaction-response";
import type { ReservationStatusUpdateRequestV21 } from "./types/reservation-status-update-request";
import type { ReservationStatusUpdateResponseV21 } from "./types/reservation-status-update-response";
import type { ReserveNowRequestV21 } from "./types/reserve-now-request";
import type { ReserveNowResponseV21 } from "./types/reserve-now-response";
import type { ResetRequestV21 } from "./types/reset-request";
import type { ResetResponseV21 } from "./types/reset-response";
import type { SecurityEventNotificationRequestV21 } from "./types/security-event-notification-request";
import type { SecurityEventNotificationResponseV21 } from "./types/security-event-notification-response";
import type { SendLocalListRequestV21 } from "./types/send-local-list-request";
import type { SendLocalListResponseV21 } from "./types/send-local-list-response";
import type { SetChargingProfileRequestV21 } from "./types/set-charging-profile-request";
import type { SetChargingProfileResponseV21 } from "./types/set-charging-profile-response";
import type { SetDefaultTariffRequestV21 } from "./types/set-default-tariff-request";
import type { SetDefaultTariffResponseV21 } from "./types/set-default-tariff-response";
import type { SetDERControlRequestV21 } from "./types/set-der-control-request";
import type { SetDERControlResponseV21 } from "./types/set-der-control-response";
import type { SetDisplayMessageRequestV21 } from "./types/set-display-message-request";
import type { SetDisplayMessageResponseV21 } from "./types/set-display-message-response";
import type { SetMonitoringBaseRequestV21 } from "./types/set-monitoring-base-request";
import type { SetMonitoringBaseResponseV21 } from "./types/set-monitoring-base-response";
import type { SetMonitoringLevelRequestV21 } from "./types/set-monitoring-level-request";
import type { SetMonitoringLevelResponseV21 } from "./types/set-monitoring-level-response";
import type { SetNetworkProfileRequestV21 } from "./types/set-network-profile-request";
import type { SetNetworkProfileResponseV21 } from "./types/set-network-profile-response";
import type { SetVariableMonitoringRequestV21 } from "./types/set-variable-monitoring-request";
import type { SetVariableMonitoringResponseV21 } from "./types/set-variable-monitoring-response";
import type { SetVariablesRequestV21 } from "./types/set-variables-request";
import type { SetVariablesResponseV21 } from "./types/set-variables-response";
import type { SignCertificateRequestV21 } from "./types/sign-certificate-request";
import type { SignCertificateResponseV21 } from "./types/sign-certificate-response";
import type { StatusNotificationRequestV21 } from "./types/status-notification-request";
import type { StatusNotificationResponseV21 } from "./types/status-notification-response";
import type { TransactionEventRequestV21 } from "./types/transaction-event-request";
import type { TransactionEventResponseV21 } from "./types/transaction-event-response";
import type { TriggerMessageRequestV21 } from "./types/trigger-message-request";
import type { TriggerMessageResponseV21 } from "./types/trigger-message-response";
import type { UnlockConnectorRequestV21 } from "./types/unlock-connector-request";
import type { UnlockConnectorResponseV21 } from "./types/unlock-connector-response";
import type { UnpublishFirmwareRequestV21 } from "./types/unpublish-firmware-request";
import type { UnpublishFirmwareResponseV21 } from "./types/unpublish-firmware-response";
import type { UpdateDynamicScheduleRequestV21 } from "./types/update-dynamic-schedule-request";
import type { UpdateDynamicScheduleResponseV21 } from "./types/update-dynamic-schedule-response";
import type { UpdateFirmwareRequestV21 } from "./types/update-firmware-request";
import type { UpdateFirmwareResponseV21 } from "./types/update-firmware-response";
import type { UsePriorityChargingRequestV21 } from "./types/use-priority-charging-request";
import type { UsePriorityChargingResponseV21 } from "./types/use-priority-charging-response";
import type { VatNumberValidationRequestV21 } from "./types/vat-number-validation-request";
import type { VatNumberValidationResponseV21 } from "./types/vat-number-validation-response";

export const isValidAdjustPeriodicEventStreamRequestV21 = (
  data: unknown,
): data is AdjustPeriodicEventStreamRequestV21 =>
  validateOCPPPayload(v21Schemas.adjustPeriodicEventStreamRequestV21, data);

export const isValidAdjustPeriodicEventStreamResponseV21 = (
  data: unknown,
): data is AdjustPeriodicEventStreamResponseV21 =>
  validateOCPPPayload(v21Schemas.adjustPeriodicEventStreamResponseV21, data);

export const isValidAFRRSignalRequestV21 = (
  data: unknown,
): data is AFRRSignalRequestV21 =>
  validateOCPPPayload(v21Schemas.aFRRSignalRequestV21, data);

export const isValidAFRRSignalResponseV21 = (
  data: unknown,
): data is AFRRSignalResponseV21 =>
  validateOCPPPayload(v21Schemas.aFRRSignalResponseV21, data);

export const isValidAuthorizeRequestV21 = (
  data: unknown,
): data is AuthorizeRequestV21 =>
  validateOCPPPayload(v21Schemas.authorizeRequestV21, data);

export const isValidAuthorizeResponseV21 = (
  data: unknown,
): data is AuthorizeResponseV21 =>
  validateOCPPPayload(v21Schemas.authorizeResponseV21, data);

export const isValidBatterySwapRequestV21 = (
  data: unknown,
): data is BatterySwapRequestV21 =>
  validateOCPPPayload(v21Schemas.batterySwapRequestV21, data);

export const isValidBatterySwapResponseV21 = (
  data: unknown,
): data is BatterySwapResponseV21 =>
  validateOCPPPayload(v21Schemas.batterySwapResponseV21, data);

export const isValidBootNotificationRequestV21 = (
  data: unknown,
): data is BootNotificationRequestV21 =>
  validateOCPPPayload(v21Schemas.bootNotificationRequestV21, data);

export const isValidBootNotificationResponseV21 = (
  data: unknown,
): data is BootNotificationResponseV21 =>
  validateOCPPPayload(v21Schemas.bootNotificationResponseV21, data);

export const isValidCancelReservationRequestV21 = (
  data: unknown,
): data is CancelReservationRequestV21 =>
  validateOCPPPayload(v21Schemas.cancelReservationRequestV21, data);

export const isValidCancelReservationResponseV21 = (
  data: unknown,
): data is CancelReservationResponseV21 =>
  validateOCPPPayload(v21Schemas.cancelReservationResponseV21, data);

export const isValidCertificateSignedRequestV21 = (
  data: unknown,
): data is CertificateSignedRequestV21 =>
  validateOCPPPayload(v21Schemas.certificateSignedRequestV21, data);

export const isValidCertificateSignedResponseV21 = (
  data: unknown,
): data is CertificateSignedResponseV21 =>
  validateOCPPPayload(v21Schemas.certificateSignedResponseV21, data);

export const isValidChangeAvailabilityRequestV21 = (
  data: unknown,
): data is ChangeAvailabilityRequestV21 =>
  validateOCPPPayload(v21Schemas.changeAvailabilityRequestV21, data);

export const isValidChangeAvailabilityResponseV21 = (
  data: unknown,
): data is ChangeAvailabilityResponseV21 =>
  validateOCPPPayload(v21Schemas.changeAvailabilityResponseV21, data);

export const isValidChangeTransactionTariffRequestV21 = (
  data: unknown,
): data is ChangeTransactionTariffRequestV21 =>
  validateOCPPPayload(v21Schemas.changeTransactionTariffRequestV21, data);

export const isValidChangeTransactionTariffResponseV21 = (
  data: unknown,
): data is ChangeTransactionTariffResponseV21 =>
  validateOCPPPayload(v21Schemas.changeTransactionTariffResponseV21, data);

export const isValidClearCacheRequestV21 = (
  data: unknown,
): data is ClearCacheRequestV21 =>
  validateOCPPPayload(v21Schemas.clearCacheRequestV21, data);

export const isValidClearCacheResponseV21 = (
  data: unknown,
): data is ClearCacheResponseV21 =>
  validateOCPPPayload(v21Schemas.clearCacheResponseV21, data);

export const isValidClearChargingProfileRequestV21 = (
  data: unknown,
): data is ClearChargingProfileRequestV21 =>
  validateOCPPPayload(v21Schemas.clearChargingProfileRequestV21, data);

export const isValidClearChargingProfileResponseV21 = (
  data: unknown,
): data is ClearChargingProfileResponseV21 =>
  validateOCPPPayload(v21Schemas.clearChargingProfileResponseV21, data);

export const isValidClearDERControlRequestV21 = (
  data: unknown,
): data is ClearDERControlRequestV21 =>
  validateOCPPPayload(v21Schemas.clearDERControlRequestV21, data);

export const isValidClearDERControlResponseV21 = (
  data: unknown,
): data is ClearDERControlResponseV21 =>
  validateOCPPPayload(v21Schemas.clearDERControlResponseV21, data);

export const isValidClearDisplayMessageRequestV21 = (
  data: unknown,
): data is ClearDisplayMessageRequestV21 =>
  validateOCPPPayload(v21Schemas.clearDisplayMessageRequestV21, data);

export const isValidClearDisplayMessageResponseV21 = (
  data: unknown,
): data is ClearDisplayMessageResponseV21 =>
  validateOCPPPayload(v21Schemas.clearDisplayMessageResponseV21, data);

export const isValidClearedChargingLimitRequestV21 = (
  data: unknown,
): data is ClearedChargingLimitRequestV21 =>
  validateOCPPPayload(v21Schemas.clearedChargingLimitRequestV21, data);

export const isValidClearedChargingLimitResponseV21 = (
  data: unknown,
): data is ClearedChargingLimitResponseV21 =>
  validateOCPPPayload(v21Schemas.clearedChargingLimitResponseV21, data);

export const isValidClearTariffsRequestV21 = (
  data: unknown,
): data is ClearTariffsRequestV21 =>
  validateOCPPPayload(v21Schemas.clearTariffsRequestV21, data);

export const isValidClearTariffsResponseV21 = (
  data: unknown,
): data is ClearTariffsResponseV21 =>
  validateOCPPPayload(v21Schemas.clearTariffsResponseV21, data);

export const isValidClearVariableMonitoringRequestV21 = (
  data: unknown,
): data is ClearVariableMonitoringRequestV21 =>
  validateOCPPPayload(v21Schemas.clearVariableMonitoringRequestV21, data);

export const isValidClearVariableMonitoringResponseV21 = (
  data: unknown,
): data is ClearVariableMonitoringResponseV21 =>
  validateOCPPPayload(v21Schemas.clearVariableMonitoringResponseV21, data);

export const isValidClosePeriodicEventStreamRequestV21 = (
  data: unknown,
): data is ClosePeriodicEventStreamRequestV21 =>
  validateOCPPPayload(v21Schemas.closePeriodicEventStreamRequestV21, data);

export const isValidClosePeriodicEventStreamResponseV21 = (
  data: unknown,
): data is ClosePeriodicEventStreamResponseV21 =>
  validateOCPPPayload(v21Schemas.closePeriodicEventStreamResponseV21, data);

export const isValidCostUpdatedRequestV21 = (
  data: unknown,
): data is CostUpdatedRequestV21 =>
  validateOCPPPayload(v21Schemas.costUpdatedRequestV21, data);

export const isValidCostUpdatedResponseV21 = (
  data: unknown,
): data is CostUpdatedResponseV21 =>
  validateOCPPPayload(v21Schemas.costUpdatedResponseV21, data);

export const isValidCustomerInformationRequestV21 = (
  data: unknown,
): data is CustomerInformationRequestV21 =>
  validateOCPPPayload(v21Schemas.customerInformationRequestV21, data);

export const isValidCustomerInformationResponseV21 = (
  data: unknown,
): data is CustomerInformationResponseV21 =>
  validateOCPPPayload(v21Schemas.customerInformationResponseV21, data);

export const isValidDataTransferRequestV21 = (
  data: unknown,
): data is DataTransferRequestV21 =>
  validateOCPPPayload(v21Schemas.dataTransferRequestV21, data);

export const isValidDataTransferResponseV21 = (
  data: unknown,
): data is DataTransferResponseV21 =>
  validateOCPPPayload(v21Schemas.dataTransferResponseV21, data);

export const isValidDeleteCertificateRequestV21 = (
  data: unknown,
): data is DeleteCertificateRequestV21 =>
  validateOCPPPayload(v21Schemas.deleteCertificateRequestV21, data);

export const isValidDeleteCertificateResponseV21 = (
  data: unknown,
): data is DeleteCertificateResponseV21 =>
  validateOCPPPayload(v21Schemas.deleteCertificateResponseV21, data);

export const isValidFirmwareStatusNotificationRequestV21 = (
  data: unknown,
): data is FirmwareStatusNotificationRequestV21 =>
  validateOCPPPayload(v21Schemas.firmwareStatusNotificationRequestV21, data);

export const isValidFirmwareStatusNotificationResponseV21 = (
  data: unknown,
): data is FirmwareStatusNotificationResponseV21 =>
  validateOCPPPayload(v21Schemas.firmwareStatusNotificationResponseV21, data);

export const isValidGet15118EVCertificateRequestV21 = (
  data: unknown,
): data is Get15118EVCertificateRequestV21 =>
  validateOCPPPayload(v21Schemas.get15118EVCertificateRequestV21, data);

export const isValidGet15118EVCertificateResponseV21 = (
  data: unknown,
): data is Get15118EVCertificateResponseV21 =>
  validateOCPPPayload(v21Schemas.get15118EVCertificateResponseV21, data);

export const isValidGetBaseReportRequestV21 = (
  data: unknown,
): data is GetBaseReportRequestV21 =>
  validateOCPPPayload(v21Schemas.getBaseReportRequestV21, data);

export const isValidGetBaseReportResponseV21 = (
  data: unknown,
): data is GetBaseReportResponseV21 =>
  validateOCPPPayload(v21Schemas.getBaseReportResponseV21, data);

export const isValidGetCertificateChainStatusRequestV21 = (
  data: unknown,
): data is GetCertificateChainStatusRequestV21 =>
  validateOCPPPayload(v21Schemas.getCertificateChainStatusRequestV21, data);

export const isValidGetCertificateChainStatusResponseV21 = (
  data: unknown,
): data is GetCertificateChainStatusResponseV21 =>
  validateOCPPPayload(v21Schemas.getCertificateChainStatusResponseV21, data);

export const isValidGetCertificateStatusRequestV21 = (
  data: unknown,
): data is GetCertificateStatusRequestV21 =>
  validateOCPPPayload(v21Schemas.getCertificateStatusRequestV21, data);

export const isValidGetCertificateStatusResponseV21 = (
  data: unknown,
): data is GetCertificateStatusResponseV21 =>
  validateOCPPPayload(v21Schemas.getCertificateStatusResponseV21, data);

export const isValidGetChargingProfilesRequestV21 = (
  data: unknown,
): data is GetChargingProfilesRequestV21 =>
  validateOCPPPayload(v21Schemas.getChargingProfilesRequestV21, data);

export const isValidGetChargingProfilesResponseV21 = (
  data: unknown,
): data is GetChargingProfilesResponseV21 =>
  validateOCPPPayload(v21Schemas.getChargingProfilesResponseV21, data);

export const isValidGetCompositeScheduleRequestV21 = (
  data: unknown,
): data is GetCompositeScheduleRequestV21 =>
  validateOCPPPayload(v21Schemas.getCompositeScheduleRequestV21, data);

export const isValidGetCompositeScheduleResponseV21 = (
  data: unknown,
): data is GetCompositeScheduleResponseV21 =>
  validateOCPPPayload(v21Schemas.getCompositeScheduleResponseV21, data);

export const isValidGetDERControlRequestV21 = (
  data: unknown,
): data is GetDERControlRequestV21 =>
  validateOCPPPayload(v21Schemas.getDERControlRequestV21, data);

export const isValidGetDERControlResponseV21 = (
  data: unknown,
): data is GetDERControlResponseV21 =>
  validateOCPPPayload(v21Schemas.getDERControlResponseV21, data);

export const isValidGetDisplayMessagesRequestV21 = (
  data: unknown,
): data is GetDisplayMessagesRequestV21 =>
  validateOCPPPayload(v21Schemas.getDisplayMessagesRequestV21, data);

export const isValidGetDisplayMessagesResponseV21 = (
  data: unknown,
): data is GetDisplayMessagesResponseV21 =>
  validateOCPPPayload(v21Schemas.getDisplayMessagesResponseV21, data);

export const isValidGetInstalledCertificateIdsRequestV21 = (
  data: unknown,
): data is GetInstalledCertificateIdsRequestV21 =>
  validateOCPPPayload(v21Schemas.getInstalledCertificateIdsRequestV21, data);

export const isValidGetInstalledCertificateIdsResponseV21 = (
  data: unknown,
): data is GetInstalledCertificateIdsResponseV21 =>
  validateOCPPPayload(v21Schemas.getInstalledCertificateIdsResponseV21, data);

export const isValidGetLocalListVersionRequestV21 = (
  data: unknown,
): data is GetLocalListVersionRequestV21 =>
  validateOCPPPayload(v21Schemas.getLocalListVersionRequestV21, data);

export const isValidGetLocalListVersionResponseV21 = (
  data: unknown,
): data is GetLocalListVersionResponseV21 =>
  validateOCPPPayload(v21Schemas.getLocalListVersionResponseV21, data);

export const isValidGetLogRequestV21 = (
  data: unknown,
): data is GetLogRequestV21 =>
  validateOCPPPayload(v21Schemas.getLogRequestV21, data);

export const isValidGetLogResponseV21 = (
  data: unknown,
): data is GetLogResponseV21 =>
  validateOCPPPayload(v21Schemas.getLogResponseV21, data);

export const isValidGetMonitoringReportRequestV21 = (
  data: unknown,
): data is GetMonitoringReportRequestV21 =>
  validateOCPPPayload(v21Schemas.getMonitoringReportRequestV21, data);

export const isValidGetMonitoringReportResponseV21 = (
  data: unknown,
): data is GetMonitoringReportResponseV21 =>
  validateOCPPPayload(v21Schemas.getMonitoringReportResponseV21, data);

export const isValidGetPeriodicEventStreamRequestV21 = (
  data: unknown,
): data is GetPeriodicEventStreamRequestV21 =>
  validateOCPPPayload(v21Schemas.getPeriodicEventStreamRequestV21, data);

export const isValidGetPeriodicEventStreamResponseV21 = (
  data: unknown,
): data is GetPeriodicEventStreamResponseV21 =>
  validateOCPPPayload(v21Schemas.getPeriodicEventStreamResponseV21, data);

export const isValidGetReportRequestV21 = (
  data: unknown,
): data is GetReportRequestV21 =>
  validateOCPPPayload(v21Schemas.getReportRequestV21, data);

export const isValidGetReportResponseV21 = (
  data: unknown,
): data is GetReportResponseV21 =>
  validateOCPPPayload(v21Schemas.getReportResponseV21, data);

export const isValidGetTariffsRequestV21 = (
  data: unknown,
): data is GetTariffsRequestV21 =>
  validateOCPPPayload(v21Schemas.getTariffsRequestV21, data);

export const isValidGetTariffsResponseV21 = (
  data: unknown,
): data is GetTariffsResponseV21 =>
  validateOCPPPayload(v21Schemas.getTariffsResponseV21, data);

export const isValidGetTransactionStatusRequestV21 = (
  data: unknown,
): data is GetTransactionStatusRequestV21 =>
  validateOCPPPayload(v21Schemas.getTransactionStatusRequestV21, data);

export const isValidGetTransactionStatusResponseV21 = (
  data: unknown,
): data is GetTransactionStatusResponseV21 =>
  validateOCPPPayload(v21Schemas.getTransactionStatusResponseV21, data);

export const isValidGetVariablesRequestV21 = (
  data: unknown,
): data is GetVariablesRequestV21 =>
  validateOCPPPayload(v21Schemas.getVariablesRequestV21, data);

export const isValidGetVariablesResponseV21 = (
  data: unknown,
): data is GetVariablesResponseV21 =>
  validateOCPPPayload(v21Schemas.getVariablesResponseV21, data);

export const isValidHeartbeatRequestV21 = (
  data: unknown,
): data is HeartbeatRequestV21 =>
  validateOCPPPayload(v21Schemas.heartbeatRequestV21, data);

export const isValidHeartbeatResponseV21 = (
  data: unknown,
): data is HeartbeatResponseV21 =>
  validateOCPPPayload(v21Schemas.heartbeatResponseV21, data);

export const isValidInstallCertificateRequestV21 = (
  data: unknown,
): data is InstallCertificateRequestV21 =>
  validateOCPPPayload(v21Schemas.installCertificateRequestV21, data);

export const isValidInstallCertificateResponseV21 = (
  data: unknown,
): data is InstallCertificateResponseV21 =>
  validateOCPPPayload(v21Schemas.installCertificateResponseV21, data);

export const isValidLogStatusNotificationRequestV21 = (
  data: unknown,
): data is LogStatusNotificationRequestV21 =>
  validateOCPPPayload(v21Schemas.logStatusNotificationRequestV21, data);

export const isValidLogStatusNotificationResponseV21 = (
  data: unknown,
): data is LogStatusNotificationResponseV21 =>
  validateOCPPPayload(v21Schemas.logStatusNotificationResponseV21, data);

export const isValidMeterValuesRequestV21 = (
  data: unknown,
): data is MeterValuesRequestV21 =>
  validateOCPPPayload(v21Schemas.meterValuesRequestV21, data);

export const isValidMeterValuesResponseV21 = (
  data: unknown,
): data is MeterValuesResponseV21 =>
  validateOCPPPayload(v21Schemas.meterValuesResponseV21, data);

export const isValidNotifyAllowedEnergyTransferRequestV21 = (
  data: unknown,
): data is NotifyAllowedEnergyTransferRequestV21 =>
  validateOCPPPayload(v21Schemas.notifyAllowedEnergyTransferRequestV21, data);

export const isValidNotifyAllowedEnergyTransferResponseV21 = (
  data: unknown,
): data is NotifyAllowedEnergyTransferResponseV21 =>
  validateOCPPPayload(v21Schemas.notifyAllowedEnergyTransferResponseV21, data);

export const isValidNotifyChargingLimitRequestV21 = (
  data: unknown,
): data is NotifyChargingLimitRequestV21 =>
  validateOCPPPayload(v21Schemas.notifyChargingLimitRequestV21, data);

export const isValidNotifyChargingLimitResponseV21 = (
  data: unknown,
): data is NotifyChargingLimitResponseV21 =>
  validateOCPPPayload(v21Schemas.notifyChargingLimitResponseV21, data);

export const isValidNotifyCustomerInformationRequestV21 = (
  data: unknown,
): data is NotifyCustomerInformationRequestV21 =>
  validateOCPPPayload(v21Schemas.notifyCustomerInformationRequestV21, data);

export const isValidNotifyCustomerInformationResponseV21 = (
  data: unknown,
): data is NotifyCustomerInformationResponseV21 =>
  validateOCPPPayload(v21Schemas.notifyCustomerInformationResponseV21, data);

export const isValidNotifyDERAlarmRequestV21 = (
  data: unknown,
): data is NotifyDERAlarmRequestV21 =>
  validateOCPPPayload(v21Schemas.notifyDERAlarmRequestV21, data);

export const isValidNotifyDERAlarmResponseV21 = (
  data: unknown,
): data is NotifyDERAlarmResponseV21 =>
  validateOCPPPayload(v21Schemas.notifyDERAlarmResponseV21, data);

export const isValidNotifyDERStartStopRequestV21 = (
  data: unknown,
): data is NotifyDERStartStopRequestV21 =>
  validateOCPPPayload(v21Schemas.notifyDERStartStopRequestV21, data);

export const isValidNotifyDERStartStopResponseV21 = (
  data: unknown,
): data is NotifyDERStartStopResponseV21 =>
  validateOCPPPayload(v21Schemas.notifyDERStartStopResponseV21, data);

export const isValidNotifyDisplayMessagesRequestV21 = (
  data: unknown,
): data is NotifyDisplayMessagesRequestV21 =>
  validateOCPPPayload(v21Schemas.notifyDisplayMessagesRequestV21, data);

export const isValidNotifyDisplayMessagesResponseV21 = (
  data: unknown,
): data is NotifyDisplayMessagesResponseV21 =>
  validateOCPPPayload(v21Schemas.notifyDisplayMessagesResponseV21, data);

export const isValidNotifyEVChargingNeedsRequestV21 = (
  data: unknown,
): data is NotifyEVChargingNeedsRequestV21 =>
  validateOCPPPayload(v21Schemas.notifyEVChargingNeedsRequestV21, data);

export const isValidNotifyEVChargingNeedsResponseV21 = (
  data: unknown,
): data is NotifyEVChargingNeedsResponseV21 =>
  validateOCPPPayload(v21Schemas.notifyEVChargingNeedsResponseV21, data);

export const isValidNotifyEVChargingScheduleRequestV21 = (
  data: unknown,
): data is NotifyEVChargingScheduleRequestV21 =>
  validateOCPPPayload(v21Schemas.notifyEVChargingScheduleRequestV21, data);

export const isValidNotifyEVChargingScheduleResponseV21 = (
  data: unknown,
): data is NotifyEVChargingScheduleResponseV21 =>
  validateOCPPPayload(v21Schemas.notifyEVChargingScheduleResponseV21, data);

export const isValidNotifyEventRequestV21 = (
  data: unknown,
): data is NotifyEventRequestV21 =>
  validateOCPPPayload(v21Schemas.notifyEventRequestV21, data);

export const isValidNotifyEventResponseV21 = (
  data: unknown,
): data is NotifyEventResponseV21 =>
  validateOCPPPayload(v21Schemas.notifyEventResponseV21, data);

export const isValidNotifyMonitoringReportRequestV21 = (
  data: unknown,
): data is NotifyMonitoringReportRequestV21 =>
  validateOCPPPayload(v21Schemas.notifyMonitoringReportRequestV21, data);

export const isValidNotifyMonitoringReportResponseV21 = (
  data: unknown,
): data is NotifyMonitoringReportResponseV21 =>
  validateOCPPPayload(v21Schemas.notifyMonitoringReportResponseV21, data);

export const isValidNotifyPeriodicEventStreamRequestV21 = (
  data: unknown,
): data is NotifyPeriodicEventStreamRequestV21 =>
  validateOCPPPayload(v21Schemas.notifyPeriodicEventStreamRequestV21, data);

export const isValidNotifyPriorityChargingRequestV21 = (
  data: unknown,
): data is NotifyPriorityChargingRequestV21 =>
  validateOCPPPayload(v21Schemas.notifyPriorityChargingRequestV21, data);

export const isValidNotifyPriorityChargingResponseV21 = (
  data: unknown,
): data is NotifyPriorityChargingResponseV21 =>
  validateOCPPPayload(v21Schemas.notifyPriorityChargingResponseV21, data);

export const isValidNotifyReportRequestV21 = (
  data: unknown,
): data is NotifyReportRequestV21 =>
  validateOCPPPayload(v21Schemas.notifyReportRequestV21, data);

export const isValidNotifyReportResponseV21 = (
  data: unknown,
): data is NotifyReportResponseV21 =>
  validateOCPPPayload(v21Schemas.notifyReportResponseV21, data);

export const isValidNotifySettlementRequestV21 = (
  data: unknown,
): data is NotifySettlementRequestV21 =>
  validateOCPPPayload(v21Schemas.notifySettlementRequestV21, data);

export const isValidNotifySettlementResponseV21 = (
  data: unknown,
): data is NotifySettlementResponseV21 =>
  validateOCPPPayload(v21Schemas.notifySettlementResponseV21, data);

export const isValidNotifyWebPaymentStartedRequestV21 = (
  data: unknown,
): data is NotifyWebPaymentStartedRequestV21 =>
  validateOCPPPayload(v21Schemas.notifyWebPaymentStartedRequestV21, data);

export const isValidNotifyWebPaymentStartedResponseV21 = (
  data: unknown,
): data is NotifyWebPaymentStartedResponseV21 =>
  validateOCPPPayload(v21Schemas.notifyWebPaymentStartedResponseV21, data);

export const isValidOpenPeriodicEventStreamRequestV21 = (
  data: unknown,
): data is OpenPeriodicEventStreamRequestV21 =>
  validateOCPPPayload(v21Schemas.openPeriodicEventStreamRequestV21, data);

export const isValidOpenPeriodicEventStreamResponseV21 = (
  data: unknown,
): data is OpenPeriodicEventStreamResponseV21 =>
  validateOCPPPayload(v21Schemas.openPeriodicEventStreamResponseV21, data);

export const isValidPublishFirmwareRequestV21 = (
  data: unknown,
): data is PublishFirmwareRequestV21 =>
  validateOCPPPayload(v21Schemas.publishFirmwareRequestV21, data);

export const isValidPublishFirmwareResponseV21 = (
  data: unknown,
): data is PublishFirmwareResponseV21 =>
  validateOCPPPayload(v21Schemas.publishFirmwareResponseV21, data);

export const isValidPublishFirmwareStatusNotificationRequestV21 = (
  data: unknown,
): data is PublishFirmwareStatusNotificationRequestV21 =>
  validateOCPPPayload(
    v21Schemas.publishFirmwareStatusNotificationRequestV21,
    data,
  );

export const isValidPublishFirmwareStatusNotificationResponseV21 = (
  data: unknown,
): data is PublishFirmwareStatusNotificationResponseV21 =>
  validateOCPPPayload(
    v21Schemas.publishFirmwareStatusNotificationResponseV21,
    data,
  );

export const isValidPullDynamicScheduleUpdateRequestV21 = (
  data: unknown,
): data is PullDynamicScheduleUpdateRequestV21 =>
  validateOCPPPayload(v21Schemas.pullDynamicScheduleUpdateRequestV21, data);

export const isValidPullDynamicScheduleUpdateResponseV21 = (
  data: unknown,
): data is PullDynamicScheduleUpdateResponseV21 =>
  validateOCPPPayload(v21Schemas.pullDynamicScheduleUpdateResponseV21, data);

export const isValidReportChargingProfilesRequestV21 = (
  data: unknown,
): data is ReportChargingProfilesRequestV21 =>
  validateOCPPPayload(v21Schemas.reportChargingProfilesRequestV21, data);

export const isValidReportChargingProfilesResponseV21 = (
  data: unknown,
): data is ReportChargingProfilesResponseV21 =>
  validateOCPPPayload(v21Schemas.reportChargingProfilesResponseV21, data);

export const isValidReportDERControlRequestV21 = (
  data: unknown,
): data is ReportDERControlRequestV21 =>
  validateOCPPPayload(v21Schemas.reportDERControlRequestV21, data);

export const isValidReportDERControlResponseV21 = (
  data: unknown,
): data is ReportDERControlResponseV21 =>
  validateOCPPPayload(v21Schemas.reportDERControlResponseV21, data);

export const isValidRequestBatterySwapRequestV21 = (
  data: unknown,
): data is RequestBatterySwapRequestV21 =>
  validateOCPPPayload(v21Schemas.requestBatterySwapRequestV21, data);

export const isValidRequestBatterySwapResponseV21 = (
  data: unknown,
): data is RequestBatterySwapResponseV21 =>
  validateOCPPPayload(v21Schemas.requestBatterySwapResponseV21, data);

export const isValidRequestStartTransactionRequestV21 = (
  data: unknown,
): data is RequestStartTransactionRequestV21 =>
  validateOCPPPayload(v21Schemas.requestStartTransactionRequestV21, data);

export const isValidRequestStartTransactionResponseV21 = (
  data: unknown,
): data is RequestStartTransactionResponseV21 =>
  validateOCPPPayload(v21Schemas.requestStartTransactionResponseV21, data);

export const isValidRequestStopTransactionRequestV21 = (
  data: unknown,
): data is RequestStopTransactionRequestV21 =>
  validateOCPPPayload(v21Schemas.requestStopTransactionRequestV21, data);

export const isValidRequestStopTransactionResponseV21 = (
  data: unknown,
): data is RequestStopTransactionResponseV21 =>
  validateOCPPPayload(v21Schemas.requestStopTransactionResponseV21, data);

export const isValidReservationStatusUpdateRequestV21 = (
  data: unknown,
): data is ReservationStatusUpdateRequestV21 =>
  validateOCPPPayload(v21Schemas.reservationStatusUpdateRequestV21, data);

export const isValidReservationStatusUpdateResponseV21 = (
  data: unknown,
): data is ReservationStatusUpdateResponseV21 =>
  validateOCPPPayload(v21Schemas.reservationStatusUpdateResponseV21, data);

export const isValidReserveNowRequestV21 = (
  data: unknown,
): data is ReserveNowRequestV21 =>
  validateOCPPPayload(v21Schemas.reserveNowRequestV21, data);

export const isValidReserveNowResponseV21 = (
  data: unknown,
): data is ReserveNowResponseV21 =>
  validateOCPPPayload(v21Schemas.reserveNowResponseV21, data);

export const isValidResetRequestV21 = (
  data: unknown,
): data is ResetRequestV21 =>
  validateOCPPPayload(v21Schemas.resetRequestV21, data);

export const isValidResetResponseV21 = (
  data: unknown,
): data is ResetResponseV21 =>
  validateOCPPPayload(v21Schemas.resetResponseV21, data);

export const isValidSecurityEventNotificationRequestV21 = (
  data: unknown,
): data is SecurityEventNotificationRequestV21 =>
  validateOCPPPayload(v21Schemas.securityEventNotificationRequestV21, data);

export const isValidSecurityEventNotificationResponseV21 = (
  data: unknown,
): data is SecurityEventNotificationResponseV21 =>
  validateOCPPPayload(v21Schemas.securityEventNotificationResponseV21, data);

export const isValidSendLocalListRequestV21 = (
  data: unknown,
): data is SendLocalListRequestV21 =>
  validateOCPPPayload(v21Schemas.sendLocalListRequestV21, data);

export const isValidSendLocalListResponseV21 = (
  data: unknown,
): data is SendLocalListResponseV21 =>
  validateOCPPPayload(v21Schemas.sendLocalListResponseV21, data);

export const isValidSetChargingProfileRequestV21 = (
  data: unknown,
): data is SetChargingProfileRequestV21 =>
  validateOCPPPayload(v21Schemas.setChargingProfileRequestV21, data);

export const isValidSetChargingProfileResponseV21 = (
  data: unknown,
): data is SetChargingProfileResponseV21 =>
  validateOCPPPayload(v21Schemas.setChargingProfileResponseV21, data);

export const isValidSetDefaultTariffRequestV21 = (
  data: unknown,
): data is SetDefaultTariffRequestV21 =>
  validateOCPPPayload(v21Schemas.setDefaultTariffRequestV21, data);

export const isValidSetDefaultTariffResponseV21 = (
  data: unknown,
): data is SetDefaultTariffResponseV21 =>
  validateOCPPPayload(v21Schemas.setDefaultTariffResponseV21, data);

export const isValidSetDERControlRequestV21 = (
  data: unknown,
): data is SetDERControlRequestV21 =>
  validateOCPPPayload(v21Schemas.setDERControlRequestV21, data);

export const isValidSetDERControlResponseV21 = (
  data: unknown,
): data is SetDERControlResponseV21 =>
  validateOCPPPayload(v21Schemas.setDERControlResponseV21, data);

export const isValidSetDisplayMessageRequestV21 = (
  data: unknown,
): data is SetDisplayMessageRequestV21 =>
  validateOCPPPayload(v21Schemas.setDisplayMessageRequestV21, data);

export const isValidSetDisplayMessageResponseV21 = (
  data: unknown,
): data is SetDisplayMessageResponseV21 =>
  validateOCPPPayload(v21Schemas.setDisplayMessageResponseV21, data);

export const isValidSetMonitoringBaseRequestV21 = (
  data: unknown,
): data is SetMonitoringBaseRequestV21 =>
  validateOCPPPayload(v21Schemas.setMonitoringBaseRequestV21, data);

export const isValidSetMonitoringBaseResponseV21 = (
  data: unknown,
): data is SetMonitoringBaseResponseV21 =>
  validateOCPPPayload(v21Schemas.setMonitoringBaseResponseV21, data);

export const isValidSetMonitoringLevelRequestV21 = (
  data: unknown,
): data is SetMonitoringLevelRequestV21 =>
  validateOCPPPayload(v21Schemas.setMonitoringLevelRequestV21, data);

export const isValidSetMonitoringLevelResponseV21 = (
  data: unknown,
): data is SetMonitoringLevelResponseV21 =>
  validateOCPPPayload(v21Schemas.setMonitoringLevelResponseV21, data);

export const isValidSetNetworkProfileRequestV21 = (
  data: unknown,
): data is SetNetworkProfileRequestV21 =>
  validateOCPPPayload(v21Schemas.setNetworkProfileRequestV21, data);

export const isValidSetNetworkProfileResponseV21 = (
  data: unknown,
): data is SetNetworkProfileResponseV21 =>
  validateOCPPPayload(v21Schemas.setNetworkProfileResponseV21, data);

export const isValidSetVariableMonitoringRequestV21 = (
  data: unknown,
): data is SetVariableMonitoringRequestV21 =>
  validateOCPPPayload(v21Schemas.setVariableMonitoringRequestV21, data);

export const isValidSetVariableMonitoringResponseV21 = (
  data: unknown,
): data is SetVariableMonitoringResponseV21 =>
  validateOCPPPayload(v21Schemas.setVariableMonitoringResponseV21, data);

export const isValidSetVariablesRequestV21 = (
  data: unknown,
): data is SetVariablesRequestV21 =>
  validateOCPPPayload(v21Schemas.setVariablesRequestV21, data);

export const isValidSetVariablesResponseV21 = (
  data: unknown,
): data is SetVariablesResponseV21 =>
  validateOCPPPayload(v21Schemas.setVariablesResponseV21, data);

export const isValidSignCertificateRequestV21 = (
  data: unknown,
): data is SignCertificateRequestV21 =>
  validateOCPPPayload(v21Schemas.signCertificateRequestV21, data);

export const isValidSignCertificateResponseV21 = (
  data: unknown,
): data is SignCertificateResponseV21 =>
  validateOCPPPayload(v21Schemas.signCertificateResponseV21, data);

export const isValidStatusNotificationRequestV21 = (
  data: unknown,
): data is StatusNotificationRequestV21 =>
  validateOCPPPayload(v21Schemas.statusNotificationRequestV21, data);

export const isValidStatusNotificationResponseV21 = (
  data: unknown,
): data is StatusNotificationResponseV21 =>
  validateOCPPPayload(v21Schemas.statusNotificationResponseV21, data);

export const isValidTransactionEventRequestV21 = (
  data: unknown,
): data is TransactionEventRequestV21 =>
  validateOCPPPayload(v21Schemas.transactionEventRequestV21, data);

export const isValidTransactionEventResponseV21 = (
  data: unknown,
): data is TransactionEventResponseV21 =>
  validateOCPPPayload(v21Schemas.transactionEventResponseV21, data);

export const isValidTriggerMessageRequestV21 = (
  data: unknown,
): data is TriggerMessageRequestV21 =>
  validateOCPPPayload(v21Schemas.triggerMessageRequestV21, data);

export const isValidTriggerMessageResponseV21 = (
  data: unknown,
): data is TriggerMessageResponseV21 =>
  validateOCPPPayload(v21Schemas.triggerMessageResponseV21, data);

export const isValidUnlockConnectorRequestV21 = (
  data: unknown,
): data is UnlockConnectorRequestV21 =>
  validateOCPPPayload(v21Schemas.unlockConnectorRequestV21, data);

export const isValidUnlockConnectorResponseV21 = (
  data: unknown,
): data is UnlockConnectorResponseV21 =>
  validateOCPPPayload(v21Schemas.unlockConnectorResponseV21, data);

export const isValidUnpublishFirmwareRequestV21 = (
  data: unknown,
): data is UnpublishFirmwareRequestV21 =>
  validateOCPPPayload(v21Schemas.unpublishFirmwareRequestV21, data);

export const isValidUnpublishFirmwareResponseV21 = (
  data: unknown,
): data is UnpublishFirmwareResponseV21 =>
  validateOCPPPayload(v21Schemas.unpublishFirmwareResponseV21, data);

export const isValidUpdateDynamicScheduleRequestV21 = (
  data: unknown,
): data is UpdateDynamicScheduleRequestV21 =>
  validateOCPPPayload(v21Schemas.updateDynamicScheduleRequestV21, data);

export const isValidUpdateDynamicScheduleResponseV21 = (
  data: unknown,
): data is UpdateDynamicScheduleResponseV21 =>
  validateOCPPPayload(v21Schemas.updateDynamicScheduleResponseV21, data);

export const isValidUpdateFirmwareRequestV21 = (
  data: unknown,
): data is UpdateFirmwareRequestV21 =>
  validateOCPPPayload(v21Schemas.updateFirmwareRequestV21, data);

export const isValidUpdateFirmwareResponseV21 = (
  data: unknown,
): data is UpdateFirmwareResponseV21 =>
  validateOCPPPayload(v21Schemas.updateFirmwareResponseV21, data);

export const isValidUsePriorityChargingRequestV21 = (
  data: unknown,
): data is UsePriorityChargingRequestV21 =>
  validateOCPPPayload(v21Schemas.usePriorityChargingRequestV21, data);

export const isValidUsePriorityChargingResponseV21 = (
  data: unknown,
): data is UsePriorityChargingResponseV21 =>
  validateOCPPPayload(v21Schemas.usePriorityChargingResponseV21, data);

export const isValidVatNumberValidationRequestV21 = (
  data: unknown,
): data is VatNumberValidationRequestV21 =>
  validateOCPPPayload(v21Schemas.vatNumberValidationRequestV21, data);

export const isValidVatNumberValidationResponseV21 = (
  data: unknown,
): data is VatNumberValidationResponseV21 =>
  validateOCPPPayload(v21Schemas.vatNumberValidationResponseV21, data);

export const actionValidatorV21: Record<string, (data: unknown) => boolean> = {
  AdjustPeriodicEventStream: isValidAdjustPeriodicEventStreamRequestV21,
  AFRRSignal: isValidAFRRSignalRequestV21,
  Authorize: isValidAuthorizeRequestV21,
  BatterySwap: isValidBatterySwapRequestV21,
  BootNotification: isValidBootNotificationRequestV21,
  CancelReservation: isValidCancelReservationRequestV21,
  CertificateSigned: isValidCertificateSignedRequestV21,
  ChangeAvailability: isValidChangeAvailabilityRequestV21,
  ChangeTransactionTariff: isValidChangeTransactionTariffRequestV21,
  ClearCache: isValidClearCacheRequestV21,
  ClearChargingProfile: isValidClearChargingProfileRequestV21,
  ClearDERControl: isValidClearDERControlRequestV21,
  ClearDisplayMessage: isValidClearDisplayMessageRequestV21,
  ClearedChargingLimit: isValidClearedChargingLimitRequestV21,
  ClearTariffs: isValidClearTariffsRequestV21,
  ClearVariableMonitoring: isValidClearVariableMonitoringRequestV21,
  ClosePeriodicEventStream: isValidClosePeriodicEventStreamRequestV21,
  CostUpdated: isValidCostUpdatedRequestV21,
  CustomerInformation: isValidCustomerInformationRequestV21,
  DataTransfer: isValidDataTransferRequestV21,
  DeleteCertificate: isValidDeleteCertificateRequestV21,
  FirmwareStatusNotification: isValidFirmwareStatusNotificationRequestV21,
  Get15118EVCertificate: isValidGet15118EVCertificateRequestV21,
  GetBaseReport: isValidGetBaseReportRequestV21,
  GetCertificateChainStatus: isValidGetCertificateChainStatusRequestV21,
  GetCertificateStatus: isValidGetCertificateStatusRequestV21,
  GetChargingProfiles: isValidGetChargingProfilesRequestV21,
  GetCompositeSchedule: isValidGetCompositeScheduleRequestV21,
  GetDERControl: isValidGetDERControlRequestV21,
  GetDisplayMessages: isValidGetDisplayMessagesRequestV21,
  GetInstalledCertificateIds: isValidGetInstalledCertificateIdsRequestV21,
  GetLocalListVersion: isValidGetLocalListVersionRequestV21,
  GetLog: isValidGetLogRequestV21,
  GetMonitoringReport: isValidGetMonitoringReportRequestV21,
  GetPeriodicEventStream: isValidGetPeriodicEventStreamRequestV21,
  GetReport: isValidGetReportRequestV21,
  GetTariffs: isValidGetTariffsRequestV21,
  GetTransactionStatus: isValidGetTransactionStatusRequestV21,
  GetVariables: isValidGetVariablesRequestV21,
  Heartbeat: isValidHeartbeatRequestV21,
  InstallCertificate: isValidInstallCertificateRequestV21,
  LogStatusNotification: isValidLogStatusNotificationRequestV21,
  MeterValues: isValidMeterValuesRequestV21,
  NotifyAllowedEnergyTransfer: isValidNotifyAllowedEnergyTransferRequestV21,
  NotifyChargingLimit: isValidNotifyChargingLimitRequestV21,
  NotifyCustomerInformation: isValidNotifyCustomerInformationRequestV21,
  NotifyDERAlarm: isValidNotifyDERAlarmRequestV21,
  NotifyDERStartStop: isValidNotifyDERStartStopRequestV21,
  NotifyDisplayMessages: isValidNotifyDisplayMessagesRequestV21,
  NotifyEVChargingNeeds: isValidNotifyEVChargingNeedsRequestV21,
  NotifyEVChargingSchedule: isValidNotifyEVChargingScheduleRequestV21,
  NotifyEvent: isValidNotifyEventRequestV21,
  NotifyMonitoringReport: isValidNotifyMonitoringReportRequestV21,
  NotifyPeriodicEventStream: isValidNotifyPeriodicEventStreamRequestV21,
  NotifyPriorityCharging: isValidNotifyPriorityChargingRequestV21,
  NotifyReport: isValidNotifyReportRequestV21,
  NotifySettlement: isValidNotifySettlementRequestV21,
  NotifyWebPaymentStarted: isValidNotifyWebPaymentStartedRequestV21,
  OpenPeriodicEventStream: isValidOpenPeriodicEventStreamRequestV21,
  PublishFirmware: isValidPublishFirmwareRequestV21,
  PublishFirmwareStatusNotification:
    isValidPublishFirmwareStatusNotificationRequestV21,
  PullDynamicScheduleUpdate: isValidPullDynamicScheduleUpdateRequestV21,
  ReportChargingProfiles: isValidReportChargingProfilesRequestV21,
  ReportDERControl: isValidReportDERControlRequestV21,
  RequestBatterySwap: isValidRequestBatterySwapRequestV21,
  RequestStartTransaction: isValidRequestStartTransactionRequestV21,
  RequestStopTransaction: isValidRequestStopTransactionRequestV21,
  ReservationStatusUpdate: isValidReservationStatusUpdateRequestV21,
  ReserveNow: isValidReserveNowRequestV21,
  Reset: isValidResetRequestV21,
  SecurityEventNotification: isValidSecurityEventNotificationRequestV21,
  SendLocalList: isValidSendLocalListRequestV21,
  SetChargingProfile: isValidSetChargingProfileRequestV21,
  SetDefaultTariff: isValidSetDefaultTariffRequestV21,
  SetDERControl: isValidSetDERControlRequestV21,
  SetDisplayMessage: isValidSetDisplayMessageRequestV21,
  SetMonitoringBase: isValidSetMonitoringBaseRequestV21,
  SetMonitoringLevel: isValidSetMonitoringLevelRequestV21,
  SetNetworkProfile: isValidSetNetworkProfileRequestV21,
  SetVariableMonitoring: isValidSetVariableMonitoringRequestV21,
  SetVariables: isValidSetVariablesRequestV21,
  SignCertificate: isValidSignCertificateRequestV21,
  StatusNotification: isValidStatusNotificationRequestV21,
  TransactionEvent: isValidTransactionEventRequestV21,
  TriggerMessage: isValidTriggerMessageRequestV21,
  UnlockConnector: isValidUnlockConnectorRequestV21,
  UnpublishFirmware: isValidUnpublishFirmwareRequestV21,
  UpdateDynamicSchedule: isValidUpdateDynamicScheduleRequestV21,
  UpdateFirmware: isValidUpdateFirmwareRequestV21,
  UsePriorityCharging: isValidUsePriorityChargingRequestV21,
  VatNumberValidation: isValidVatNumberValidationRequestV21,
};
