// src/cli/exportK6/emit/render.ts
// String templates for the generated bundle. Kept CLI-side (not part of the
// emitted runtime).
import type { ScenarioJson, ScenarioNodeJson } from "../runtime/types";

// Scenario-derived text (name, id, node labels) is embedded in `//` comments
// of the generated script. A raw line terminator in any of it would close
// the comment early and splice the rest of the value in as executable code,
// so every such value is routed through this before interpolation.
function sanitizeForComment(value: string): string {
  return value.replace(/[\r\n\u2028\u2029]/g, " ");
}

export function renderEntryScript(
  scenario: ScenarioJson,
  opts: { ocppVersion: string },
): string {
  const steps = summarizeSteps(scenario)
    .map((line, i) => `//   ${i + 1}. ${line}`)
    .join("\n");
  const scenarioName = sanitizeForComment(scenario.name ?? scenario.id);
  const scenarioId = sanitizeForComment(scenario.id);
  return `// Generated by ocpp-cp-sim export-k6 — regenerate rather than editing ocpp-runtime/.
// Scenario: ${scenarioName} (${scenarioId})
// OCPP version: ${opts.ocppVersion} (override at run time with OCPP_VERSION)
// Requires k6 >= v1.6.0 (uses the stable k6/websockets module). See README.md for env vars.
//
// Steps:
${steps}
import { check } from "k6";
import {
  OcppChargePoint,
  buildOptions,
  createWire,
  evaluateAssertions,
  loadIdentities,
  requiredEnv,
  resolveIdentity,
  runScenario,
  scenarioSuccess,
  type ScenarioJson,
} from "./ocpp-runtime/index";

declare const __ENV: Record<string, string | undefined>;
declare const __VU: number;
declare function open(path: string): string;

const scenario = JSON.parse(open("./scenario.json")) as ScenarioJson;
const identities = loadIdentities(__ENV);

export const options = buildOptions(__ENV);

export default async function (): Promise<void> {
  const identity = resolveIdentity(identities, __ENV, __VU);
  const wire = createWire(__ENV.OCPP_VERSION ?? ${JSON.stringify(opts.ocppVersion)});
  const cp = new OcppChargePoint({
    url: requiredEnv(__ENV, "CSMS_URL"),
    identity,
    wire,
    connectorId: scenario.targetId ?? 1,
  });
  let ok = false;
  try {
    await cp.connect();
    const result = await runScenario(cp, wire, scenario);
    const outcomes = evaluateAssertions(
      scenario.assertions ?? [],
      cp.transcript(),
      cp.status(),
    );
    for (const outcome of outcomes) {
      check(outcome, { [\`assertion \${outcome.id}\`]: (o) => o.ok });
    }
    ok = result.completed && outcomes.every((o) => o.ok);
    if (!result.completed) {
      console.error(\`[\${identity.cpId}] scenario failed: \${result.error}\`);
    }
    if ((__ENV.PROFILE ?? "steady") === "soak" && ok) {
      await cp.hold();
    }
  } finally {
    scenarioSuccess.add(ok);
    cp.close();
  }
}
`;
}

function summarizeSteps(scenario: ScenarioJson): string[] {
  const byId = new Map(scenario.nodes.map((n) => [n.id, n]));
  const lines: string[] = [];
  const visited = new Set<string>();
  const queue: ScenarioNodeJson[] = scenario.nodes.filter(
    (n) => n.type === "start",
  );
  while (queue.length > 0 && lines.length < 50) {
    const node = queue.shift() as ScenarioNodeJson;
    if (visited.has(node.id)) continue;
    visited.add(node.id);
    if (node.type !== "start" && node.type !== "end") {
      const label = sanitizeForComment(
        typeof node.data.label === "string" ? node.data.label : node.id,
      );
      lines.push(`${label} (${node.type})`);
    }
    for (const edge of scenario.edges) {
      const target = byId.get(edge.target);
      if (edge.source === node.id && target !== undefined) queue.push(target);
    }
  }
  return lines;
}

export function renderReadme(opts: {
  scenarioName: string;
  ocppVersion: string;
}): string {
  return `# k6 load test: ${opts.scenarioName}

Generated by \`ocpp-cp-sim export-k6\`. Requires **k6 >= v1.6.0** (uses the stable \`k6/websockets\` module).

## Run

\`\`\`sh
CSMS_URL=wss://csms.example.com/ocpp k6 run scenario.k6.ts
CSMS_URL=... PROFILE=spike VUS=1000 RAMP_DURATION=2m k6 run scenario.k6.ts
CSMS_URL=... PROFILE=soak VUS=200 DURATION=8h k6 run scenario.k6.ts
\`\`\`

## Environment variables

| Variable | Default | Meaning |
|---|---|---|
| \`CSMS_URL\` | (required) | Base OCPP WebSocket URL; the charge point id is appended as a path segment |
| \`PROFILE\` | \`steady\` | \`spike\` (ramping connect storm), \`steady\` (connect -> scenario -> close per iteration), \`soak\` (run once, then hold the connection with heartbeats) |
| \`VUS\` | \`5\` | Concurrent virtual charge points |
| \`DURATION\` | \`5m\` (\`1h\` for soak) | Test duration |
| \`RAMP_DURATION\` | \`1m\` | Spike ramp-up time |
| \`CP_IDS_FILE\` | (none) | JSON array of \`{"cpId": "...", "basicPassword": "..."}\`; assigned per VU round-robin (see ids.example.json) |
| \`CP_ID_TEMPLATE\` | \`CP-\${__VU}\` | Identity fallback when no CP_IDS_FILE is given |
| \`BASIC_AUTH_PASSWORD\` | (none) | Shared HTTP Basic password for template identities |
| \`OCPP_VERSION\` | \`${opts.ocppVersion}\` | Wire version (this runtime build supports 1.6) |

## mTLS

k6 client certificates are configured **per domain**, not per VU: add a
\`tlsAuth\` entry to \`options\` in scenario.k6.ts:

\`\`\`ts
export const options = {
  ...buildOptions(__ENV),
  tlsAuth: [{ domains: ["csms.example.com"], cert: open("./client.crt"), key: open("./client.key") }],
};
\`\`\`

## Limitations

- All VUs share one client certificate (k6 \`tlsAuth\` is per-domain — per-CP
  certificates would need an xk6 extension).
- \`trigger: statusChange\` scenarios start immediately (there is no external
  status source in k6).
- The EV battery model is a simplified linear SoC progression.

## Custom metrics

\`ocpp_call_duration\` (by action), \`ocpp_calls\`, \`ocpp_errors\` (CALLERROR /
timeout, by action), \`ocpp_boot_time\`, \`scenario_success\` (thresholded at
rate>0.99 by default).
`;
}

export function renderIdsExample(): string {
  return `${JSON.stringify(
    [
      { cpId: "CP-0001", basicPassword: "change-me" },
      { cpId: "CP-0002", basicPassword: "change-me" },
    ],
    null,
    2,
  )}\n`;
}
