// Generated by scripts/generate-ocpp.ts. Do not edit.

import authorizeRequestV201Schema from "../../../vendor/ocpp-schemas/v201/AuthorizeRequest.json";
import authorizeResponseV201Schema from "../../../vendor/ocpp-schemas/v201/AuthorizeResponse.json";
import bootNotificationRequestV201Schema from "../../../vendor/ocpp-schemas/v201/BootNotificationRequest.json";
import bootNotificationResponseV201Schema from "../../../vendor/ocpp-schemas/v201/BootNotificationResponse.json";
import cancelReservationRequestV201Schema from "../../../vendor/ocpp-schemas/v201/CancelReservationRequest.json";
import cancelReservationResponseV201Schema from "../../../vendor/ocpp-schemas/v201/CancelReservationResponse.json";
import certificateSignedRequestV201Schema from "../../../vendor/ocpp-schemas/v201/CertificateSignedRequest.json";
import certificateSignedResponseV201Schema from "../../../vendor/ocpp-schemas/v201/CertificateSignedResponse.json";
import changeAvailabilityRequestV201Schema from "../../../vendor/ocpp-schemas/v201/ChangeAvailabilityRequest.json";
import changeAvailabilityResponseV201Schema from "../../../vendor/ocpp-schemas/v201/ChangeAvailabilityResponse.json";
import clearCacheRequestV201Schema from "../../../vendor/ocpp-schemas/v201/ClearCacheRequest.json";
import clearCacheResponseV201Schema from "../../../vendor/ocpp-schemas/v201/ClearCacheResponse.json";
import clearChargingProfileRequestV201Schema from "../../../vendor/ocpp-schemas/v201/ClearChargingProfileRequest.json";
import clearChargingProfileResponseV201Schema from "../../../vendor/ocpp-schemas/v201/ClearChargingProfileResponse.json";
import clearDisplayMessageRequestV201Schema from "../../../vendor/ocpp-schemas/v201/ClearDisplayMessageRequest.json";
import clearDisplayMessageResponseV201Schema from "../../../vendor/ocpp-schemas/v201/ClearDisplayMessageResponse.json";
import clearedChargingLimitRequestV201Schema from "../../../vendor/ocpp-schemas/v201/ClearedChargingLimitRequest.json";
import clearedChargingLimitResponseV201Schema from "../../../vendor/ocpp-schemas/v201/ClearedChargingLimitResponse.json";
import clearVariableMonitoringRequestV201Schema from "../../../vendor/ocpp-schemas/v201/ClearVariableMonitoringRequest.json";
import clearVariableMonitoringResponseV201Schema from "../../../vendor/ocpp-schemas/v201/ClearVariableMonitoringResponse.json";
import costUpdatedRequestV201Schema from "../../../vendor/ocpp-schemas/v201/CostUpdatedRequest.json";
import costUpdatedResponseV201Schema from "../../../vendor/ocpp-schemas/v201/CostUpdatedResponse.json";
import customerInformationRequestV201Schema from "../../../vendor/ocpp-schemas/v201/CustomerInformationRequest.json";
import customerInformationResponseV201Schema from "../../../vendor/ocpp-schemas/v201/CustomerInformationResponse.json";
import dataTransferRequestV201Schema from "../../../vendor/ocpp-schemas/v201/DataTransferRequest.json";
import dataTransferResponseV201Schema from "../../../vendor/ocpp-schemas/v201/DataTransferResponse.json";
import deleteCertificateRequestV201Schema from "../../../vendor/ocpp-schemas/v201/DeleteCertificateRequest.json";
import deleteCertificateResponseV201Schema from "../../../vendor/ocpp-schemas/v201/DeleteCertificateResponse.json";
import firmwareStatusNotificationRequestV201Schema from "../../../vendor/ocpp-schemas/v201/FirmwareStatusNotificationRequest.json";
import firmwareStatusNotificationResponseV201Schema from "../../../vendor/ocpp-schemas/v201/FirmwareStatusNotificationResponse.json";
import get15118EVCertificateRequestV201Schema from "../../../vendor/ocpp-schemas/v201/Get15118EVCertificateRequest.json";
import get15118EVCertificateResponseV201Schema from "../../../vendor/ocpp-schemas/v201/Get15118EVCertificateResponse.json";
import getBaseReportRequestV201Schema from "../../../vendor/ocpp-schemas/v201/GetBaseReportRequest.json";
import getBaseReportResponseV201Schema from "../../../vendor/ocpp-schemas/v201/GetBaseReportResponse.json";
import getCertificateStatusRequestV201Schema from "../../../vendor/ocpp-schemas/v201/GetCertificateStatusRequest.json";
import getCertificateStatusResponseV201Schema from "../../../vendor/ocpp-schemas/v201/GetCertificateStatusResponse.json";
import getChargingProfilesRequestV201Schema from "../../../vendor/ocpp-schemas/v201/GetChargingProfilesRequest.json";
import getChargingProfilesResponseV201Schema from "../../../vendor/ocpp-schemas/v201/GetChargingProfilesResponse.json";
import getCompositeScheduleRequestV201Schema from "../../../vendor/ocpp-schemas/v201/GetCompositeScheduleRequest.json";
import getCompositeScheduleResponseV201Schema from "../../../vendor/ocpp-schemas/v201/GetCompositeScheduleResponse.json";
import getDisplayMessagesRequestV201Schema from "../../../vendor/ocpp-schemas/v201/GetDisplayMessagesRequest.json";
import getDisplayMessagesResponseV201Schema from "../../../vendor/ocpp-schemas/v201/GetDisplayMessagesResponse.json";
import getInstalledCertificateIdsRequestV201Schema from "../../../vendor/ocpp-schemas/v201/GetInstalledCertificateIdsRequest.json";
import getInstalledCertificateIdsResponseV201Schema from "../../../vendor/ocpp-schemas/v201/GetInstalledCertificateIdsResponse.json";
import getLocalListVersionRequestV201Schema from "../../../vendor/ocpp-schemas/v201/GetLocalListVersionRequest.json";
import getLocalListVersionResponseV201Schema from "../../../vendor/ocpp-schemas/v201/GetLocalListVersionResponse.json";
import getLogRequestV201Schema from "../../../vendor/ocpp-schemas/v201/GetLogRequest.json";
import getLogResponseV201Schema from "../../../vendor/ocpp-schemas/v201/GetLogResponse.json";
import getMonitoringReportRequestV201Schema from "../../../vendor/ocpp-schemas/v201/GetMonitoringReportRequest.json";
import getMonitoringReportResponseV201Schema from "../../../vendor/ocpp-schemas/v201/GetMonitoringReportResponse.json";
import getReportRequestV201Schema from "../../../vendor/ocpp-schemas/v201/GetReportRequest.json";
import getReportResponseV201Schema from "../../../vendor/ocpp-schemas/v201/GetReportResponse.json";
import getTransactionStatusRequestV201Schema from "../../../vendor/ocpp-schemas/v201/GetTransactionStatusRequest.json";
import getTransactionStatusResponseV201Schema from "../../../vendor/ocpp-schemas/v201/GetTransactionStatusResponse.json";
import getVariablesRequestV201Schema from "../../../vendor/ocpp-schemas/v201/GetVariablesRequest.json";
import getVariablesResponseV201Schema from "../../../vendor/ocpp-schemas/v201/GetVariablesResponse.json";
import heartbeatRequestV201Schema from "../../../vendor/ocpp-schemas/v201/HeartbeatRequest.json";
import heartbeatResponseV201Schema from "../../../vendor/ocpp-schemas/v201/HeartbeatResponse.json";
import installCertificateRequestV201Schema from "../../../vendor/ocpp-schemas/v201/InstallCertificateRequest.json";
import installCertificateResponseV201Schema from "../../../vendor/ocpp-schemas/v201/InstallCertificateResponse.json";
import logStatusNotificationRequestV201Schema from "../../../vendor/ocpp-schemas/v201/LogStatusNotificationRequest.json";
import logStatusNotificationResponseV201Schema from "../../../vendor/ocpp-schemas/v201/LogStatusNotificationResponse.json";
import meterValuesRequestV201Schema from "../../../vendor/ocpp-schemas/v201/MeterValuesRequest.json";
import meterValuesResponseV201Schema from "../../../vendor/ocpp-schemas/v201/MeterValuesResponse.json";
import notifyChargingLimitRequestV201Schema from "../../../vendor/ocpp-schemas/v201/NotifyChargingLimitRequest.json";
import notifyChargingLimitResponseV201Schema from "../../../vendor/ocpp-schemas/v201/NotifyChargingLimitResponse.json";
import notifyCustomerInformationRequestV201Schema from "../../../vendor/ocpp-schemas/v201/NotifyCustomerInformationRequest.json";
import notifyCustomerInformationResponseV201Schema from "../../../vendor/ocpp-schemas/v201/NotifyCustomerInformationResponse.json";
import notifyDisplayMessagesRequestV201Schema from "../../../vendor/ocpp-schemas/v201/NotifyDisplayMessagesRequest.json";
import notifyDisplayMessagesResponseV201Schema from "../../../vendor/ocpp-schemas/v201/NotifyDisplayMessagesResponse.json";
import notifyEVChargingNeedsRequestV201Schema from "../../../vendor/ocpp-schemas/v201/NotifyEVChargingNeedsRequest.json";
import notifyEVChargingNeedsResponseV201Schema from "../../../vendor/ocpp-schemas/v201/NotifyEVChargingNeedsResponse.json";
import notifyEVChargingScheduleRequestV201Schema from "../../../vendor/ocpp-schemas/v201/NotifyEVChargingScheduleRequest.json";
import notifyEVChargingScheduleResponseV201Schema from "../../../vendor/ocpp-schemas/v201/NotifyEVChargingScheduleResponse.json";
import notifyEventRequestV201Schema from "../../../vendor/ocpp-schemas/v201/NotifyEventRequest.json";
import notifyEventResponseV201Schema from "../../../vendor/ocpp-schemas/v201/NotifyEventResponse.json";
import notifyMonitoringReportRequestV201Schema from "../../../vendor/ocpp-schemas/v201/NotifyMonitoringReportRequest.json";
import notifyMonitoringReportResponseV201Schema from "../../../vendor/ocpp-schemas/v201/NotifyMonitoringReportResponse.json";
import notifyReportRequestV201Schema from "../../../vendor/ocpp-schemas/v201/NotifyReportRequest.json";
import notifyReportResponseV201Schema from "../../../vendor/ocpp-schemas/v201/NotifyReportResponse.json";
import publishFirmwareRequestV201Schema from "../../../vendor/ocpp-schemas/v201/PublishFirmwareRequest.json";
import publishFirmwareResponseV201Schema from "../../../vendor/ocpp-schemas/v201/PublishFirmwareResponse.json";
import publishFirmwareStatusNotificationRequestV201Schema from "../../../vendor/ocpp-schemas/v201/PublishFirmwareStatusNotificationRequest.json";
import publishFirmwareStatusNotificationResponseV201Schema from "../../../vendor/ocpp-schemas/v201/PublishFirmwareStatusNotificationResponse.json";
import reportChargingProfilesRequestV201Schema from "../../../vendor/ocpp-schemas/v201/ReportChargingProfilesRequest.json";
import reportChargingProfilesResponseV201Schema from "../../../vendor/ocpp-schemas/v201/ReportChargingProfilesResponse.json";
import requestStartTransactionRequestV201Schema from "../../../vendor/ocpp-schemas/v201/RequestStartTransactionRequest.json";
import requestStartTransactionResponseV201Schema from "../../../vendor/ocpp-schemas/v201/RequestStartTransactionResponse.json";
import requestStopTransactionRequestV201Schema from "../../../vendor/ocpp-schemas/v201/RequestStopTransactionRequest.json";
import requestStopTransactionResponseV201Schema from "../../../vendor/ocpp-schemas/v201/RequestStopTransactionResponse.json";
import reservationStatusUpdateRequestV201Schema from "../../../vendor/ocpp-schemas/v201/ReservationStatusUpdateRequest.json";
import reservationStatusUpdateResponseV201Schema from "../../../vendor/ocpp-schemas/v201/ReservationStatusUpdateResponse.json";
import reserveNowRequestV201Schema from "../../../vendor/ocpp-schemas/v201/ReserveNowRequest.json";
import reserveNowResponseV201Schema from "../../../vendor/ocpp-schemas/v201/ReserveNowResponse.json";
import resetRequestV201Schema from "../../../vendor/ocpp-schemas/v201/ResetRequest.json";
import resetResponseV201Schema from "../../../vendor/ocpp-schemas/v201/ResetResponse.json";
import securityEventNotificationRequestV201Schema from "../../../vendor/ocpp-schemas/v201/SecurityEventNotificationRequest.json";
import securityEventNotificationResponseV201Schema from "../../../vendor/ocpp-schemas/v201/SecurityEventNotificationResponse.json";
import sendLocalListRequestV201Schema from "../../../vendor/ocpp-schemas/v201/SendLocalListRequest.json";
import sendLocalListResponseV201Schema from "../../../vendor/ocpp-schemas/v201/SendLocalListResponse.json";
import setChargingProfileRequestV201Schema from "../../../vendor/ocpp-schemas/v201/SetChargingProfileRequest.json";
import setChargingProfileResponseV201Schema from "../../../vendor/ocpp-schemas/v201/SetChargingProfileResponse.json";
import setDisplayMessageRequestV201Schema from "../../../vendor/ocpp-schemas/v201/SetDisplayMessageRequest.json";
import setDisplayMessageResponseV201Schema from "../../../vendor/ocpp-schemas/v201/SetDisplayMessageResponse.json";
import setMonitoringBaseRequestV201Schema from "../../../vendor/ocpp-schemas/v201/SetMonitoringBaseRequest.json";
import setMonitoringBaseResponseV201Schema from "../../../vendor/ocpp-schemas/v201/SetMonitoringBaseResponse.json";
import setMonitoringLevelRequestV201Schema from "../../../vendor/ocpp-schemas/v201/SetMonitoringLevelRequest.json";
import setMonitoringLevelResponseV201Schema from "../../../vendor/ocpp-schemas/v201/SetMonitoringLevelResponse.json";
import setNetworkProfileRequestV201Schema from "../../../vendor/ocpp-schemas/v201/SetNetworkProfileRequest.json";
import setNetworkProfileResponseV201Schema from "../../../vendor/ocpp-schemas/v201/SetNetworkProfileResponse.json";
import setVariableMonitoringRequestV201Schema from "../../../vendor/ocpp-schemas/v201/SetVariableMonitoringRequest.json";
import setVariableMonitoringResponseV201Schema from "../../../vendor/ocpp-schemas/v201/SetVariableMonitoringResponse.json";
import setVariablesRequestV201Schema from "../../../vendor/ocpp-schemas/v201/SetVariablesRequest.json";
import setVariablesResponseV201Schema from "../../../vendor/ocpp-schemas/v201/SetVariablesResponse.json";
import signCertificateRequestV201Schema from "../../../vendor/ocpp-schemas/v201/SignCertificateRequest.json";
import signCertificateResponseV201Schema from "../../../vendor/ocpp-schemas/v201/SignCertificateResponse.json";
import statusNotificationRequestV201Schema from "../../../vendor/ocpp-schemas/v201/StatusNotificationRequest.json";
import statusNotificationResponseV201Schema from "../../../vendor/ocpp-schemas/v201/StatusNotificationResponse.json";
import transactionEventRequestV201Schema from "../../../vendor/ocpp-schemas/v201/TransactionEventRequest.json";
import transactionEventResponseV201Schema from "../../../vendor/ocpp-schemas/v201/TransactionEventResponse.json";
import triggerMessageRequestV201Schema from "../../../vendor/ocpp-schemas/v201/TriggerMessageRequest.json";
import triggerMessageResponseV201Schema from "../../../vendor/ocpp-schemas/v201/TriggerMessageResponse.json";
import unlockConnectorRequestV201Schema from "../../../vendor/ocpp-schemas/v201/UnlockConnectorRequest.json";
import unlockConnectorResponseV201Schema from "../../../vendor/ocpp-schemas/v201/UnlockConnectorResponse.json";
import unpublishFirmwareRequestV201Schema from "../../../vendor/ocpp-schemas/v201/UnpublishFirmwareRequest.json";
import unpublishFirmwareResponseV201Schema from "../../../vendor/ocpp-schemas/v201/UnpublishFirmwareResponse.json";
import updateFirmwareRequestV201Schema from "../../../vendor/ocpp-schemas/v201/UpdateFirmwareRequest.json";
import updateFirmwareResponseV201Schema from "../../../vendor/ocpp-schemas/v201/UpdateFirmwareResponse.json";

export const v201Schemas: Record<string, object> = {
  authorizeRequestV201: authorizeRequestV201Schema,
  authorizeResponseV201: authorizeResponseV201Schema,
  bootNotificationRequestV201: bootNotificationRequestV201Schema,
  bootNotificationResponseV201: bootNotificationResponseV201Schema,
  cancelReservationRequestV201: cancelReservationRequestV201Schema,
  cancelReservationResponseV201: cancelReservationResponseV201Schema,
  certificateSignedRequestV201: certificateSignedRequestV201Schema,
  certificateSignedResponseV201: certificateSignedResponseV201Schema,
  changeAvailabilityRequestV201: changeAvailabilityRequestV201Schema,
  changeAvailabilityResponseV201: changeAvailabilityResponseV201Schema,
  clearCacheRequestV201: clearCacheRequestV201Schema,
  clearCacheResponseV201: clearCacheResponseV201Schema,
  clearChargingProfileRequestV201: clearChargingProfileRequestV201Schema,
  clearChargingProfileResponseV201: clearChargingProfileResponseV201Schema,
  clearDisplayMessageRequestV201: clearDisplayMessageRequestV201Schema,
  clearDisplayMessageResponseV201: clearDisplayMessageResponseV201Schema,
  clearedChargingLimitRequestV201: clearedChargingLimitRequestV201Schema,
  clearedChargingLimitResponseV201: clearedChargingLimitResponseV201Schema,
  clearVariableMonitoringRequestV201: clearVariableMonitoringRequestV201Schema,
  clearVariableMonitoringResponseV201:
    clearVariableMonitoringResponseV201Schema,
  costUpdatedRequestV201: costUpdatedRequestV201Schema,
  costUpdatedResponseV201: costUpdatedResponseV201Schema,
  customerInformationRequestV201: customerInformationRequestV201Schema,
  customerInformationResponseV201: customerInformationResponseV201Schema,
  dataTransferRequestV201: dataTransferRequestV201Schema,
  dataTransferResponseV201: dataTransferResponseV201Schema,
  deleteCertificateRequestV201: deleteCertificateRequestV201Schema,
  deleteCertificateResponseV201: deleteCertificateResponseV201Schema,
  firmwareStatusNotificationRequestV201:
    firmwareStatusNotificationRequestV201Schema,
  firmwareStatusNotificationResponseV201:
    firmwareStatusNotificationResponseV201Schema,
  get15118EVCertificateRequestV201: get15118EVCertificateRequestV201Schema,
  get15118EVCertificateResponseV201: get15118EVCertificateResponseV201Schema,
  getBaseReportRequestV201: getBaseReportRequestV201Schema,
  getBaseReportResponseV201: getBaseReportResponseV201Schema,
  getCertificateStatusRequestV201: getCertificateStatusRequestV201Schema,
  getCertificateStatusResponseV201: getCertificateStatusResponseV201Schema,
  getChargingProfilesRequestV201: getChargingProfilesRequestV201Schema,
  getChargingProfilesResponseV201: getChargingProfilesResponseV201Schema,
  getCompositeScheduleRequestV201: getCompositeScheduleRequestV201Schema,
  getCompositeScheduleResponseV201: getCompositeScheduleResponseV201Schema,
  getDisplayMessagesRequestV201: getDisplayMessagesRequestV201Schema,
  getDisplayMessagesResponseV201: getDisplayMessagesResponseV201Schema,
  getInstalledCertificateIdsRequestV201:
    getInstalledCertificateIdsRequestV201Schema,
  getInstalledCertificateIdsResponseV201:
    getInstalledCertificateIdsResponseV201Schema,
  getLocalListVersionRequestV201: getLocalListVersionRequestV201Schema,
  getLocalListVersionResponseV201: getLocalListVersionResponseV201Schema,
  getLogRequestV201: getLogRequestV201Schema,
  getLogResponseV201: getLogResponseV201Schema,
  getMonitoringReportRequestV201: getMonitoringReportRequestV201Schema,
  getMonitoringReportResponseV201: getMonitoringReportResponseV201Schema,
  getReportRequestV201: getReportRequestV201Schema,
  getReportResponseV201: getReportResponseV201Schema,
  getTransactionStatusRequestV201: getTransactionStatusRequestV201Schema,
  getTransactionStatusResponseV201: getTransactionStatusResponseV201Schema,
  getVariablesRequestV201: getVariablesRequestV201Schema,
  getVariablesResponseV201: getVariablesResponseV201Schema,
  heartbeatRequestV201: heartbeatRequestV201Schema,
  heartbeatResponseV201: heartbeatResponseV201Schema,
  installCertificateRequestV201: installCertificateRequestV201Schema,
  installCertificateResponseV201: installCertificateResponseV201Schema,
  logStatusNotificationRequestV201: logStatusNotificationRequestV201Schema,
  logStatusNotificationResponseV201: logStatusNotificationResponseV201Schema,
  meterValuesRequestV201: meterValuesRequestV201Schema,
  meterValuesResponseV201: meterValuesResponseV201Schema,
  notifyChargingLimitRequestV201: notifyChargingLimitRequestV201Schema,
  notifyChargingLimitResponseV201: notifyChargingLimitResponseV201Schema,
  notifyCustomerInformationRequestV201:
    notifyCustomerInformationRequestV201Schema,
  notifyCustomerInformationResponseV201:
    notifyCustomerInformationResponseV201Schema,
  notifyDisplayMessagesRequestV201: notifyDisplayMessagesRequestV201Schema,
  notifyDisplayMessagesResponseV201: notifyDisplayMessagesResponseV201Schema,
  notifyEVChargingNeedsRequestV201: notifyEVChargingNeedsRequestV201Schema,
  notifyEVChargingNeedsResponseV201: notifyEVChargingNeedsResponseV201Schema,
  notifyEVChargingScheduleRequestV201:
    notifyEVChargingScheduleRequestV201Schema,
  notifyEVChargingScheduleResponseV201:
    notifyEVChargingScheduleResponseV201Schema,
  notifyEventRequestV201: notifyEventRequestV201Schema,
  notifyEventResponseV201: notifyEventResponseV201Schema,
  notifyMonitoringReportRequestV201: notifyMonitoringReportRequestV201Schema,
  notifyMonitoringReportResponseV201: notifyMonitoringReportResponseV201Schema,
  notifyReportRequestV201: notifyReportRequestV201Schema,
  notifyReportResponseV201: notifyReportResponseV201Schema,
  publishFirmwareRequestV201: publishFirmwareRequestV201Schema,
  publishFirmwareResponseV201: publishFirmwareResponseV201Schema,
  publishFirmwareStatusNotificationRequestV201:
    publishFirmwareStatusNotificationRequestV201Schema,
  publishFirmwareStatusNotificationResponseV201:
    publishFirmwareStatusNotificationResponseV201Schema,
  reportChargingProfilesRequestV201: reportChargingProfilesRequestV201Schema,
  reportChargingProfilesResponseV201: reportChargingProfilesResponseV201Schema,
  requestStartTransactionRequestV201: requestStartTransactionRequestV201Schema,
  requestStartTransactionResponseV201:
    requestStartTransactionResponseV201Schema,
  requestStopTransactionRequestV201: requestStopTransactionRequestV201Schema,
  requestStopTransactionResponseV201: requestStopTransactionResponseV201Schema,
  reservationStatusUpdateRequestV201: reservationStatusUpdateRequestV201Schema,
  reservationStatusUpdateResponseV201:
    reservationStatusUpdateResponseV201Schema,
  reserveNowRequestV201: reserveNowRequestV201Schema,
  reserveNowResponseV201: reserveNowResponseV201Schema,
  resetRequestV201: resetRequestV201Schema,
  resetResponseV201: resetResponseV201Schema,
  securityEventNotificationRequestV201:
    securityEventNotificationRequestV201Schema,
  securityEventNotificationResponseV201:
    securityEventNotificationResponseV201Schema,
  sendLocalListRequestV201: sendLocalListRequestV201Schema,
  sendLocalListResponseV201: sendLocalListResponseV201Schema,
  setChargingProfileRequestV201: setChargingProfileRequestV201Schema,
  setChargingProfileResponseV201: setChargingProfileResponseV201Schema,
  setDisplayMessageRequestV201: setDisplayMessageRequestV201Schema,
  setDisplayMessageResponseV201: setDisplayMessageResponseV201Schema,
  setMonitoringBaseRequestV201: setMonitoringBaseRequestV201Schema,
  setMonitoringBaseResponseV201: setMonitoringBaseResponseV201Schema,
  setMonitoringLevelRequestV201: setMonitoringLevelRequestV201Schema,
  setMonitoringLevelResponseV201: setMonitoringLevelResponseV201Schema,
  setNetworkProfileRequestV201: setNetworkProfileRequestV201Schema,
  setNetworkProfileResponseV201: setNetworkProfileResponseV201Schema,
  setVariableMonitoringRequestV201: setVariableMonitoringRequestV201Schema,
  setVariableMonitoringResponseV201: setVariableMonitoringResponseV201Schema,
  setVariablesRequestV201: setVariablesRequestV201Schema,
  setVariablesResponseV201: setVariablesResponseV201Schema,
  signCertificateRequestV201: signCertificateRequestV201Schema,
  signCertificateResponseV201: signCertificateResponseV201Schema,
  statusNotificationRequestV201: statusNotificationRequestV201Schema,
  statusNotificationResponseV201: statusNotificationResponseV201Schema,
  transactionEventRequestV201: transactionEventRequestV201Schema,
  transactionEventResponseV201: transactionEventResponseV201Schema,
  triggerMessageRequestV201: triggerMessageRequestV201Schema,
  triggerMessageResponseV201: triggerMessageResponseV201Schema,
  unlockConnectorRequestV201: unlockConnectorRequestV201Schema,
  unlockConnectorResponseV201: unlockConnectorResponseV201Schema,
  unpublishFirmwareRequestV201: unpublishFirmwareRequestV201Schema,
  unpublishFirmwareResponseV201: unpublishFirmwareResponseV201Schema,
  updateFirmwareRequestV201: updateFirmwareRequestV201Schema,
  updateFirmwareResponseV201: updateFirmwareResponseV201Schema,
};
