// Generated by scripts/generate-ocpp.ts. Do not edit.

import { validateOCPPPayload } from "../validate";
import { v201Schemas } from "./schemas";
import type { AuthorizeRequestV201 } from "./types/authorize-request";
import type { AuthorizeResponseV201 } from "./types/authorize-response";
import type { BootNotificationRequestV201 } from "./types/boot-notification-request";
import type { BootNotificationResponseV201 } from "./types/boot-notification-response";
import type { CancelReservationRequestV201 } from "./types/cancel-reservation-request";
import type { CancelReservationResponseV201 } from "./types/cancel-reservation-response";
import type { CertificateSignedRequestV201 } from "./types/certificate-signed-request";
import type { CertificateSignedResponseV201 } from "./types/certificate-signed-response";
import type { ChangeAvailabilityRequestV201 } from "./types/change-availability-request";
import type { ChangeAvailabilityResponseV201 } from "./types/change-availability-response";
import type { ClearCacheRequestV201 } from "./types/clear-cache-request";
import type { ClearCacheResponseV201 } from "./types/clear-cache-response";
import type { ClearChargingProfileRequestV201 } from "./types/clear-charging-profile-request";
import type { ClearChargingProfileResponseV201 } from "./types/clear-charging-profile-response";
import type { ClearDisplayMessageRequestV201 } from "./types/clear-display-message-request";
import type { ClearDisplayMessageResponseV201 } from "./types/clear-display-message-response";
import type { ClearedChargingLimitRequestV201 } from "./types/cleared-charging-limit-request";
import type { ClearedChargingLimitResponseV201 } from "./types/cleared-charging-limit-response";
import type { ClearVariableMonitoringRequestV201 } from "./types/clear-variable-monitoring-request";
import type { ClearVariableMonitoringResponseV201 } from "./types/clear-variable-monitoring-response";
import type { CostUpdatedRequestV201 } from "./types/cost-updated-request";
import type { CostUpdatedResponseV201 } from "./types/cost-updated-response";
import type { CustomerInformationRequestV201 } from "./types/customer-information-request";
import type { CustomerInformationResponseV201 } from "./types/customer-information-response";
import type { DataTransferRequestV201 } from "./types/data-transfer-request";
import type { DataTransferResponseV201 } from "./types/data-transfer-response";
import type { DeleteCertificateRequestV201 } from "./types/delete-certificate-request";
import type { DeleteCertificateResponseV201 } from "./types/delete-certificate-response";
import type { FirmwareStatusNotificationRequestV201 } from "./types/firmware-status-notification-request";
import type { FirmwareStatusNotificationResponseV201 } from "./types/firmware-status-notification-response";
import type { Get15118EVCertificateRequestV201 } from "./types/get15118-ev-certificate-request";
import type { Get15118EVCertificateResponseV201 } from "./types/get15118-ev-certificate-response";
import type { GetBaseReportRequestV201 } from "./types/get-base-report-request";
import type { GetBaseReportResponseV201 } from "./types/get-base-report-response";
import type { GetCertificateStatusRequestV201 } from "./types/get-certificate-status-request";
import type { GetCertificateStatusResponseV201 } from "./types/get-certificate-status-response";
import type { GetChargingProfilesRequestV201 } from "./types/get-charging-profiles-request";
import type { GetChargingProfilesResponseV201 } from "./types/get-charging-profiles-response";
import type { GetCompositeScheduleRequestV201 } from "./types/get-composite-schedule-request";
import type { GetCompositeScheduleResponseV201 } from "./types/get-composite-schedule-response";
import type { GetDisplayMessagesRequestV201 } from "./types/get-display-messages-request";
import type { GetDisplayMessagesResponseV201 } from "./types/get-display-messages-response";
import type { GetInstalledCertificateIdsRequestV201 } from "./types/get-installed-certificate-ids-request";
import type { GetInstalledCertificateIdsResponseV201 } from "./types/get-installed-certificate-ids-response";
import type { GetLocalListVersionRequestV201 } from "./types/get-local-list-version-request";
import type { GetLocalListVersionResponseV201 } from "./types/get-local-list-version-response";
import type { GetLogRequestV201 } from "./types/get-log-request";
import type { GetLogResponseV201 } from "./types/get-log-response";
import type { GetMonitoringReportRequestV201 } from "./types/get-monitoring-report-request";
import type { GetMonitoringReportResponseV201 } from "./types/get-monitoring-report-response";
import type { GetReportRequestV201 } from "./types/get-report-request";
import type { GetReportResponseV201 } from "./types/get-report-response";
import type { GetTransactionStatusRequestV201 } from "./types/get-transaction-status-request";
import type { GetTransactionStatusResponseV201 } from "./types/get-transaction-status-response";
import type { GetVariablesRequestV201 } from "./types/get-variables-request";
import type { GetVariablesResponseV201 } from "./types/get-variables-response";
import type { HeartbeatRequestV201 } from "./types/heartbeat-request";
import type { HeartbeatResponseV201 } from "./types/heartbeat-response";
import type { InstallCertificateRequestV201 } from "./types/install-certificate-request";
import type { InstallCertificateResponseV201 } from "./types/install-certificate-response";
import type { LogStatusNotificationRequestV201 } from "./types/log-status-notification-request";
import type { LogStatusNotificationResponseV201 } from "./types/log-status-notification-response";
import type { MeterValuesRequestV201 } from "./types/meter-values-request";
import type { MeterValuesResponseV201 } from "./types/meter-values-response";
import type { NotifyChargingLimitRequestV201 } from "./types/notify-charging-limit-request";
import type { NotifyChargingLimitResponseV201 } from "./types/notify-charging-limit-response";
import type { NotifyCustomerInformationRequestV201 } from "./types/notify-customer-information-request";
import type { NotifyCustomerInformationResponseV201 } from "./types/notify-customer-information-response";
import type { NotifyDisplayMessagesRequestV201 } from "./types/notify-display-messages-request";
import type { NotifyDisplayMessagesResponseV201 } from "./types/notify-display-messages-response";
import type { NotifyEVChargingNeedsRequestV201 } from "./types/notify-ev-charging-needs-request";
import type { NotifyEVChargingNeedsResponseV201 } from "./types/notify-ev-charging-needs-response";
import type { NotifyEVChargingScheduleRequestV201 } from "./types/notify-ev-charging-schedule-request";
import type { NotifyEVChargingScheduleResponseV201 } from "./types/notify-ev-charging-schedule-response";
import type { NotifyEventRequestV201 } from "./types/notify-event-request";
import type { NotifyEventResponseV201 } from "./types/notify-event-response";
import type { NotifyMonitoringReportRequestV201 } from "./types/notify-monitoring-report-request";
import type { NotifyMonitoringReportResponseV201 } from "./types/notify-monitoring-report-response";
import type { NotifyReportRequestV201 } from "./types/notify-report-request";
import type { NotifyReportResponseV201 } from "./types/notify-report-response";
import type { PublishFirmwareRequestV201 } from "./types/publish-firmware-request";
import type { PublishFirmwareResponseV201 } from "./types/publish-firmware-response";
import type { PublishFirmwareStatusNotificationRequestV201 } from "./types/publish-firmware-status-notification-request";
import type { PublishFirmwareStatusNotificationResponseV201 } from "./types/publish-firmware-status-notification-response";
import type { ReportChargingProfilesRequestV201 } from "./types/report-charging-profiles-request";
import type { ReportChargingProfilesResponseV201 } from "./types/report-charging-profiles-response";
import type { RequestStartTransactionRequestV201 } from "./types/request-start-transaction-request";
import type { RequestStartTransactionResponseV201 } from "./types/request-start-transaction-response";
import type { RequestStopTransactionRequestV201 } from "./types/request-stop-transaction-request";
import type { RequestStopTransactionResponseV201 } from "./types/request-stop-transaction-response";
import type { ReservationStatusUpdateRequestV201 } from "./types/reservation-status-update-request";
import type { ReservationStatusUpdateResponseV201 } from "./types/reservation-status-update-response";
import type { ReserveNowRequestV201 } from "./types/reserve-now-request";
import type { ReserveNowResponseV201 } from "./types/reserve-now-response";
import type { ResetRequestV201 } from "./types/reset-request";
import type { ResetResponseV201 } from "./types/reset-response";
import type { SecurityEventNotificationRequestV201 } from "./types/security-event-notification-request";
import type { SecurityEventNotificationResponseV201 } from "./types/security-event-notification-response";
import type { SendLocalListRequestV201 } from "./types/send-local-list-request";
import type { SendLocalListResponseV201 } from "./types/send-local-list-response";
import type { SetChargingProfileRequestV201 } from "./types/set-charging-profile-request";
import type { SetChargingProfileResponseV201 } from "./types/set-charging-profile-response";
import type { SetDisplayMessageRequestV201 } from "./types/set-display-message-request";
import type { SetDisplayMessageResponseV201 } from "./types/set-display-message-response";
import type { SetMonitoringBaseRequestV201 } from "./types/set-monitoring-base-request";
import type { SetMonitoringBaseResponseV201 } from "./types/set-monitoring-base-response";
import type { SetMonitoringLevelRequestV201 } from "./types/set-monitoring-level-request";
import type { SetMonitoringLevelResponseV201 } from "./types/set-monitoring-level-response";
import type { SetNetworkProfileRequestV201 } from "./types/set-network-profile-request";
import type { SetNetworkProfileResponseV201 } from "./types/set-network-profile-response";
import type { SetVariableMonitoringRequestV201 } from "./types/set-variable-monitoring-request";
import type { SetVariableMonitoringResponseV201 } from "./types/set-variable-monitoring-response";
import type { SetVariablesRequestV201 } from "./types/set-variables-request";
import type { SetVariablesResponseV201 } from "./types/set-variables-response";
import type { SignCertificateRequestV201 } from "./types/sign-certificate-request";
import type { SignCertificateResponseV201 } from "./types/sign-certificate-response";
import type { StatusNotificationRequestV201 } from "./types/status-notification-request";
import type { StatusNotificationResponseV201 } from "./types/status-notification-response";
import type { TransactionEventRequestV201 } from "./types/transaction-event-request";
import type { TransactionEventResponseV201 } from "./types/transaction-event-response";
import type { TriggerMessageRequestV201 } from "./types/trigger-message-request";
import type { TriggerMessageResponseV201 } from "./types/trigger-message-response";
import type { UnlockConnectorRequestV201 } from "./types/unlock-connector-request";
import type { UnlockConnectorResponseV201 } from "./types/unlock-connector-response";
import type { UnpublishFirmwareRequestV201 } from "./types/unpublish-firmware-request";
import type { UnpublishFirmwareResponseV201 } from "./types/unpublish-firmware-response";
import type { UpdateFirmwareRequestV201 } from "./types/update-firmware-request";
import type { UpdateFirmwareResponseV201 } from "./types/update-firmware-response";

export const isValidAuthorizeRequestV201 = (
  data: unknown,
): data is AuthorizeRequestV201 =>
  validateOCPPPayload(v201Schemas.authorizeRequestV201, data);

export const isValidAuthorizeResponseV201 = (
  data: unknown,
): data is AuthorizeResponseV201 =>
  validateOCPPPayload(v201Schemas.authorizeResponseV201, data);

export const isValidBootNotificationRequestV201 = (
  data: unknown,
): data is BootNotificationRequestV201 =>
  validateOCPPPayload(v201Schemas.bootNotificationRequestV201, data);

export const isValidBootNotificationResponseV201 = (
  data: unknown,
): data is BootNotificationResponseV201 =>
  validateOCPPPayload(v201Schemas.bootNotificationResponseV201, data);

export const isValidCancelReservationRequestV201 = (
  data: unknown,
): data is CancelReservationRequestV201 =>
  validateOCPPPayload(v201Schemas.cancelReservationRequestV201, data);

export const isValidCancelReservationResponseV201 = (
  data: unknown,
): data is CancelReservationResponseV201 =>
  validateOCPPPayload(v201Schemas.cancelReservationResponseV201, data);

export const isValidCertificateSignedRequestV201 = (
  data: unknown,
): data is CertificateSignedRequestV201 =>
  validateOCPPPayload(v201Schemas.certificateSignedRequestV201, data);

export const isValidCertificateSignedResponseV201 = (
  data: unknown,
): data is CertificateSignedResponseV201 =>
  validateOCPPPayload(v201Schemas.certificateSignedResponseV201, data);

export const isValidChangeAvailabilityRequestV201 = (
  data: unknown,
): data is ChangeAvailabilityRequestV201 =>
  validateOCPPPayload(v201Schemas.changeAvailabilityRequestV201, data);

export const isValidChangeAvailabilityResponseV201 = (
  data: unknown,
): data is ChangeAvailabilityResponseV201 =>
  validateOCPPPayload(v201Schemas.changeAvailabilityResponseV201, data);

export const isValidClearCacheRequestV201 = (
  data: unknown,
): data is ClearCacheRequestV201 =>
  validateOCPPPayload(v201Schemas.clearCacheRequestV201, data);

export const isValidClearCacheResponseV201 = (
  data: unknown,
): data is ClearCacheResponseV201 =>
  validateOCPPPayload(v201Schemas.clearCacheResponseV201, data);

export const isValidClearChargingProfileRequestV201 = (
  data: unknown,
): data is ClearChargingProfileRequestV201 =>
  validateOCPPPayload(v201Schemas.clearChargingProfileRequestV201, data);

export const isValidClearChargingProfileResponseV201 = (
  data: unknown,
): data is ClearChargingProfileResponseV201 =>
  validateOCPPPayload(v201Schemas.clearChargingProfileResponseV201, data);

export const isValidClearDisplayMessageRequestV201 = (
  data: unknown,
): data is ClearDisplayMessageRequestV201 =>
  validateOCPPPayload(v201Schemas.clearDisplayMessageRequestV201, data);

export const isValidClearDisplayMessageResponseV201 = (
  data: unknown,
): data is ClearDisplayMessageResponseV201 =>
  validateOCPPPayload(v201Schemas.clearDisplayMessageResponseV201, data);

export const isValidClearedChargingLimitRequestV201 = (
  data: unknown,
): data is ClearedChargingLimitRequestV201 =>
  validateOCPPPayload(v201Schemas.clearedChargingLimitRequestV201, data);

export const isValidClearedChargingLimitResponseV201 = (
  data: unknown,
): data is ClearedChargingLimitResponseV201 =>
  validateOCPPPayload(v201Schemas.clearedChargingLimitResponseV201, data);

export const isValidClearVariableMonitoringRequestV201 = (
  data: unknown,
): data is ClearVariableMonitoringRequestV201 =>
  validateOCPPPayload(v201Schemas.clearVariableMonitoringRequestV201, data);

export const isValidClearVariableMonitoringResponseV201 = (
  data: unknown,
): data is ClearVariableMonitoringResponseV201 =>
  validateOCPPPayload(v201Schemas.clearVariableMonitoringResponseV201, data);

export const isValidCostUpdatedRequestV201 = (
  data: unknown,
): data is CostUpdatedRequestV201 =>
  validateOCPPPayload(v201Schemas.costUpdatedRequestV201, data);

export const isValidCostUpdatedResponseV201 = (
  data: unknown,
): data is CostUpdatedResponseV201 =>
  validateOCPPPayload(v201Schemas.costUpdatedResponseV201, data);

export const isValidCustomerInformationRequestV201 = (
  data: unknown,
): data is CustomerInformationRequestV201 =>
  validateOCPPPayload(v201Schemas.customerInformationRequestV201, data);

export const isValidCustomerInformationResponseV201 = (
  data: unknown,
): data is CustomerInformationResponseV201 =>
  validateOCPPPayload(v201Schemas.customerInformationResponseV201, data);

export const isValidDataTransferRequestV201 = (
  data: unknown,
): data is DataTransferRequestV201 =>
  validateOCPPPayload(v201Schemas.dataTransferRequestV201, data);

export const isValidDataTransferResponseV201 = (
  data: unknown,
): data is DataTransferResponseV201 =>
  validateOCPPPayload(v201Schemas.dataTransferResponseV201, data);

export const isValidDeleteCertificateRequestV201 = (
  data: unknown,
): data is DeleteCertificateRequestV201 =>
  validateOCPPPayload(v201Schemas.deleteCertificateRequestV201, data);

export const isValidDeleteCertificateResponseV201 = (
  data: unknown,
): data is DeleteCertificateResponseV201 =>
  validateOCPPPayload(v201Schemas.deleteCertificateResponseV201, data);

export const isValidFirmwareStatusNotificationRequestV201 = (
  data: unknown,
): data is FirmwareStatusNotificationRequestV201 =>
  validateOCPPPayload(v201Schemas.firmwareStatusNotificationRequestV201, data);

export const isValidFirmwareStatusNotificationResponseV201 = (
  data: unknown,
): data is FirmwareStatusNotificationResponseV201 =>
  validateOCPPPayload(v201Schemas.firmwareStatusNotificationResponseV201, data);

export const isValidGet15118EVCertificateRequestV201 = (
  data: unknown,
): data is Get15118EVCertificateRequestV201 =>
  validateOCPPPayload(v201Schemas.get15118EVCertificateRequestV201, data);

export const isValidGet15118EVCertificateResponseV201 = (
  data: unknown,
): data is Get15118EVCertificateResponseV201 =>
  validateOCPPPayload(v201Schemas.get15118EVCertificateResponseV201, data);

export const isValidGetBaseReportRequestV201 = (
  data: unknown,
): data is GetBaseReportRequestV201 =>
  validateOCPPPayload(v201Schemas.getBaseReportRequestV201, data);

export const isValidGetBaseReportResponseV201 = (
  data: unknown,
): data is GetBaseReportResponseV201 =>
  validateOCPPPayload(v201Schemas.getBaseReportResponseV201, data);

export const isValidGetCertificateStatusRequestV201 = (
  data: unknown,
): data is GetCertificateStatusRequestV201 =>
  validateOCPPPayload(v201Schemas.getCertificateStatusRequestV201, data);

export const isValidGetCertificateStatusResponseV201 = (
  data: unknown,
): data is GetCertificateStatusResponseV201 =>
  validateOCPPPayload(v201Schemas.getCertificateStatusResponseV201, data);

export const isValidGetChargingProfilesRequestV201 = (
  data: unknown,
): data is GetChargingProfilesRequestV201 =>
  validateOCPPPayload(v201Schemas.getChargingProfilesRequestV201, data);

export const isValidGetChargingProfilesResponseV201 = (
  data: unknown,
): data is GetChargingProfilesResponseV201 =>
  validateOCPPPayload(v201Schemas.getChargingProfilesResponseV201, data);

export const isValidGetCompositeScheduleRequestV201 = (
  data: unknown,
): data is GetCompositeScheduleRequestV201 =>
  validateOCPPPayload(v201Schemas.getCompositeScheduleRequestV201, data);

export const isValidGetCompositeScheduleResponseV201 = (
  data: unknown,
): data is GetCompositeScheduleResponseV201 =>
  validateOCPPPayload(v201Schemas.getCompositeScheduleResponseV201, data);

export const isValidGetDisplayMessagesRequestV201 = (
  data: unknown,
): data is GetDisplayMessagesRequestV201 =>
  validateOCPPPayload(v201Schemas.getDisplayMessagesRequestV201, data);

export const isValidGetDisplayMessagesResponseV201 = (
  data: unknown,
): data is GetDisplayMessagesResponseV201 =>
  validateOCPPPayload(v201Schemas.getDisplayMessagesResponseV201, data);

export const isValidGetInstalledCertificateIdsRequestV201 = (
  data: unknown,
): data is GetInstalledCertificateIdsRequestV201 =>
  validateOCPPPayload(v201Schemas.getInstalledCertificateIdsRequestV201, data);

export const isValidGetInstalledCertificateIdsResponseV201 = (
  data: unknown,
): data is GetInstalledCertificateIdsResponseV201 =>
  validateOCPPPayload(v201Schemas.getInstalledCertificateIdsResponseV201, data);

export const isValidGetLocalListVersionRequestV201 = (
  data: unknown,
): data is GetLocalListVersionRequestV201 =>
  validateOCPPPayload(v201Schemas.getLocalListVersionRequestV201, data);

export const isValidGetLocalListVersionResponseV201 = (
  data: unknown,
): data is GetLocalListVersionResponseV201 =>
  validateOCPPPayload(v201Schemas.getLocalListVersionResponseV201, data);

export const isValidGetLogRequestV201 = (
  data: unknown,
): data is GetLogRequestV201 =>
  validateOCPPPayload(v201Schemas.getLogRequestV201, data);

export const isValidGetLogResponseV201 = (
  data: unknown,
): data is GetLogResponseV201 =>
  validateOCPPPayload(v201Schemas.getLogResponseV201, data);

export const isValidGetMonitoringReportRequestV201 = (
  data: unknown,
): data is GetMonitoringReportRequestV201 =>
  validateOCPPPayload(v201Schemas.getMonitoringReportRequestV201, data);

export const isValidGetMonitoringReportResponseV201 = (
  data: unknown,
): data is GetMonitoringReportResponseV201 =>
  validateOCPPPayload(v201Schemas.getMonitoringReportResponseV201, data);

export const isValidGetReportRequestV201 = (
  data: unknown,
): data is GetReportRequestV201 =>
  validateOCPPPayload(v201Schemas.getReportRequestV201, data);

export const isValidGetReportResponseV201 = (
  data: unknown,
): data is GetReportResponseV201 =>
  validateOCPPPayload(v201Schemas.getReportResponseV201, data);

export const isValidGetTransactionStatusRequestV201 = (
  data: unknown,
): data is GetTransactionStatusRequestV201 =>
  validateOCPPPayload(v201Schemas.getTransactionStatusRequestV201, data);

export const isValidGetTransactionStatusResponseV201 = (
  data: unknown,
): data is GetTransactionStatusResponseV201 =>
  validateOCPPPayload(v201Schemas.getTransactionStatusResponseV201, data);

export const isValidGetVariablesRequestV201 = (
  data: unknown,
): data is GetVariablesRequestV201 =>
  validateOCPPPayload(v201Schemas.getVariablesRequestV201, data);

export const isValidGetVariablesResponseV201 = (
  data: unknown,
): data is GetVariablesResponseV201 =>
  validateOCPPPayload(v201Schemas.getVariablesResponseV201, data);

export const isValidHeartbeatRequestV201 = (
  data: unknown,
): data is HeartbeatRequestV201 =>
  validateOCPPPayload(v201Schemas.heartbeatRequestV201, data);

export const isValidHeartbeatResponseV201 = (
  data: unknown,
): data is HeartbeatResponseV201 =>
  validateOCPPPayload(v201Schemas.heartbeatResponseV201, data);

export const isValidInstallCertificateRequestV201 = (
  data: unknown,
): data is InstallCertificateRequestV201 =>
  validateOCPPPayload(v201Schemas.installCertificateRequestV201, data);

export const isValidInstallCertificateResponseV201 = (
  data: unknown,
): data is InstallCertificateResponseV201 =>
  validateOCPPPayload(v201Schemas.installCertificateResponseV201, data);

export const isValidLogStatusNotificationRequestV201 = (
  data: unknown,
): data is LogStatusNotificationRequestV201 =>
  validateOCPPPayload(v201Schemas.logStatusNotificationRequestV201, data);

export const isValidLogStatusNotificationResponseV201 = (
  data: unknown,
): data is LogStatusNotificationResponseV201 =>
  validateOCPPPayload(v201Schemas.logStatusNotificationResponseV201, data);

export const isValidMeterValuesRequestV201 = (
  data: unknown,
): data is MeterValuesRequestV201 =>
  validateOCPPPayload(v201Schemas.meterValuesRequestV201, data);

export const isValidMeterValuesResponseV201 = (
  data: unknown,
): data is MeterValuesResponseV201 =>
  validateOCPPPayload(v201Schemas.meterValuesResponseV201, data);

export const isValidNotifyChargingLimitRequestV201 = (
  data: unknown,
): data is NotifyChargingLimitRequestV201 =>
  validateOCPPPayload(v201Schemas.notifyChargingLimitRequestV201, data);

export const isValidNotifyChargingLimitResponseV201 = (
  data: unknown,
): data is NotifyChargingLimitResponseV201 =>
  validateOCPPPayload(v201Schemas.notifyChargingLimitResponseV201, data);

export const isValidNotifyCustomerInformationRequestV201 = (
  data: unknown,
): data is NotifyCustomerInformationRequestV201 =>
  validateOCPPPayload(v201Schemas.notifyCustomerInformationRequestV201, data);

export const isValidNotifyCustomerInformationResponseV201 = (
  data: unknown,
): data is NotifyCustomerInformationResponseV201 =>
  validateOCPPPayload(v201Schemas.notifyCustomerInformationResponseV201, data);

export const isValidNotifyDisplayMessagesRequestV201 = (
  data: unknown,
): data is NotifyDisplayMessagesRequestV201 =>
  validateOCPPPayload(v201Schemas.notifyDisplayMessagesRequestV201, data);

export const isValidNotifyDisplayMessagesResponseV201 = (
  data: unknown,
): data is NotifyDisplayMessagesResponseV201 =>
  validateOCPPPayload(v201Schemas.notifyDisplayMessagesResponseV201, data);

export const isValidNotifyEVChargingNeedsRequestV201 = (
  data: unknown,
): data is NotifyEVChargingNeedsRequestV201 =>
  validateOCPPPayload(v201Schemas.notifyEVChargingNeedsRequestV201, data);

export const isValidNotifyEVChargingNeedsResponseV201 = (
  data: unknown,
): data is NotifyEVChargingNeedsResponseV201 =>
  validateOCPPPayload(v201Schemas.notifyEVChargingNeedsResponseV201, data);

export const isValidNotifyEVChargingScheduleRequestV201 = (
  data: unknown,
): data is NotifyEVChargingScheduleRequestV201 =>
  validateOCPPPayload(v201Schemas.notifyEVChargingScheduleRequestV201, data);

export const isValidNotifyEVChargingScheduleResponseV201 = (
  data: unknown,
): data is NotifyEVChargingScheduleResponseV201 =>
  validateOCPPPayload(v201Schemas.notifyEVChargingScheduleResponseV201, data);

export const isValidNotifyEventRequestV201 = (
  data: unknown,
): data is NotifyEventRequestV201 =>
  validateOCPPPayload(v201Schemas.notifyEventRequestV201, data);

export const isValidNotifyEventResponseV201 = (
  data: unknown,
): data is NotifyEventResponseV201 =>
  validateOCPPPayload(v201Schemas.notifyEventResponseV201, data);

export const isValidNotifyMonitoringReportRequestV201 = (
  data: unknown,
): data is NotifyMonitoringReportRequestV201 =>
  validateOCPPPayload(v201Schemas.notifyMonitoringReportRequestV201, data);

export const isValidNotifyMonitoringReportResponseV201 = (
  data: unknown,
): data is NotifyMonitoringReportResponseV201 =>
  validateOCPPPayload(v201Schemas.notifyMonitoringReportResponseV201, data);

export const isValidNotifyReportRequestV201 = (
  data: unknown,
): data is NotifyReportRequestV201 =>
  validateOCPPPayload(v201Schemas.notifyReportRequestV201, data);

export const isValidNotifyReportResponseV201 = (
  data: unknown,
): data is NotifyReportResponseV201 =>
  validateOCPPPayload(v201Schemas.notifyReportResponseV201, data);

export const isValidPublishFirmwareRequestV201 = (
  data: unknown,
): data is PublishFirmwareRequestV201 =>
  validateOCPPPayload(v201Schemas.publishFirmwareRequestV201, data);

export const isValidPublishFirmwareResponseV201 = (
  data: unknown,
): data is PublishFirmwareResponseV201 =>
  validateOCPPPayload(v201Schemas.publishFirmwareResponseV201, data);

export const isValidPublishFirmwareStatusNotificationRequestV201 = (
  data: unknown,
): data is PublishFirmwareStatusNotificationRequestV201 =>
  validateOCPPPayload(
    v201Schemas.publishFirmwareStatusNotificationRequestV201,
    data,
  );

export const isValidPublishFirmwareStatusNotificationResponseV201 = (
  data: unknown,
): data is PublishFirmwareStatusNotificationResponseV201 =>
  validateOCPPPayload(
    v201Schemas.publishFirmwareStatusNotificationResponseV201,
    data,
  );

export const isValidReportChargingProfilesRequestV201 = (
  data: unknown,
): data is ReportChargingProfilesRequestV201 =>
  validateOCPPPayload(v201Schemas.reportChargingProfilesRequestV201, data);

export const isValidReportChargingProfilesResponseV201 = (
  data: unknown,
): data is ReportChargingProfilesResponseV201 =>
  validateOCPPPayload(v201Schemas.reportChargingProfilesResponseV201, data);

export const isValidRequestStartTransactionRequestV201 = (
  data: unknown,
): data is RequestStartTransactionRequestV201 =>
  validateOCPPPayload(v201Schemas.requestStartTransactionRequestV201, data);

export const isValidRequestStartTransactionResponseV201 = (
  data: unknown,
): data is RequestStartTransactionResponseV201 =>
  validateOCPPPayload(v201Schemas.requestStartTransactionResponseV201, data);

export const isValidRequestStopTransactionRequestV201 = (
  data: unknown,
): data is RequestStopTransactionRequestV201 =>
  validateOCPPPayload(v201Schemas.requestStopTransactionRequestV201, data);

export const isValidRequestStopTransactionResponseV201 = (
  data: unknown,
): data is RequestStopTransactionResponseV201 =>
  validateOCPPPayload(v201Schemas.requestStopTransactionResponseV201, data);

export const isValidReservationStatusUpdateRequestV201 = (
  data: unknown,
): data is ReservationStatusUpdateRequestV201 =>
  validateOCPPPayload(v201Schemas.reservationStatusUpdateRequestV201, data);

export const isValidReservationStatusUpdateResponseV201 = (
  data: unknown,
): data is ReservationStatusUpdateResponseV201 =>
  validateOCPPPayload(v201Schemas.reservationStatusUpdateResponseV201, data);

export const isValidReserveNowRequestV201 = (
  data: unknown,
): data is ReserveNowRequestV201 =>
  validateOCPPPayload(v201Schemas.reserveNowRequestV201, data);

export const isValidReserveNowResponseV201 = (
  data: unknown,
): data is ReserveNowResponseV201 =>
  validateOCPPPayload(v201Schemas.reserveNowResponseV201, data);

export const isValidResetRequestV201 = (
  data: unknown,
): data is ResetRequestV201 =>
  validateOCPPPayload(v201Schemas.resetRequestV201, data);

export const isValidResetResponseV201 = (
  data: unknown,
): data is ResetResponseV201 =>
  validateOCPPPayload(v201Schemas.resetResponseV201, data);

export const isValidSecurityEventNotificationRequestV201 = (
  data: unknown,
): data is SecurityEventNotificationRequestV201 =>
  validateOCPPPayload(v201Schemas.securityEventNotificationRequestV201, data);

export const isValidSecurityEventNotificationResponseV201 = (
  data: unknown,
): data is SecurityEventNotificationResponseV201 =>
  validateOCPPPayload(v201Schemas.securityEventNotificationResponseV201, data);

export const isValidSendLocalListRequestV201 = (
  data: unknown,
): data is SendLocalListRequestV201 =>
  validateOCPPPayload(v201Schemas.sendLocalListRequestV201, data);

export const isValidSendLocalListResponseV201 = (
  data: unknown,
): data is SendLocalListResponseV201 =>
  validateOCPPPayload(v201Schemas.sendLocalListResponseV201, data);

export const isValidSetChargingProfileRequestV201 = (
  data: unknown,
): data is SetChargingProfileRequestV201 =>
  validateOCPPPayload(v201Schemas.setChargingProfileRequestV201, data);

export const isValidSetChargingProfileResponseV201 = (
  data: unknown,
): data is SetChargingProfileResponseV201 =>
  validateOCPPPayload(v201Schemas.setChargingProfileResponseV201, data);

export const isValidSetDisplayMessageRequestV201 = (
  data: unknown,
): data is SetDisplayMessageRequestV201 =>
  validateOCPPPayload(v201Schemas.setDisplayMessageRequestV201, data);

export const isValidSetDisplayMessageResponseV201 = (
  data: unknown,
): data is SetDisplayMessageResponseV201 =>
  validateOCPPPayload(v201Schemas.setDisplayMessageResponseV201, data);

export const isValidSetMonitoringBaseRequestV201 = (
  data: unknown,
): data is SetMonitoringBaseRequestV201 =>
  validateOCPPPayload(v201Schemas.setMonitoringBaseRequestV201, data);

export const isValidSetMonitoringBaseResponseV201 = (
  data: unknown,
): data is SetMonitoringBaseResponseV201 =>
  validateOCPPPayload(v201Schemas.setMonitoringBaseResponseV201, data);

export const isValidSetMonitoringLevelRequestV201 = (
  data: unknown,
): data is SetMonitoringLevelRequestV201 =>
  validateOCPPPayload(v201Schemas.setMonitoringLevelRequestV201, data);

export const isValidSetMonitoringLevelResponseV201 = (
  data: unknown,
): data is SetMonitoringLevelResponseV201 =>
  validateOCPPPayload(v201Schemas.setMonitoringLevelResponseV201, data);

export const isValidSetNetworkProfileRequestV201 = (
  data: unknown,
): data is SetNetworkProfileRequestV201 =>
  validateOCPPPayload(v201Schemas.setNetworkProfileRequestV201, data);

export const isValidSetNetworkProfileResponseV201 = (
  data: unknown,
): data is SetNetworkProfileResponseV201 =>
  validateOCPPPayload(v201Schemas.setNetworkProfileResponseV201, data);

export const isValidSetVariableMonitoringRequestV201 = (
  data: unknown,
): data is SetVariableMonitoringRequestV201 =>
  validateOCPPPayload(v201Schemas.setVariableMonitoringRequestV201, data);

export const isValidSetVariableMonitoringResponseV201 = (
  data: unknown,
): data is SetVariableMonitoringResponseV201 =>
  validateOCPPPayload(v201Schemas.setVariableMonitoringResponseV201, data);

export const isValidSetVariablesRequestV201 = (
  data: unknown,
): data is SetVariablesRequestV201 =>
  validateOCPPPayload(v201Schemas.setVariablesRequestV201, data);

export const isValidSetVariablesResponseV201 = (
  data: unknown,
): data is SetVariablesResponseV201 =>
  validateOCPPPayload(v201Schemas.setVariablesResponseV201, data);

export const isValidSignCertificateRequestV201 = (
  data: unknown,
): data is SignCertificateRequestV201 =>
  validateOCPPPayload(v201Schemas.signCertificateRequestV201, data);

export const isValidSignCertificateResponseV201 = (
  data: unknown,
): data is SignCertificateResponseV201 =>
  validateOCPPPayload(v201Schemas.signCertificateResponseV201, data);

export const isValidStatusNotificationRequestV201 = (
  data: unknown,
): data is StatusNotificationRequestV201 =>
  validateOCPPPayload(v201Schemas.statusNotificationRequestV201, data);

export const isValidStatusNotificationResponseV201 = (
  data: unknown,
): data is StatusNotificationResponseV201 =>
  validateOCPPPayload(v201Schemas.statusNotificationResponseV201, data);

export const isValidTransactionEventRequestV201 = (
  data: unknown,
): data is TransactionEventRequestV201 =>
  validateOCPPPayload(v201Schemas.transactionEventRequestV201, data);

export const isValidTransactionEventResponseV201 = (
  data: unknown,
): data is TransactionEventResponseV201 =>
  validateOCPPPayload(v201Schemas.transactionEventResponseV201, data);

export const isValidTriggerMessageRequestV201 = (
  data: unknown,
): data is TriggerMessageRequestV201 =>
  validateOCPPPayload(v201Schemas.triggerMessageRequestV201, data);

export const isValidTriggerMessageResponseV201 = (
  data: unknown,
): data is TriggerMessageResponseV201 =>
  validateOCPPPayload(v201Schemas.triggerMessageResponseV201, data);

export const isValidUnlockConnectorRequestV201 = (
  data: unknown,
): data is UnlockConnectorRequestV201 =>
  validateOCPPPayload(v201Schemas.unlockConnectorRequestV201, data);

export const isValidUnlockConnectorResponseV201 = (
  data: unknown,
): data is UnlockConnectorResponseV201 =>
  validateOCPPPayload(v201Schemas.unlockConnectorResponseV201, data);

export const isValidUnpublishFirmwareRequestV201 = (
  data: unknown,
): data is UnpublishFirmwareRequestV201 =>
  validateOCPPPayload(v201Schemas.unpublishFirmwareRequestV201, data);

export const isValidUnpublishFirmwareResponseV201 = (
  data: unknown,
): data is UnpublishFirmwareResponseV201 =>
  validateOCPPPayload(v201Schemas.unpublishFirmwareResponseV201, data);

export const isValidUpdateFirmwareRequestV201 = (
  data: unknown,
): data is UpdateFirmwareRequestV201 =>
  validateOCPPPayload(v201Schemas.updateFirmwareRequestV201, data);

export const isValidUpdateFirmwareResponseV201 = (
  data: unknown,
): data is UpdateFirmwareResponseV201 =>
  validateOCPPPayload(v201Schemas.updateFirmwareResponseV201, data);

export const actionValidatorV201: Record<string, (data: unknown) => boolean> = {
  Authorize: isValidAuthorizeRequestV201,
  BootNotification: isValidBootNotificationRequestV201,
  CancelReservation: isValidCancelReservationRequestV201,
  CertificateSigned: isValidCertificateSignedRequestV201,
  ChangeAvailability: isValidChangeAvailabilityRequestV201,
  ClearCache: isValidClearCacheRequestV201,
  ClearChargingProfile: isValidClearChargingProfileRequestV201,
  ClearDisplayMessage: isValidClearDisplayMessageRequestV201,
  ClearedChargingLimit: isValidClearedChargingLimitRequestV201,
  ClearVariableMonitoring: isValidClearVariableMonitoringRequestV201,
  CostUpdated: isValidCostUpdatedRequestV201,
  CustomerInformation: isValidCustomerInformationRequestV201,
  DataTransfer: isValidDataTransferRequestV201,
  DeleteCertificate: isValidDeleteCertificateRequestV201,
  FirmwareStatusNotification: isValidFirmwareStatusNotificationRequestV201,
  Get15118EVCertificate: isValidGet15118EVCertificateRequestV201,
  GetBaseReport: isValidGetBaseReportRequestV201,
  GetCertificateStatus: isValidGetCertificateStatusRequestV201,
  GetChargingProfiles: isValidGetChargingProfilesRequestV201,
  GetCompositeSchedule: isValidGetCompositeScheduleRequestV201,
  GetDisplayMessages: isValidGetDisplayMessagesRequestV201,
  GetInstalledCertificateIds: isValidGetInstalledCertificateIdsRequestV201,
  GetLocalListVersion: isValidGetLocalListVersionRequestV201,
  GetLog: isValidGetLogRequestV201,
  GetMonitoringReport: isValidGetMonitoringReportRequestV201,
  GetReport: isValidGetReportRequestV201,
  GetTransactionStatus: isValidGetTransactionStatusRequestV201,
  GetVariables: isValidGetVariablesRequestV201,
  Heartbeat: isValidHeartbeatRequestV201,
  InstallCertificate: isValidInstallCertificateRequestV201,
  LogStatusNotification: isValidLogStatusNotificationRequestV201,
  MeterValues: isValidMeterValuesRequestV201,
  NotifyChargingLimit: isValidNotifyChargingLimitRequestV201,
  NotifyCustomerInformation: isValidNotifyCustomerInformationRequestV201,
  NotifyDisplayMessages: isValidNotifyDisplayMessagesRequestV201,
  NotifyEVChargingNeeds: isValidNotifyEVChargingNeedsRequestV201,
  NotifyEVChargingSchedule: isValidNotifyEVChargingScheduleRequestV201,
  NotifyEvent: isValidNotifyEventRequestV201,
  NotifyMonitoringReport: isValidNotifyMonitoringReportRequestV201,
  NotifyReport: isValidNotifyReportRequestV201,
  PublishFirmware: isValidPublishFirmwareRequestV201,
  PublishFirmwareStatusNotification:
    isValidPublishFirmwareStatusNotificationRequestV201,
  ReportChargingProfiles: isValidReportChargingProfilesRequestV201,
  RequestStartTransaction: isValidRequestStartTransactionRequestV201,
  RequestStopTransaction: isValidRequestStopTransactionRequestV201,
  ReservationStatusUpdate: isValidReservationStatusUpdateRequestV201,
  ReserveNow: isValidReserveNowRequestV201,
  Reset: isValidResetRequestV201,
  SecurityEventNotification: isValidSecurityEventNotificationRequestV201,
  SendLocalList: isValidSendLocalListRequestV201,
  SetChargingProfile: isValidSetChargingProfileRequestV201,
  SetDisplayMessage: isValidSetDisplayMessageRequestV201,
  SetMonitoringBase: isValidSetMonitoringBaseRequestV201,
  SetMonitoringLevel: isValidSetMonitoringLevelRequestV201,
  SetNetworkProfile: isValidSetNetworkProfileRequestV201,
  SetVariableMonitoring: isValidSetVariableMonitoringRequestV201,
  SetVariables: isValidSetVariablesRequestV201,
  SignCertificate: isValidSignCertificateRequestV201,
  StatusNotification: isValidStatusNotificationRequestV201,
  TransactionEvent: isValidTransactionEventRequestV201,
  TriggerMessage: isValidTriggerMessageRequestV201,
  UnlockConnector: isValidUnlockConnectorRequestV201,
  UnpublishFirmware: isValidUnpublishFirmwareRequestV201,
  UpdateFirmware: isValidUpdateFirmwareRequestV201,
};
