// Generated by scripts/generate-ocpp.ts. Do not edit.

export type IdTokenEnumType =
  | "Central"
  | "eMAID"
  | "ISO14443"
  | "ISO15693"
  | "KeyCode"
  | "Local"
  | "MacAddress"
  | "NoAuthorization";
export type HashAlgorithmEnumType = "SHA256" | "SHA384" | "SHA512";

export interface AuthorizeRequestV201 {
  customData?: CustomDataType;
  idToken: IdTokenType;
  certificate?: string;
  iso15118CertificateHashData?:
    | [OCSPRequestDataType]
    | [OCSPRequestDataType, OCSPRequestDataType]
    | [OCSPRequestDataType, OCSPRequestDataType, OCSPRequestDataType]
    | [
        OCSPRequestDataType,
        OCSPRequestDataType,
        OCSPRequestDataType,
        OCSPRequestDataType,
      ];
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface IdTokenType {
  customData?: CustomDataType;
  additionalInfo?: [AdditionalInfoType, ...AdditionalInfoType[]];
  idToken: string;
  type: IdTokenEnumType;
}
export interface AdditionalInfoType {
  customData?: CustomDataType;
  additionalIdToken: string;
  type: string;
}
export interface OCSPRequestDataType {
  customData?: CustomDataType;
  hashAlgorithm: HashAlgorithmEnumType;
  issuerNameHash: string;
  issuerKeyHash: string;
  serialNumber: string;
  responderURL: string;
}
