// Generated by scripts/generate-ocpp.ts. Do not edit.

export type AuthorizationStatusEnumType =
  | "Accepted"
  | "Blocked"
  | "ConcurrentTx"
  | "Expired"
  | "Invalid"
  | "NoCredit"
  | "NotAllowedTypeEVSE"
  | "NotAtThisLocation"
  | "NotAtThisTime"
  | "Unknown";
export type IdTokenEnumType =
  | "Central"
  | "eMAID"
  | "ISO14443"
  | "ISO15693"
  | "KeyCode"
  | "Local"
  | "MacAddress"
  | "NoAuthorization";
export type MessageFormatEnumType = "ASCII" | "HTML" | "URI" | "UTF8";
export type AuthorizeCertificateStatusEnumType =
  | "Accepted"
  | "SignatureError"
  | "CertificateExpired"
  | "CertificateRevoked"
  | "NoCertificateAvailable"
  | "CertChainError"
  | "ContractCancelled";

export interface AuthorizeResponseV201 {
  customData?: CustomDataType;
  idTokenInfo: IdTokenInfoType;
  certificateStatus?: AuthorizeCertificateStatusEnumType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface IdTokenInfoType {
  customData?: CustomDataType;
  status: AuthorizationStatusEnumType;
  cacheExpiryDateTime?: string;
  chargingPriority?: number;
  language1?: string;
  evseId?: [number, ...number[]];
  groupIdToken?: IdTokenType;
  language2?: string;
  personalMessage?: MessageContentType;
}
export interface IdTokenType {
  customData?: CustomDataType;
  additionalInfo?: [AdditionalInfoType, ...AdditionalInfoType[]];
  idToken: string;
  type: IdTokenEnumType;
}
export interface AdditionalInfoType {
  customData?: CustomDataType;
  additionalIdToken: string;
  type: string;
}
export interface MessageContentType {
  customData?: CustomDataType;
  format: MessageFormatEnumType;
  language?: string;
  content: string;
}
