// Generated by scripts/generate-ocpp.ts. Do not edit.

export type CancelReservationStatusEnumType = "Accepted" | "Rejected";

export interface CancelReservationResponseV201 {
  customData?: CustomDataType;
  status: CancelReservationStatusEnumType;
  statusInfo?: StatusInfoType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface StatusInfoType {
  customData?: CustomDataType;
  reasonCode: string;
  additionalInfo?: string;
}
