// Generated by scripts/generate-ocpp.ts. Do not edit.

export type CertificateSigningUseEnumType =
  "ChargingStationCertificate" | "V2GCertificate";

export interface CertificateSignedRequestV201 {
  customData?: CustomDataType;
  certificateChain: string;
  certificateType?: CertificateSigningUseEnumType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
