// Generated by scripts/generate-ocpp.ts. Do not edit.

export type CertificateSignedStatusEnumType = "Accepted" | "Rejected";

export interface CertificateSignedResponseV201 {
  customData?: CustomDataType;
  status: CertificateSignedStatusEnumType;
  statusInfo?: StatusInfoType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface StatusInfoType {
  customData?: CustomDataType;
  reasonCode: string;
  additionalInfo?: string;
}
