// Generated by scripts/generate-ocpp.ts. Do not edit.

export type OperationalStatusEnumType = "Inoperative" | "Operative";

export interface ChangeAvailabilityRequestV201 {
  customData?: CustomDataType;
  evse?: EVSEType;
  operationalStatus: OperationalStatusEnumType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface EVSEType {
  customData?: CustomDataType;
  id: number;
  connectorId?: number;
}
