// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ChangeAvailabilityStatusEnumType =
  | "Accepted"
  | "Rejected"
  | "Scheduled";

export interface ChangeAvailabilityResponseV201 {
  customData?: CustomDataType;
  status: ChangeAvailabilityStatusEnumType;
  statusInfo?: StatusInfoType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface StatusInfoType {
  customData?: CustomDataType;
  reasonCode: string;
  additionalInfo?: string;
}
