// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ClearCacheStatusEnumType = "Accepted" | "Rejected";

export interface ClearCacheResponseV201 {
  customData?: CustomDataType;
  status: ClearCacheStatusEnumType;
  statusInfo?: StatusInfoType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface StatusInfoType {
  customData?: CustomDataType;
  reasonCode: string;
  additionalInfo?: string;
}
