// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface ClearDisplayMessageRequestV201 {
  customData?: CustomDataType;
  id: number;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
