// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ClearMessageStatusEnumType = "Accepted" | "Unknown";

export interface ClearDisplayMessageResponseV201 {
  customData?: CustomDataType;
  status: ClearMessageStatusEnumType;
  statusInfo?: StatusInfoType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface StatusInfoType {
  customData?: CustomDataType;
  reasonCode: string;
  additionalInfo?: string;
}
