// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ChargingProfilePurposeEnumType =
  | "ChargingStationExternalConstraints"
  | "ChargingStationMaxProfile"
  | "TxDefaultProfile"
  | "TxProfile";

export interface ClearChargingProfileRequestV201 {
  customData?: CustomDataType;
  chargingProfileId?: number;
  chargingProfileCriteria?: ClearChargingProfileType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface ClearChargingProfileType {
  customData?: CustomDataType;
  evseId?: number;
  chargingProfilePurpose?: ChargingProfilePurposeEnumType;
  stackLevel?: number;
}
