// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ClearMonitoringStatusEnumType =
  | "Accepted"
  | "Rejected"
  | "NotFound";

export interface ClearVariableMonitoringResponseV201 {
  customData?: CustomDataType;
  clearMonitoringResult: [
    ClearMonitoringResultType,
    ...ClearMonitoringResultType[],
  ];
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface ClearMonitoringResultType {
  customData?: CustomDataType;
  status: ClearMonitoringStatusEnumType;
  id: number;
  statusInfo?: StatusInfoType;
}
export interface StatusInfoType {
  customData?: CustomDataType;
  reasonCode: string;
  additionalInfo?: string;
}
