// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface CostUpdatedRequestV201 {
  customData?: CustomDataType;
  totalCost: number;
  transactionId: string;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
