// Generated by scripts/generate-ocpp.ts. Do not edit.

export type HashAlgorithmEnumType = "SHA256" | "SHA384" | "SHA512";
export type IdTokenEnumType =
  | "Central"
  | "eMAID"
  | "ISO14443"
  | "ISO15693"
  | "KeyCode"
  | "Local"
  | "MacAddress"
  | "NoAuthorization";

export interface CustomerInformationRequestV201 {
  customData?: CustomDataType;
  customerCertificate?: CertificateHashDataType;
  idToken?: IdTokenType;
  requestId: number;
  report: boolean;
  clear: boolean;
  customerIdentifier?: string;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface CertificateHashDataType {
  customData?: CustomDataType;
  hashAlgorithm: HashAlgorithmEnumType;
  issuerNameHash: string;
  issuerKeyHash: string;
  serialNumber: string;
}
export interface IdTokenType {
  customData?: CustomDataType;
  additionalInfo?: [AdditionalInfoType, ...AdditionalInfoType[]];
  idToken: string;
  type: IdTokenEnumType;
}
export interface AdditionalInfoType {
  customData?: CustomDataType;
  additionalIdToken: string;
  type: string;
}
