// Generated by scripts/generate-ocpp.ts. Do not edit.

export type CustomerInformationStatusEnumType =
  "Accepted" | "Rejected" | "Invalid";

export interface CustomerInformationResponseV201 {
  customData?: CustomDataType;
  status: CustomerInformationStatusEnumType;
  statusInfo?: StatusInfoType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface StatusInfoType {
  customData?: CustomDataType;
  reasonCode: string;
  additionalInfo?: string;
}
