// Generated by scripts/generate-ocpp.ts. Do not edit.

export type DeleteCertificateStatusEnumType =
  | "Accepted"
  | "Failed"
  | "NotFound";

export interface DeleteCertificateResponseV201 {
  customData?: CustomDataType;
  status: DeleteCertificateStatusEnumType;
  statusInfo?: StatusInfoType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface StatusInfoType {
  customData?: CustomDataType;
  reasonCode: string;
  additionalInfo?: string;
}
