// Generated by scripts/generate-ocpp.ts. Do not edit.

export type FirmwareStatusEnumType =
  | "Downloaded"
  | "DownloadFailed"
  | "Downloading"
  | "DownloadScheduled"
  | "DownloadPaused"
  | "Idle"
  | "InstallationFailed"
  | "Installing"
  | "Installed"
  | "InstallRebooting"
  | "InstallScheduled"
  | "InstallVerificationFailed"
  | "InvalidSignature"
  | "SignatureVerified";

export interface FirmwareStatusNotificationRequestV201 {
  customData?: CustomDataType;
  status: FirmwareStatusEnumType;
  requestId?: number;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
