// Generated by scripts/generate-ocpp.ts. Do not edit.

export type MonitoringCriterionEnumType =
  | "ThresholdMonitoring"
  | "DeltaMonitoring"
  | "PeriodicMonitoring";

export interface GetMonitoringReportRequestV201 {
  customData?: CustomDataType;
  componentVariable?: [ComponentVariableType, ...ComponentVariableType[]];
  requestId: number;
  monitoringCriteria?:
    | [MonitoringCriterionEnumType]
    | [MonitoringCriterionEnumType, MonitoringCriterionEnumType]
    | [
        MonitoringCriterionEnumType,
        MonitoringCriterionEnumType,
        MonitoringCriterionEnumType,
      ];
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface ComponentVariableType {
  customData?: CustomDataType;
  component: ComponentType;
  variable?: VariableType;
}
export interface ComponentType {
  customData?: CustomDataType;
  evse?: EVSEType;
  name: string;
  instance?: string;
}
export interface EVSEType {
  customData?: CustomDataType;
  id: number;
  connectorId?: number;
}
export interface VariableType {
  customData?: CustomDataType;
  name: string;
  instance?: string;
}
