// Generated by scripts/generate-ocpp.ts. Do not edit.

export type GetChargingProfileStatusEnumType = "Accepted" | "NoProfiles";

export interface GetChargingProfilesResponseV201 {
  customData?: CustomDataType;
  status: GetChargingProfileStatusEnumType;
  statusInfo?: StatusInfoType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface StatusInfoType {
  customData?: CustomDataType;
  reasonCode: string;
  additionalInfo?: string;
}
