// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ComponentCriterionEnumType =
  "Active" | "Available" | "Enabled" | "Problem";

export interface GetReportRequestV201 {
  customData?: CustomDataType;
  componentVariable?: [ComponentVariableType, ...ComponentVariableType[]];
  requestId: number;
  componentCriteria?:
    | [ComponentCriterionEnumType]
    | [ComponentCriterionEnumType, ComponentCriterionEnumType]
    | [
        ComponentCriterionEnumType,
        ComponentCriterionEnumType,
        ComponentCriterionEnumType,
      ]
    | [
        ComponentCriterionEnumType,
        ComponentCriterionEnumType,
        ComponentCriterionEnumType,
        ComponentCriterionEnumType,
      ];
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface ComponentVariableType {
  customData?: CustomDataType;
  component: ComponentType;
  variable?: VariableType;
}
export interface ComponentType {
  customData?: CustomDataType;
  evse?: EVSEType;
  name: string;
  instance?: string;
}
export interface EVSEType {
  customData?: CustomDataType;
  id: number;
  connectorId?: number;
}
export interface VariableType {
  customData?: CustomDataType;
  name: string;
  instance?: string;
}
