// Generated by scripts/generate-ocpp.ts. Do not edit.

export type GetCertificateStatusEnumType = "Accepted" | "Failed";

export interface GetCertificateStatusResponseV201 {
  customData?: CustomDataType;
  status: GetCertificateStatusEnumType;
  statusInfo?: StatusInfoType;
  ocspResult?: string;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface StatusInfoType {
  customData?: CustomDataType;
  reasonCode: string;
  additionalInfo?: string;
}
