// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ChargingProfilePurposeEnumType =
  | "ChargingStationExternalConstraints"
  | "ChargingStationMaxProfile"
  | "TxDefaultProfile"
  | "TxProfile";
export type ChargingLimitSourceEnumType = "EMS" | "Other" | "SO" | "CSO";

export interface GetChargingProfilesRequestV201 {
  customData?: CustomDataType;
  requestId: number;
  evseId?: number;
  chargingProfile: ChargingProfileCriterionType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface ChargingProfileCriterionType {
  customData?: CustomDataType;
  chargingProfilePurpose?: ChargingProfilePurposeEnumType;
  stackLevel?: number;
  chargingProfileId?: [number, ...number[]];
  chargingLimitSource?:
    | [ChargingLimitSourceEnumType]
    | [ChargingLimitSourceEnumType, ChargingLimitSourceEnumType]
    | [
        ChargingLimitSourceEnumType,
        ChargingLimitSourceEnumType,
        ChargingLimitSourceEnumType,
      ]
    | [
        ChargingLimitSourceEnumType,
        ChargingLimitSourceEnumType,
        ChargingLimitSourceEnumType,
        ChargingLimitSourceEnumType,
      ];
}
