// Generated by scripts/generate-ocpp.ts. Do not edit.

export type GenericDeviceModelStatusEnumType =
  "Accepted" | "Rejected" | "NotSupported" | "EmptyResultSet";

export interface GetBaseReportResponseV201 {
  customData?: CustomDataType;
  status: GenericDeviceModelStatusEnumType;
  statusInfo?: StatusInfoType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface StatusInfoType {
  customData?: CustomDataType;
  reasonCode: string;
  additionalInfo?: string;
}
