// Generated by scripts/generate-ocpp.ts. Do not edit.

export type MessagePriorityEnumType = "AlwaysFront" | "InFront" | "NormalCycle";
export type MessageStateEnumType =
  "Charging" | "Faulted" | "Idle" | "Unavailable";

export interface GetDisplayMessagesRequestV201 {
  customData?: CustomDataType;
  id?: [number, ...number[]];
  requestId: number;
  priority?: MessagePriorityEnumType;
  state?: MessageStateEnumType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
