// Generated by scripts/generate-ocpp.ts. Do not edit.

export type LogStatusEnumType = "Accepted" | "Rejected" | "AcceptedCanceled";

export interface GetLogResponseV201 {
  customData?: CustomDataType;
  status: LogStatusEnumType;
  statusInfo?: StatusInfoType;
  filename?: string;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface StatusInfoType {
  customData?: CustomDataType;
  reasonCode: string;
  additionalInfo?: string;
}
