// Generated by scripts/generate-ocpp.ts. Do not edit.

export type GetCertificateIdUseEnumType =
  | "V2GRootCertificate"
  | "MORootCertificate"
  | "CSMSRootCertificate"
  | "V2GCertificateChain"
  | "ManufacturerRootCertificate";

export interface GetInstalledCertificateIdsRequestV201 {
  customData?: CustomDataType;
  certificateType?: [
    GetCertificateIdUseEnumType,
    ...GetCertificateIdUseEnumType[],
  ];
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
