// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface GetTransactionStatusResponseV201 {
  customData?: CustomDataType;
  ongoingIndicator?: boolean;
  messagesInQueue: boolean;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
