// Generated by scripts/generate-ocpp.ts. Do not edit.

export type LogEnumType = "DiagnosticsLog" | "SecurityLog";

export interface GetLogRequestV201 {
  customData?: CustomDataType;
  log: LogParametersType;
  logType: LogEnumType;
  requestId: number;
  retries?: number;
  retryInterval?: number;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface LogParametersType {
  customData?: CustomDataType;
  remoteLocation: string;
  oldestTimestamp?: string;
  latestTimestamp?: string;
}
