// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface GetTransactionStatusRequestV201 {
  customData?: CustomDataType;
  transactionId?: string;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
