// Generated by scripts/generate-ocpp.ts. Do not edit.

export type GenericStatusEnumType = "Accepted" | "Rejected";
export type ChargingRateUnitEnumType = "W" | "A";

export interface GetCompositeScheduleResponseV201 {
  customData?: CustomDataType;
  status: GenericStatusEnumType;
  statusInfo?: StatusInfoType;
  schedule?: CompositeScheduleType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface StatusInfoType {
  customData?: CustomDataType;
  reasonCode: string;
  additionalInfo?: string;
}
export interface CompositeScheduleType {
  customData?: CustomDataType;
  chargingSchedulePeriod: [
    ChargingSchedulePeriodType,
    ...ChargingSchedulePeriodType[],
  ];
  evseId: number;
  duration: number;
  scheduleStart: string;
  chargingRateUnit: ChargingRateUnitEnumType;
}
export interface ChargingSchedulePeriodType {
  customData?: CustomDataType;
  startPeriod: number;
  limit: number;
  numberPhases?: number;
  phaseToUse?: number;
}
