// Generated by scripts/generate-ocpp.ts. Do not edit.

export type CertificateActionEnumType = "Install" | "Update";

export interface Get15118EVCertificateRequestV201 {
  customData?: CustomDataType;
  iso15118SchemaVersion: string;
  action: CertificateActionEnumType;
  exiRequest: string;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
