// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface HeartbeatResponseV201 {
  customData?: CustomDataType;
  currentTime: string;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
