// Generated by scripts/generate-ocpp.ts. Do not edit.

export type EventTriggerEnumType = "Alerting" | "Delta" | "Periodic";
export type EventNotificationEnumType =
  | "HardWiredNotification"
  | "HardWiredMonitor"
  | "PreconfiguredMonitor"
  | "CustomMonitor";

export interface NotifyEventRequestV201 {
  customData?: CustomDataType;
  generatedAt: string;
  tbc?: boolean;
  seqNo: number;
  eventData: [EventDataType, ...EventDataType[]];
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface EventDataType {
  customData?: CustomDataType;
  eventId: number;
  timestamp: string;
  trigger: EventTriggerEnumType;
  cause?: number;
  actualValue: string;
  techCode?: string;
  techInfo?: string;
  cleared?: boolean;
  transactionId?: string;
  component: ComponentType;
  variableMonitoringId?: number;
  eventNotificationType: EventNotificationEnumType;
  variable: VariableType;
}
export interface ComponentType {
  customData?: CustomDataType;
  evse?: EVSEType;
  name: string;
  instance?: string;
}
export interface EVSEType {
  customData?: CustomDataType;
  id: number;
  connectorId?: number;
}
export interface VariableType {
  customData?: CustomDataType;
  name: string;
  instance?: string;
}
