// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface NotifyCustomerInformationRequestV201 {
  customData?: CustomDataType;
  data: string;
  tbc?: boolean;
  seqNo: number;
  generatedAt: string;
  requestId: number;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
