// Generated by scripts/generate-ocpp.ts. Do not edit.

export type AttributeEnumType = "Actual" | "Target" | "MinSet" | "MaxSet";
export type MutabilityEnumType = "ReadOnly" | "WriteOnly" | "ReadWrite";
export type DataEnumType =
  | "string"
  | "decimal"
  | "integer"
  | "dateTime"
  | "boolean"
  | "OptionList"
  | "SequenceList"
  | "MemberList";

export interface NotifyReportRequestV201 {
  customData?: CustomDataType;
  requestId: number;
  generatedAt: string;
  reportData?: [ReportDataType, ...ReportDataType[]];
  tbc?: boolean;
  seqNo: number;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface ReportDataType {
  customData?: CustomDataType;
  component: ComponentType;
  variable: VariableType;
  variableAttribute:
    | [VariableAttributeType]
    | [VariableAttributeType, VariableAttributeType]
    | [VariableAttributeType, VariableAttributeType, VariableAttributeType]
    | [
        VariableAttributeType,
        VariableAttributeType,
        VariableAttributeType,
        VariableAttributeType,
      ];
  variableCharacteristics?: VariableCharacteristicsType;
}
export interface ComponentType {
  customData?: CustomDataType;
  evse?: EVSEType;
  name: string;
  instance?: string;
}
export interface EVSEType {
  customData?: CustomDataType;
  id: number;
  connectorId?: number;
}
export interface VariableType {
  customData?: CustomDataType;
  name: string;
  instance?: string;
}
export interface VariableAttributeType {
  customData?: CustomDataType;
  type?: AttributeEnumType;
  value?: string;
  mutability?: MutabilityEnumType;
  persistent?: boolean;
  constant?: boolean;
}
export interface VariableCharacteristicsType {
  customData?: CustomDataType;
  unit?: string;
  dataType: DataEnumType;
  minLimit?: number;
  maxLimit?: number;
  valuesList?: string;
  supportsMonitoring: boolean;
}
