// Generated by scripts/generate-ocpp.ts. Do not edit.

export type MonitorEnumType =
  | "UpperThreshold"
  | "LowerThreshold"
  | "Delta"
  | "Periodic"
  | "PeriodicClockAligned";

export interface NotifyMonitoringReportRequestV201 {
  customData?: CustomDataType;
  monitor?: [MonitoringDataType, ...MonitoringDataType[]];
  requestId: number;
  tbc?: boolean;
  seqNo: number;
  generatedAt: string;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface MonitoringDataType {
  customData?: CustomDataType;
  component: ComponentType;
  variable: VariableType;
  variableMonitoring: [VariableMonitoringType, ...VariableMonitoringType[]];
}
export interface ComponentType {
  customData?: CustomDataType;
  evse?: EVSEType;
  name: string;
  instance?: string;
}
export interface EVSEType {
  customData?: CustomDataType;
  id: number;
  connectorId?: number;
}
export interface VariableType {
  customData?: CustomDataType;
  name: string;
  instance?: string;
}
export interface VariableMonitoringType {
  customData?: CustomDataType;
  id: number;
  transaction: boolean;
  value: number;
  type: MonitorEnumType;
  severity: number;
}
