// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ResetStatusEnumType = "Accepted" | "Rejected" | "Scheduled";

export interface ResetResponseV201 {
  customData?: CustomDataType;
  status: ResetStatusEnumType;
  statusInfo?: StatusInfoType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface StatusInfoType {
  customData?: CustomDataType;
  reasonCode: string;
  additionalInfo?: string;
}
