// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ReserveNowStatusEnumType =
  | "Accepted"
  | "Faulted"
  | "Occupied"
  | "Rejected"
  | "Unavailable";

export interface ReserveNowResponseV201 {
  customData?: CustomDataType;
  status: ReserveNowStatusEnumType;
  statusInfo?: StatusInfoType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface StatusInfoType {
  customData?: CustomDataType;
  reasonCode: string;
  additionalInfo?: string;
}
