// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ReservationUpdateStatusEnumType = "Expired" | "Removed";

export interface ReservationStatusUpdateRequestV201 {
  customData?: CustomDataType;
  reservationId: number;
  reservationUpdateStatus: ReservationUpdateStatusEnumType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
