// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface SecurityEventNotificationRequestV201 {
  customData?: CustomDataType;
  type: string;
  timestamp: string;
  techInfo?: string;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
