// Generated by scripts/generate-ocpp.ts. Do not edit.

export type MonitoringBaseEnumType = "All" | "FactoryDefault" | "HardWiredOnly";

export interface SetMonitoringBaseRequestV201 {
  customData?: CustomDataType;
  monitoringBase: MonitoringBaseEnumType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
