// Generated by scripts/generate-ocpp.ts. Do not edit.

export type MonitorEnumType =
  | "UpperThreshold"
  | "LowerThreshold"
  | "Delta"
  | "Periodic"
  | "PeriodicClockAligned";

export interface SetVariableMonitoringRequestV201 {
  customData?: CustomDataType;
  setMonitoringData: [SetMonitoringDataType, ...SetMonitoringDataType[]];
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface SetMonitoringDataType {
  customData?: CustomDataType;
  id?: number;
  transaction?: boolean;
  value: number;
  type: MonitorEnumType;
  severity: number;
  component: ComponentType;
  variable: VariableType;
}
export interface ComponentType {
  customData?: CustomDataType;
  evse?: EVSEType;
  name: string;
  instance?: string;
}
export interface EVSEType {
  customData?: CustomDataType;
  id: number;
  connectorId?: number;
}
export interface VariableType {
  customData?: CustomDataType;
  name: string;
  instance?: string;
}
