// Generated by scripts/generate-ocpp.ts. Do not edit.

export type APNAuthenticationEnumType = "CHAP" | "NONE" | "PAP" | "AUTO";
export type OCPPVersionEnumType = "OCPP12" | "OCPP15" | "OCPP16" | "OCPP20";
export type OCPPTransportEnumType = "JSON" | "SOAP";
export type OCPPInterfaceEnumType =
  | "Wired0"
  | "Wired1"
  | "Wired2"
  | "Wired3"
  | "Wireless0"
  | "Wireless1"
  | "Wireless2"
  | "Wireless3";
export type VPNEnumType = "IKEv2" | "IPSec" | "L2TP" | "PPTP";

export interface SetNetworkProfileRequestV201 {
  customData?: CustomDataType;
  configurationSlot: number;
  connectionData: NetworkConnectionProfileType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface NetworkConnectionProfileType {
  customData?: CustomDataType;
  apn?: APNType;
  ocppVersion: OCPPVersionEnumType;
  ocppTransport: OCPPTransportEnumType;
  ocppCsmsUrl: string;
  messageTimeout: number;
  securityProfile: number;
  ocppInterface: OCPPInterfaceEnumType;
  vpn?: VPNType;
}
export interface APNType {
  customData?: CustomDataType;
  apn: string;
  apnUserName?: string;
  apnPassword?: string;
  simPin?: number;
  preferredNetwork?: string;
  useOnlyPreferredNetwork?: boolean;
  apnAuthentication: APNAuthenticationEnumType;
}
export interface VPNType {
  customData?: CustomDataType;
  server: string;
  user: string;
  group?: string;
  password: string;
  key: string;
  type: VPNEnumType;
}
