// Generated by scripts/generate-ocpp.ts. Do not edit.

export type MessagePriorityEnumType = "AlwaysFront" | "InFront" | "NormalCycle";
export type MessageStateEnumType =
  "Charging" | "Faulted" | "Idle" | "Unavailable";
export type MessageFormatEnumType = "ASCII" | "HTML" | "URI" | "UTF8";

export interface SetDisplayMessageRequestV201 {
  customData?: CustomDataType;
  message: MessageInfoType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface MessageInfoType {
  customData?: CustomDataType;
  display?: ComponentType;
  id: number;
  priority: MessagePriorityEnumType;
  state?: MessageStateEnumType;
  startDateTime?: string;
  endDateTime?: string;
  transactionId?: string;
  message: MessageContentType;
}
export interface ComponentType {
  customData?: CustomDataType;
  evse?: EVSEType;
  name: string;
  instance?: string;
}
export interface EVSEType {
  customData?: CustomDataType;
  id: number;
  connectorId?: number;
}
export interface MessageContentType {
  customData?: CustomDataType;
  format: MessageFormatEnumType;
  language?: string;
  content: string;
}
