// Generated by scripts/generate-ocpp.ts. Do not edit.

export type AttributeEnumType = "Actual" | "Target" | "MinSet" | "MaxSet";

export interface SetVariablesRequestV201 {
  customData?: CustomDataType;
  setVariableData: [SetVariableDataType, ...SetVariableDataType[]];
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface SetVariableDataType {
  customData?: CustomDataType;
  attributeType?: AttributeEnumType;
  attributeValue: string;
  component: ComponentType;
  variable: VariableType;
}
export interface ComponentType {
  customData?: CustomDataType;
  evse?: EVSEType;
  name: string;
  instance?: string;
}
export interface EVSEType {
  customData?: CustomDataType;
  id: number;
  connectorId?: number;
}
export interface VariableType {
  customData?: CustomDataType;
  name: string;
  instance?: string;
}
