// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface SetMonitoringLevelRequestV201 {
  customData?: CustomDataType;
  severity: number;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
