// Generated by scripts/generate-ocpp.ts. Do not edit.

export type CertificateSigningUseEnumType =
  | "ChargingStationCertificate"
  | "V2GCertificate";

export interface SignCertificateRequestV201 {
  customData?: CustomDataType;
  csr: string;
  certificateType?: CertificateSigningUseEnumType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
