// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ConnectorStatusEnumType =
  | "Available"
  | "Occupied"
  | "Reserved"
  | "Unavailable"
  | "Faulted";

export interface StatusNotificationRequestV201 {
  customData?: CustomDataType;
  timestamp: string;
  connectorStatus: ConnectorStatusEnumType;
  evseId: number;
  connectorId: number;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
