// Generated by scripts/generate-ocpp.ts. Do not edit.

export type TransactionEventEnumType = "Ended" | "Started" | "Updated";
export type ReadingContextEnumType =
  | "Interruption.Begin"
  | "Interruption.End"
  | "Other"
  | "Sample.Clock"
  | "Sample.Periodic"
  | "Transaction.Begin"
  | "Transaction.End"
  | "Trigger";
export type MeasurandEnumType =
  | "Current.Export"
  | "Current.Import"
  | "Current.Offered"
  | "Energy.Active.Export.Register"
  | "Energy.Active.Import.Register"
  | "Energy.Reactive.Export.Register"
  | "Energy.Reactive.Import.Register"
  | "Energy.Active.Export.Interval"
  | "Energy.Active.Import.Interval"
  | "Energy.Active.Net"
  | "Energy.Reactive.Export.Interval"
  | "Energy.Reactive.Import.Interval"
  | "Energy.Reactive.Net"
  | "Energy.Apparent.Net"
  | "Energy.Apparent.Import"
  | "Energy.Apparent.Export"
  | "Frequency"
  | "Power.Active.Export"
  | "Power.Active.Import"
  | "Power.Factor"
  | "Power.Offered"
  | "Power.Reactive.Export"
  | "Power.Reactive.Import"
  | "SoC"
  | "Voltage";
export type PhaseEnumType =
  | "L1"
  | "L2"
  | "L3"
  | "N"
  | "L1-N"
  | "L2-N"
  | "L3-N"
  | "L1-L2"
  | "L2-L3"
  | "L3-L1";
export type LocationEnumType = "Body" | "Cable" | "EV" | "Inlet" | "Outlet";
export type TriggerReasonEnumType =
  | "Authorized"
  | "CablePluggedIn"
  | "ChargingRateChanged"
  | "ChargingStateChanged"
  | "Deauthorized"
  | "EnergyLimitReached"
  | "EVCommunicationLost"
  | "EVConnectTimeout"
  | "MeterValueClock"
  | "MeterValuePeriodic"
  | "TimeLimitReached"
  | "Trigger"
  | "UnlockCommand"
  | "StopAuthorized"
  | "EVDeparted"
  | "EVDetected"
  | "RemoteStop"
  | "RemoteStart"
  | "AbnormalCondition"
  | "SignedDataReceived"
  | "ResetCommand";
export type ChargingStateEnumType =
  "Charging" | "EVConnected" | "SuspendedEV" | "SuspendedEVSE" | "Idle";
export type ReasonEnumType =
  | "DeAuthorized"
  | "EmergencyStop"
  | "EnergyLimitReached"
  | "EVDisconnected"
  | "GroundFault"
  | "ImmediateReset"
  | "Local"
  | "LocalOutOfCredit"
  | "MasterPass"
  | "Other"
  | "OvercurrentFault"
  | "PowerLoss"
  | "PowerQuality"
  | "Reboot"
  | "Remote"
  | "SOCLimitReached"
  | "StoppedByEV"
  | "TimeLimitReached"
  | "Timeout";
export type IdTokenEnumType =
  | "Central"
  | "eMAID"
  | "ISO14443"
  | "ISO15693"
  | "KeyCode"
  | "Local"
  | "MacAddress"
  | "NoAuthorization";

export interface TransactionEventRequestV201 {
  customData?: CustomDataType;
  eventType: TransactionEventEnumType;
  meterValue?: [MeterValueType, ...MeterValueType[]];
  timestamp: string;
  triggerReason: TriggerReasonEnumType;
  seqNo: number;
  offline?: boolean;
  numberOfPhasesUsed?: number;
  cableMaxCurrent?: number;
  reservationId?: number;
  transactionInfo: TransactionType;
  evse?: EVSEType;
  idToken?: IdTokenType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface MeterValueType {
  customData?: CustomDataType;
  sampledValue: [SampledValueType, ...SampledValueType[]];
  timestamp: string;
}
export interface SampledValueType {
  customData?: CustomDataType;
  value: number;
  context?: ReadingContextEnumType;
  measurand?: MeasurandEnumType;
  phase?: PhaseEnumType;
  location?: LocationEnumType;
  signedMeterValue?: SignedMeterValueType;
  unitOfMeasure?: UnitOfMeasureType;
}
export interface SignedMeterValueType {
  customData?: CustomDataType;
  signedMeterData: string;
  signingMethod: string;
  encodingMethod: string;
  publicKey: string;
}
export interface UnitOfMeasureType {
  customData?: CustomDataType;
  unit?: string;
  multiplier?: number;
}
export interface TransactionType {
  customData?: CustomDataType;
  transactionId: string;
  chargingState?: ChargingStateEnumType;
  timeSpentCharging?: number;
  stoppedReason?: ReasonEnumType;
  remoteStartId?: number;
}
export interface EVSEType {
  customData?: CustomDataType;
  id: number;
  connectorId?: number;
}
export interface IdTokenType {
  customData?: CustomDataType;
  additionalInfo?: [AdditionalInfoType, ...AdditionalInfoType[]];
  idToken: string;
  type: IdTokenEnumType;
}
export interface AdditionalInfoType {
  customData?: CustomDataType;
  additionalIdToken: string;
  type: string;
}
