// Generated by scripts/generate-ocpp.ts. Do not edit.

export type MessageTriggerEnumType =
  | "BootNotification"
  | "LogStatusNotification"
  | "FirmwareStatusNotification"
  | "Heartbeat"
  | "MeterValues"
  | "SignChargingStationCertificate"
  | "SignV2GCertificate"
  | "StatusNotification"
  | "TransactionEvent"
  | "SignCombinedCertificate"
  | "PublishFirmwareStatusNotification";

export interface TriggerMessageRequestV201 {
  customData?: CustomDataType;
  evse?: EVSEType;
  requestedMessage: MessageTriggerEnumType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface EVSEType {
  customData?: CustomDataType;
  id: number;
  connectorId?: number;
}
