// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface UnlockConnectorRequestV201 {
  customData?: CustomDataType;
  evseId: number;
  connectorId: number;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
