// Generated by scripts/generate-ocpp.ts. Do not edit.

export type UnpublishFirmwareStatusEnumType =
  "DownloadOngoing" | "NoFirmware" | "Unpublished";

export interface UnpublishFirmwareResponseV201 {
  customData?: CustomDataType;
  status: UnpublishFirmwareStatusEnumType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
