// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface UnpublishFirmwareRequestV201 {
  customData?: CustomDataType;
  checksum: string;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
