import { spawnSync } from "node:child_process";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";
import type { JSONSchema } from "json-schema-to-typescript";

type Version = "v16" | "v201" | "v21";
type MessageKind = "Request" | "Response";
type JsonObject = Record<string, unknown>;

interface MessageSpec {
  action: string;
  kind: MessageKind;
  schemaImportName: string;
  schemaKey: string;
  sourcePath: string;
  typeFileBase: string;
  typeName: string;
  version: Version;
  versionSuffix: string;
}

const versions: Version[] = ["v16", "v201", "v21"];
const versionSuffixes: Record<Version, string> = {
  v16: "V16",
  v201: "V201",
  v21: "V21",
};
const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const vendorDir = join(rootDir, "vendor", "ocpp-schemas");
const outputDir = join(rootDir, "src", "ocpp");
const generatedHeader =
  "// Generated by scripts/generate-ocpp.ts. Do not edit.\n\n";
const nestedV201Exports = [
  "ReportDataType",
  "VariableAttributeType",
  "VariableCharacteristicsType",
];

function isJsonObject(value: unknown): value is JsonObject {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

async function readJsonObject(path: string): Promise<JsonObject> {
  const parsed: unknown = JSON.parse(await readFile(path, "utf8"));

  if (!isJsonObject(parsed)) {
    throw new Error(`${path} did not contain a JSON object`);
  }

  return parsed;
}

function cloneJsonObject(value: JsonObject): JsonObject {
  const cloned: unknown = JSON.parse(JSON.stringify(value));

  if (!isJsonObject(cloned)) {
    throw new Error("JSON object clone did not produce an object");
  }

  return cloned;
}

function lowerFirst(value: string): string {
  return `${value.charAt(0).toLowerCase()}${value.slice(1)}`;
}

function kebabCase(value: string): string {
  return value
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase();
}

function modulePath(fromDir: string, toPath: string): string {
  const path = relative(fromDir, toPath).replace(/\\/g, "/");

  return path.startsWith(".") ? path : `./${path}`;
}

function inferKind(fileStem: string): MessageKind {
  return fileStem.endsWith("Response") ? "Response" : "Request";
}

function actionName(fileStem: string, kind: MessageKind): string {
  return fileStem.endsWith(kind) ? fileStem.slice(0, -kind.length) : fileStem;
}

function rootBaseName(fileStem: string, kind: MessageKind): string {
  return fileStem.endsWith(kind) ? fileStem : `${fileStem}${kind}`;
}

async function discoverSpecs(version: Version): Promise<MessageSpec[]> {
  const versionDir = join(vendorDir, version);
  const files = (await readdir(versionDir))
    .filter((file) => file.endsWith(".json"))
    .sort((left, right) => left.localeCompare(right));

  return files
    .map((file) => {
      const fileStem = file.slice(0, -".json".length);
      const kind = inferKind(fileStem);
      const baseName = rootBaseName(fileStem, kind);
      const versionSuffix = versionSuffixes[version];
      const typeName = `${baseName}${versionSuffix}`;
      const schemaKey = lowerFirst(typeName);

      return {
        action: actionName(fileStem, kind),
        kind,
        schemaImportName: `${schemaKey}Schema`,
        schemaKey,
        sourcePath: join(versionDir, file),
        typeFileBase: kebabCase(baseName),
        typeName,
        version,
        versionSuffix,
      };
    })
    .sort((left, right) => left.typeName.localeCompare(right.typeName));
}

async function writeGenerated(path: string, contents: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, `${contents.trimEnd()}\n`, "utf8");
}

function stripSchemaComments(contents: string): string {
  return contents
    .replace(/\/\*\*[\s\S]*?\*\/\n?/g, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

async function writeTypeFile(spec: MessageSpec): Promise<void> {
  const schema = cloneJsonObject(await readJsonObject(spec.sourcePath));
  schema.title = spec.typeName;

  const compiled = await compile(schema as JSONSchema, spec.typeName, {
    bannerComment: "",
    format: false,
    style: {
      semi: true,
      singleQuote: false,
      tabWidth: 2,
      trailingComma: "all",
    },
    unknownAny: true,
    unreachableDefinitions: false,
  });

  await writeGenerated(
    join(outputDir, spec.version, "types", `${spec.typeFileBase}.ts`),
    `${generatedHeader}${stripSchemaComments(compiled)}`,
  );
}

async function writeSchemasFile(
  version: Version,
  specs: MessageSpec[],
): Promise<void> {
  const versionDir = join(outputDir, version);
  const imports = specs.map((spec) => {
    const source = modulePath(versionDir, spec.sourcePath);

    return `import ${spec.schemaImportName} from "${source}";`;
  });
  const entries = specs.map(
    (spec) => `  ${spec.schemaKey}: ${spec.schemaImportName},`,
  );

  await writeGenerated(
    join(versionDir, "schemas.ts"),
    `${generatedHeader}${imports.join("\n")}

export const ${version}Schemas: Record<string, object> = {
${entries.join("\n")}
};`,
  );
}

async function writeValidatorsFile(
  version: Version,
  specs: MessageSpec[],
): Promise<void> {
  const versionDir = join(outputDir, version);
  const typeImports = specs.map((spec) => {
    return `import type { ${spec.typeName} } from "./types/${spec.typeFileBase}";`;
  });
  const validators = specs.map((spec) => {
    return `export const isValid${spec.typeName} = (
  data: unknown,
): data is ${spec.typeName} =>
  validateOCPPPayload(${version}Schemas.${spec.schemaKey}, data);`;
  });
  const requestSpecs = specs.filter((spec) => spec.kind === "Request");
  const actionEntries = requestSpecs.map((spec) => {
    return `  ${JSON.stringify(spec.action)}: isValid${spec.typeName},`;
  });

  await writeGenerated(
    join(versionDir, "validators.ts"),
    `${generatedHeader}import { validateOCPPPayload } from "../validate";
import { ${version}Schemas } from "./schemas";
${typeImports.join("\n")}

${validators.join("\n\n")}

export const actionValidator${versionSuffixes[version]}: Record<
  string,
  (data: unknown) => boolean
> = {
${actionEntries.join("\n")}
};`,
  );
}

async function writeVersionIndex(
  version: Version,
  specs: MessageSpec[],
): Promise<void> {
  const typeExports = specs.map((spec) => {
    if (version === "v201" && spec.typeName === "NotifyReportRequestV201") {
      return `export type { ${[spec.typeName, ...nestedV201Exports].join(
        ", ",
      )} } from "./types/${spec.typeFileBase}";`;
    }

    return `export type { ${spec.typeName} } from "./types/${spec.typeFileBase}";`;
  });

  await writeGenerated(
    join(outputDir, version, "index.ts"),
    `${generatedHeader}export * from "./schemas";
export * from "./validators";
${typeExports.join("\n")}`,
  );
}

async function writeSchemaAggregate(): Promise<void> {
  await writeGenerated(
    join(outputDir, "schemas.ts"),
    `${generatedHeader}import { v16Schemas } from "./v16/schemas";
import { v201Schemas } from "./v201/schemas";
import { v21Schemas } from "./v21/schemas";

export const schemas: {
  v16: Record<string, object>;
  v201: Record<string, object>;
  v21: Record<string, object>;
} = {
  v16: v16Schemas,
  v201: v201Schemas,
  v21: v21Schemas,
};`,
  );
}

async function writeValidateModule(): Promise<void> {
  await writeGenerated(
    join(outputDir, "validate.ts"),
    `${generatedHeader}import Ajv from "ajv";
import type { AnySchema, AnySchemaObject, ValidateFunction } from "ajv";
import draft06MetaSchema from "ajv/dist/refs/json-schema-draft-06.json";
import Ajv04 from "ajv-draft-04";

interface SchemaCompiler {
  compile(schema: AnySchema): ValidateFunction;
}

const ajvOptions = {
  allErrors: true,
  strict: false,
  strictSchema: false,
  validateFormats: false,
  // OCPP 1.6 declares multipleOf 0.1 on charging limits, and AJV's exact
  // check reads 0.3 as not a multiple of 0.1 because 0.3 / 0.1 is
  // 2.9999999999999996 in binary floating point. Without a tolerance a legal
  // SetChargingProfile is rejected -- which mattered the moment #285 turned
  // these results into SOAP Faults rather than warnings.
  multipleOfPrecision: 6,
};

const draft04Ajv = new Ajv04(ajvOptions) as SchemaCompiler;
const draft06AjvInstance = new Ajv(ajvOptions);
draft06AjvInstance.addMetaSchema(draft06MetaSchema as AnySchemaObject);
const draft06Ajv = draft06AjvInstance as SchemaCompiler;
const draft04Cache = new WeakMap<object, ValidateFunction>();
const draft06Cache = new WeakMap<object, ValidateFunction>();

function isDraft04Schema(schema: object): boolean {
  const schemaVersion = (schema as { $schema?: unknown }).$schema;

  return typeof schemaVersion === "string" && schemaVersion.includes("draft-04");
}

function validatorCache(schema: object): WeakMap<object, ValidateFunction> {
  return isDraft04Schema(schema) ? draft04Cache : draft06Cache;
}

function validatorCompiler(schema: object): SchemaCompiler {
  return isDraft04Schema(schema) ? draft04Ajv : draft06Ajv;
}

function validatorFor(schema: object): ValidateFunction {
  const cache = validatorCache(schema);
  const cached = cache.get(schema);

  if (cached) {
    return cached;
  }

  const compiled = validatorCompiler(schema).compile(schema as AnySchema);
  cache.set(schema, compiled);

  return compiled;
}

export function validateOCPPPayload(schema: object, data: unknown): boolean {
  if (data == null) {
    return false;
  }

  return validatorFor(schema)(data) === true;
}

export function validationErrors(schema: object, data: unknown): string[] {
  const validate = validatorFor(schema);

  if (validate(data)) {
    return [];
  }

  return (validate.errors ?? []).map((error) =>
    \`\${error.instancePath} \${error.message ?? ""}\`.trim(),
  );
}

// The strict pair. The instances above leave formats unchecked, which is the
// right default for a warning: a CSMS with a sloppy timestamp should still be
// simulated against. It is the wrong default for a gate that REFUSES a
// request (#285), where an unchecked format means expiryDate "not-a-date"
// reaches the handler and gets a normal answer. Only date-time and uri appear
// in the vendored OCPP 1.6 schemas, so they are implemented here rather than
// by taking on ajv-formats.
const strictAjvOptions = { ...ajvOptions, validateFormats: true };

type FormatCheck = (value: string) => boolean;

const DATE_TIME_SHAPE =
  /^(\\d{4})-(\\d{2})-(\\d{2})[Tt](\\d{2}):(\\d{2}):(\\d{2})(\\.\\d+)?([Zz]|[+-]\\d{2}:\\d{2})$/;

function isRealCalendarInstant(value: string): boolean {
  const match = DATE_TIME_SHAPE.exec(value);
  if (!match) return false;
  const [, y, mo, d, h, mi, sec] = match.map(Number);
  if (mo < 1 || mo > 12) return false;
  const leap = (y % 4 === 0 && y % 100 !== 0) || y % 400 === 0;
  const days = [31, leap ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
  // Deliberately not Date.parse: it NORMALISES, so 2026-02-30 becomes March 2
  // and reports success, and it rejects the leap second RFC 3339 allows.
  if (d < 1 || d > days[mo - 1]) return false;
  if (h > 23 || mi > 59) return false;
  return sec <= 60;
}

const OCPP_FORMATS: Record<string, FormatCheck> = {
  // RFC 3339, which is what OCPP means by dateTime.
  "date-time": isRealCalendarInstant,
  // Absolute only: OCPP uses these for firmware and diagnostics locations,
  // which a charge point has to reach on its own. \`new URL()\` alone is too
  // permissive -- it accepts a space and a dangling percent by normalising
  // them -- so the RFC 3986 character rules are checked first.
  uri: (value) => {
    if (/[\\s<>"{}|\\\\^\`]/.test(value)) return false;
    if (/%(?![0-9A-Fa-f]{2})/.test(value)) return false;
    try {
      return Boolean(new URL(value).protocol);
    } catch {
      return false;
    }
  },
};

interface FormatAware {
  addFormat(name: string, format: FormatCheck): unknown;
}

function withFormats<T>(instance: T): T {
  for (const [name, check] of Object.entries(OCPP_FORMATS)) {
    (instance as FormatAware).addFormat(name, check);
  }
  return instance;
}

const strictDraft04Ajv = withFormats(
  new Ajv04(strictAjvOptions),
) as unknown as SchemaCompiler;
const strictDraft06Instance = new Ajv(strictAjvOptions);
strictDraft06Instance.addMetaSchema(draft06MetaSchema as AnySchemaObject);
withFormats(strictDraft06Instance);
const strictDraft06Ajv = strictDraft06Instance as unknown as SchemaCompiler;
const strictDraft04Cache = new WeakMap<object, ValidateFunction>();
const strictDraft06Cache = new WeakMap<object, ValidateFunction>();

function strictValidatorFor(schema: object): ValidateFunction {
  const draft04 = isDraft04Schema(schema);
  const cache = draft04 ? strictDraft04Cache : strictDraft06Cache;
  const cached = cache.get(schema);

  if (cached) {
    return cached;
  }

  const compiled = (draft04 ? strictDraft04Ajv : strictDraft06Ajv).compile(
    schema as AnySchema,
  );
  cache.set(schema, compiled);

  return compiled;
}

/** Like validationErrors, but formats count. */
export function strictValidationErrors(
  schema: object,
  data: unknown,
): string[] {
  const validate = strictValidatorFor(schema);

  if (validate(data)) {
    return [];
  }

  return (validate.errors ?? []).map((error) =>
    \`\${error.instancePath} \${error.message ?? ""}\`.trim(),
  );
}`,
  );
}

async function writeEnumsModule(): Promise<void> {
  await writeGenerated(
    join(outputDir, "enums.ts"),
    `${generatedHeader}export enum ActionNameV16 {
  Authorize = "Authorize",
  BootNotification = "BootNotification",
  CancelReservation = "CancelReservation",
  CertificateSigned = "CertificateSigned",
  ChangeAvailability = "ChangeAvailability",
  ChangeConfiguration = "ChangeConfiguration",
  ClearCache = "ClearCache",
  ClearChargingProfile = "ClearChargingProfile",
  DataTransfer = "DataTransfer",
  DeleteCertificate = "DeleteCertificate",
  DiagnosticsStatusNotification = "DiagnosticsStatusNotification",
  ExtendedTriggerMessage = "ExtendedTriggerMessage",
  FirmwareStatusNotification = "FirmwareStatusNotification",
  GetCompositeSchedule = "GetCompositeSchedule",
  GetConfiguration = "GetConfiguration",
  GetDiagnostics = "GetDiagnostics",
  GetInstalledCertificateIds = "GetInstalledCertificateIds",
  GetLocalListVersion = "GetLocalListVersion",
  GetLog = "GetLog",
  Heartbeat = "Heartbeat",
  InstallCertificate = "InstallCertificate",
  LogStatusNotification = "LogStatusNotification",
  MeterValues = "MeterValues",
  RemoteStartTransaction = "RemoteStartTransaction",
  RemoteStopTransaction = "RemoteStopTransaction",
  ReserveNow = "ReserveNow",
  Reset = "Reset",
  SecurityEventNotification = "SecurityEventNotification",
  SendLocalList = "SendLocalList",
  SetChargingProfile = "SetChargingProfile",
  SignCertificate = "SignCertificate",
  SignedFirmwareStatusNotification = "SignedFirmwareStatusNotification",
  SignedUpdateFirmware = "SignedUpdateFirmware",
  StartTransaction = "StartTransaction",
  StatusNotification = "StatusNotification",
  StopTransaction = "StopTransaction",
  TriggerMessage = "TriggerMessage",
  UnlockConnector = "UnlockConnector",
  UpdateFirmware = "UpdateFirmware",
}

export enum OCPPErrorCodeV16 {
  NotImplemented = "NotImplemented",
  NotSupported = "NotSupported",
  InternalError = "InternalError",
  ProtocolError = "ProtocolError",
  SecurityError = "SecurityError",
  FormationViolation = "FormationViolation",
  PropertyConstraintViolation = "PropertyConstraintViolation",
  OccurenceConstraintViolation = "OccurenceConstraintViolation",
  TypeConstraintViolation = "TypeConstraintViolation",
  GenericError = "GenericError",
}

export enum ActionNameV201 {
  Authorize = "Authorize",
  BootNotification = "BootNotification",
  CancelReservation = "CancelReservation",
  CertificateSigned = "CertificateSigned",
  ChangeAvailability = "ChangeAvailability",
  ClearCache = "ClearCache",
  ClearChargingProfile = "ClearChargingProfile",
  ClearDisplayMessage = "ClearDisplayMessage",
  ClearVariableMonitoring = "ClearVariableMonitoring",
  ClearedChargingLimit = "ClearedChargingLimit",
  CostUpdated = "CostUpdated",
  CustomerInformation = "CustomerInformation",
  DataTransfer = "DataTransfer",
  DeleteCertificate = "DeleteCertificate",
  FirmwareStatusNotification = "FirmwareStatusNotification",
  GetBaseReport = "GetBaseReport",
  GetCertificateStatus = "GetCertificateStatus",
  GetChargingProfiles = "GetChargingProfiles",
  GetCompositeSchedule = "GetCompositeSchedule",
  GetDisplayMessages = "GetDisplayMessages",
  GetInstalledCertificateIds = "GetInstalledCertificateIds",
  GetLocalListVersion = "GetLocalListVersion",
  GetLog = "GetLog",
  GetMonitoringReport = "GetMonitoringReport",
  GetReport = "GetReport",
  GetTransactionStatus = "GetTransactionStatus",
  GetVariables = "GetVariables",
  Get15118EVCertificate = "Get15118EVCertificate",
  Heartbeat = "Heartbeat",
  InstallCertificate = "InstallCertificate",
  LogStatusNotification = "LogStatusNotification",
  MeterValues = "MeterValues",
  NotifyChargingLimit = "NotifyChargingLimit",
  NotifyCustomerInformation = "NotifyCustomerInformation",
  NotifyDisplayMessages = "NotifyDisplayMessages",
  NotifyEVChargingNeeds = "NotifyEVChargingNeeds",
  NotifyEVChargingSchedule = "NotifyEVChargingSchedule",
  NotifyEvent = "NotifyEvent",
  NotifyMonitoringReport = "NotifyMonitoringReport",
  NotifyReport = "NotifyReport",
  PublishFirmwareStatusNotification = "PublishFirmwareStatusNotification",
  PublishFirmware = "PublishFirmware",
  ReportChargingProfiles = "ReportChargingProfiles",
  ReservationStatusUpdate = "ReservationStatusUpdate",
  ReserveNow = "ReserveNow",
  Reset = "Reset",
  SecurityEventNotification = "SecurityEventNotification",
  SendLocalList = "SendLocalList",
  SetChargingProfile = "SetChargingProfile",
  SetDisplayMessage = "SetDisplayMessage",
  SetMonitoringBase = "SetMonitoringBase",
  SetMonitoringLevel = "SetMonitoringLevel",
  SetNetworkProfile = "SetNetworkProfile",
  SetVariableMonitoring = "SetVariableMonitoring",
  SetVariables = "SetVariables",
  SignCertificate = "SignCertificate",
  StartTransactionResponse = "StartTransactionResponse",
  StartTransactionRequest = "StartTransactionRequest",
  StatusNotification = "StatusNotification",
  StopTransactionResponse = "StopTransactionResponse",
  StopTransactionRequest = "StopTransactionRequest",
  TransactionEvent = "TransactionEvent",
  TriggerMessage = "TriggerMessage",
  UnlockConnector = "UnlockConnector",
  UnpublishFirmware = "UnpublishFirmware",
  UpdateFirmware = "UpdateFirmware",
}

export enum OCPPErrorCodeV201 {
  NotImplemented = "NotImplemented",
  NotSupported = "NotSupported",
  InternalError = "InternalError",
  ProtocolError = "ProtocolError",
  SecurityError = "SecurityError",
  FormationViolation = "FormationViolation",
  PropertyConstraintViolation = "PropertyConstraintViolation",
  OccurenceConstraintViolation = "OccurenceConstraintViolation",
  TypeConstraintViolation = "TypeConstraintViolation",
  GenericError = "GenericError",
}`,
  );
}

async function writeRootIndex(): Promise<void> {
  await writeGenerated(
    join(outputDir, "index.ts"),
    `${generatedHeader}export * from "./validate";
export * from "./schemas";
export * from "./enums";
export * from "./v16";
export * from "./v201";
export * from "./v21";`,
  );
}

async function writeCompatibilityModules(): Promise<void> {
  await writeGenerated(
    join(outputDir, "validation", "index.ts"),
    `${generatedHeader}export { validateOCPPPayload, validationErrors, strictValidationErrors } from "../validate";
export * from "./v16";
export * from "./v201";
export * from "./v21";`,
  );

  for (const version of versions) {
    await writeGenerated(
      join(outputDir, "validation", version, "index.ts"),
      `${generatedHeader}export * from "../../${version}/validators";`,
    );
  }

  await writeGenerated(
    join(outputDir, "types", "v201", "notify-report.ts"),
    `${generatedHeader}export type { ${nestedV201Exports.join(
      ", ",
    )} } from "../../v201/types/notify-report-request";`,
  );
}

function formatOutput(): void {
  const prettierBin = join(
    rootDir,
    "node_modules",
    ".bin",
    process.platform === "win32" ? "prettier.cmd" : "prettier",
  );
  const result = spawnSync(
    prettierBin,
    ["--write", outputDir, "--log-level", "silent"],
    {
      cwd: rootDir,
      encoding: "utf8",
    },
  );

  if (result.status !== 0) {
    throw new Error(
      `Prettier failed while formatting generated OCPP files.\n${result.stdout ?? ""}${result.stderr ?? ""}`,
    );
  }
}

async function main(): Promise<void> {
  const specsByVersion = new Map<Version, MessageSpec[]>();

  for (const version of versions) {
    specsByVersion.set(version, await discoverSpecs(version));
  }

  await rm(outputDir, { force: true, recursive: true });
  await mkdir(outputDir, { recursive: true });

  for (const version of versions) {
    const specs = specsByVersion.get(version);

    if (!specs) {
      throw new Error(`No schema specs discovered for ${version}`);
    }

    for (const spec of specs) {
      await writeTypeFile(spec);
    }

    await writeSchemasFile(version, specs);
    await writeValidatorsFile(version, specs);
    await writeVersionIndex(version, specs);
  }

  await writeSchemaAggregate();
  await writeValidateModule();
  await writeEnumsModule();
  await writeRootIndex();
  await writeCompatibilityModules();
  formatOutput();

  const counts = versions.map((version) => {
    const count = specsByVersion.get(version)?.length ?? 0;

    return `${version}: ${count}`;
  });

  console.log(`Generated OCPP code (${counts.join(", ")})`);
}

await main();
