// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface AdjustPeriodicEventStreamRequestV21 {
  id: number;
  params: PeriodicEventStreamParamsType;
  customData?: CustomDataType;
}
export interface PeriodicEventStreamParamsType {
  interval?: number;
  values?: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
