// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface AFRRSignalRequestV21 {
  timestamp: string;
  signal: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
