// Generated by scripts/generate-ocpp.ts. Do not edit.

export type AuthorizationStatusEnumType =
  | "Accepted"
  | "Blocked"
  | "ConcurrentTx"
  | "Expired"
  | "Invalid"
  | "NoCredit"
  | "NotAllowedTypeEVSE"
  | "NotAtThisLocation"
  | "NotAtThisTime"
  | "Unknown";
export type MessageFormatEnumType =
  "ASCII" | "HTML" | "URI" | "UTF8" | "QRCODE";
export type AuthorizeCertificateStatusEnumType =
  | "Accepted"
  | "SignatureError"
  | "CertificateExpired"
  | "CertificateRevoked"
  | "NoCertificateAvailable"
  | "CertChainError"
  | "ContractCancelled";
export type EnergyTransferModeEnumType =
  | "AC_single_phase"
  | "AC_two_phase"
  | "AC_three_phase"
  | "DC"
  | "AC_BPT"
  | "AC_BPT_DER"
  | "AC_DER"
  | "DC_BPT"
  | "DC_ACDP"
  | "DC_ACDP_BPT"
  | "WPT";
export type DayOfWeekEnumType =
  | "Monday"
  | "Tuesday"
  | "Wednesday"
  | "Thursday"
  | "Friday"
  | "Saturday"
  | "Sunday";
export type EvseKindEnumType = "AC" | "DC";

export interface AuthorizeResponseV21 {
  idTokenInfo: IdTokenInfoType;
  certificateStatus?: AuthorizeCertificateStatusEnumType;
  allowedEnergyTransfer?: [
    EnergyTransferModeEnumType,
    ...EnergyTransferModeEnumType[],
  ];
  tariff?: TariffType;
  customData?: CustomDataType;
}
export interface IdTokenInfoType {
  status: AuthorizationStatusEnumType;
  cacheExpiryDateTime?: string;
  chargingPriority?: number;
  groupIdToken?: IdTokenType;
  language1?: string;
  language2?: string;
  evseId?: [number, ...number[]];
  personalMessage?: MessageContentType;
  customData?: CustomDataType;
}
export interface IdTokenType {
  additionalInfo?: [AdditionalInfoType, ...AdditionalInfoType[]];
  idToken: string;
  type: string;
  customData?: CustomDataType;
}
export interface AdditionalInfoType {
  additionalIdToken: string;
  type: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface MessageContentType {
  format: MessageFormatEnumType;
  language?: string;
  content: string;
  customData?: CustomDataType;
}
export interface TariffType {
  tariffId: string;
  description?:
    | [MessageContentType]
    | [MessageContentType, MessageContentType]
    | [MessageContentType, MessageContentType, MessageContentType]
    | [
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
      ]
    | [
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
      ]
    | [
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
      ]
    | [
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
      ]
    | [
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
      ]
    | [
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
      ]
    | [
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
      ];
  currency: string;
  energy?: TariffEnergyType;
  validFrom?: string;
  chargingTime?: TariffTimeType;
  idleTime?: TariffTimeType;
  fixedFee?: TariffFixedType;
  reservationTime?: TariffTimeType;
  reservationFixed?: TariffFixedType;
  minCost?: PriceType;
  maxCost?: PriceType;
  customData?: CustomDataType;
}
export interface TariffEnergyType {
  prices: [TariffEnergyPriceType, ...TariffEnergyPriceType[]];
  taxRates?:
    | [TaxRateType]
    | [TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType, TaxRateType];
  customData?: CustomDataType;
}
export interface TariffEnergyPriceType {
  priceKwh: number;
  conditions?: TariffConditionsType;
  customData?: CustomDataType;
}
export interface TariffConditionsType {
  startTimeOfDay?: string;
  endTimeOfDay?: string;
  dayOfWeek?:
    | [DayOfWeekEnumType]
    | [DayOfWeekEnumType, DayOfWeekEnumType]
    | [DayOfWeekEnumType, DayOfWeekEnumType, DayOfWeekEnumType]
    | [
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
      ]
    | [
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
      ]
    | [
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
      ]
    | [
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
      ];
  validFromDate?: string;
  validToDate?: string;
  evseKind?: EvseKindEnumType;
  minEnergy?: number;
  maxEnergy?: number;
  minCurrent?: number;
  maxCurrent?: number;
  minPower?: number;
  maxPower?: number;
  minTime?: number;
  maxTime?: number;
  minChargingTime?: number;
  maxChargingTime?: number;
  minIdleTime?: number;
  maxIdleTime?: number;
  customData?: CustomDataType;
}
export interface TaxRateType {
  type: string;
  tax: number;
  stack?: number;
  customData?: CustomDataType;
}
export interface TariffTimeType {
  prices: [TariffTimePriceType, ...TariffTimePriceType[]];
  taxRates?:
    | [TaxRateType]
    | [TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType, TaxRateType];
  customData?: CustomDataType;
}
export interface TariffTimePriceType {
  priceMinute: number;
  conditions?: TariffConditionsType;
  customData?: CustomDataType;
}
export interface TariffFixedType {
  prices: [TariffFixedPriceType, ...TariffFixedPriceType[]];
  taxRates?:
    | [TaxRateType]
    | [TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType, TaxRateType];
  customData?: CustomDataType;
}
export interface TariffFixedPriceType {
  conditions?: TariffConditionsFixedType;
  priceFixed: number;
  customData?: CustomDataType;
}
export interface TariffConditionsFixedType {
  startTimeOfDay?: string;
  endTimeOfDay?: string;
  dayOfWeek?:
    | [DayOfWeekEnumType]
    | [DayOfWeekEnumType, DayOfWeekEnumType]
    | [DayOfWeekEnumType, DayOfWeekEnumType, DayOfWeekEnumType]
    | [
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
      ]
    | [
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
      ]
    | [
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
      ]
    | [
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
      ];
  validFromDate?: string;
  validToDate?: string;
  evseKind?: EvseKindEnumType;
  paymentBrand?: string;
  paymentRecognition?: string;
  customData?: CustomDataType;
}
export interface PriceType {
  exclTax?: number;
  inclTax?: number;
  taxRates?:
    | [TaxRateType]
    | [TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType, TaxRateType];
  customData?: CustomDataType;
}
