// Generated by scripts/generate-ocpp.ts. Do not edit.

export type BootReasonEnumType =
  | "ApplicationReset"
  | "FirmwareUpdate"
  | "LocalReset"
  | "PowerUp"
  | "RemoteReset"
  | "ScheduledReset"
  | "Triggered"
  | "Unknown"
  | "Watchdog";

export interface BootNotificationRequestV21 {
  chargingStation: ChargingStationType;
  reason: BootReasonEnumType;
  customData?: CustomDataType;
}
export interface ChargingStationType {
  serialNumber?: string;
  model: string;
  modem?: ModemType;
  vendorName: string;
  firmwareVersion?: string;
  customData?: CustomDataType;
}
export interface ModemType {
  iccid?: string;
  imsi?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
