// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface CancelReservationRequestV21 {
  reservationId: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
