// Generated by scripts/generate-ocpp.ts. Do not edit.

export type CertificateSigningUseEnumType =
  "ChargingStationCertificate" | "V2GCertificate" | "V2G20Certificate";

export interface CertificateSignedRequestV21 {
  certificateChain: string;
  certificateType?: CertificateSigningUseEnumType;
  requestId?: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
