// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ChangeAvailabilityStatusEnumType =
  "Accepted" | "Rejected" | "Scheduled";

export interface ChangeAvailabilityResponseV21 {
  status: ChangeAvailabilityStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
