// Generated by scripts/generate-ocpp.ts. Do not edit.

export type TariffChangeStatusEnumType =
  | "Accepted"
  | "Rejected"
  | "TooManyElements"
  | "ConditionNotSupported"
  | "TxNotFound"
  | "NoCurrencyChange";

export interface ChangeTransactionTariffResponseV21 {
  status: TariffChangeStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
