// Generated by scripts/generate-ocpp.ts. Do not edit.

export type TariffClearStatusEnumType = "Accepted" | "Rejected" | "NoTariff";

export interface ClearTariffsResponseV21 {
  clearTariffsResult: [ClearTariffsResultType, ...ClearTariffsResultType[]];
  customData?: CustomDataType;
}
export interface ClearTariffsResultType {
  statusInfo?: StatusInfoType;
  tariffId?: string;
  status: TariffClearStatusEnumType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
