// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ClearMonitoringStatusEnumType =
  "Accepted" | "Rejected" | "NotFound";

export interface ClearVariableMonitoringResponseV21 {
  clearMonitoringResult: [
    ClearMonitoringResultType,
    ...ClearMonitoringResultType[],
  ];
  customData?: CustomDataType;
}
export interface ClearMonitoringResultType {
  status: ClearMonitoringStatusEnumType;
  id: number;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
