// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ClearMessageStatusEnumType = "Accepted" | "Unknown" | "Rejected";

export interface ClearDisplayMessageResponseV21 {
  status: ClearMessageStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
