// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface ClearedChargingLimitRequestV21 {
  chargingLimitSource: string;
  evseId?: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
