// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface ClearTariffsRequestV21 {
  tariffIds?: [string, ...string[]];
  evseId?: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
