// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface ClearDisplayMessageRequestV21 {
  id: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
