// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ChargingProfilePurposeEnumType =
  | "ChargingStationExternalConstraints"
  | "ChargingStationMaxProfile"
  | "TxDefaultProfile"
  | "TxProfile"
  | "PriorityCharging"
  | "LocalGeneration";

export interface ClearChargingProfileRequestV21 {
  chargingProfileId?: number;
  chargingProfileCriteria?: ClearChargingProfileType;
  customData?: CustomDataType;
}
export interface ClearChargingProfileType {
  evseId?: number;
  chargingProfilePurpose?: ChargingProfilePurposeEnumType;
  stackLevel?: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
