// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface CostUpdatedRequestV21 {
  totalCost: number;
  transactionId: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
