// Generated by scripts/generate-ocpp.ts. Do not edit.

export type CustomerInformationStatusEnumType =
  | "Accepted"
  | "Rejected"
  | "Invalid";

export interface CustomerInformationResponseV21 {
  status: CustomerInformationStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
