// Generated by scripts/generate-ocpp.ts. Do not edit.

export type HashAlgorithmEnumType = "SHA256" | "SHA384" | "SHA512";

export interface CustomerInformationRequestV21 {
  customerCertificate?: CertificateHashDataType;
  idToken?: IdTokenType;
  requestId: number;
  report: boolean;
  clear: boolean;
  customerIdentifier?: string;
  customData?: CustomDataType;
}
export interface CertificateHashDataType {
  hashAlgorithm: HashAlgorithmEnumType;
  issuerNameHash: string;
  issuerKeyHash: string;
  serialNumber: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface IdTokenType {
  additionalInfo?: [AdditionalInfoType, ...AdditionalInfoType[]];
  idToken: string;
  type: string;
  customData?: CustomDataType;
}
export interface AdditionalInfoType {
  additionalIdToken: string;
  type: string;
  customData?: CustomDataType;
}
