// Generated by scripts/generate-ocpp.ts. Do not edit.

export type DataTransferStatusEnumType =
  | "Accepted"
  | "Rejected"
  | "UnknownMessageId"
  | "UnknownVendorId";

export interface DataTransferResponseV21 {
  status: DataTransferStatusEnumType;
  statusInfo?: StatusInfoType;
  data?: {
    [k: string]: unknown;
  };
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
