// Generated by scripts/generate-ocpp.ts. Do not edit.

export type HashAlgorithmEnumType = "SHA256" | "SHA384" | "SHA512";
export type CertificateStatusSourceEnumType = "CRL" | "OCSP";
export type CertificateStatusEnumType =
  "Good" | "Revoked" | "Unknown" | "Failed";

export interface GetCertificateChainStatusResponseV21 {
  certificateStatus:
    | [CertificateStatusType]
    | [CertificateStatusType, CertificateStatusType]
    | [CertificateStatusType, CertificateStatusType, CertificateStatusType]
    | [
        CertificateStatusType,
        CertificateStatusType,
        CertificateStatusType,
        CertificateStatusType,
      ];
  customData?: CustomDataType;
}
export interface CertificateStatusType {
  certificateHashData: CertificateHashDataType;
  source: CertificateStatusSourceEnumType;
  status: CertificateStatusEnumType;
  nextUpdate: string;
  customData?: CustomDataType;
}
export interface CertificateHashDataType {
  hashAlgorithm: HashAlgorithmEnumType;
  issuerNameHash: string;
  issuerKeyHash: string;
  serialNumber: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
