// Generated by scripts/generate-ocpp.ts. Do not edit.

export type GetVariableStatusEnumType =
  | "Accepted"
  | "Rejected"
  | "UnknownComponent"
  | "UnknownVariable"
  | "NotSupportedAttributeType";
export type AttributeEnumType = "Actual" | "Target" | "MinSet" | "MaxSet";

export interface GetVariablesResponseV21 {
  getVariableResult: [GetVariableResultType, ...GetVariableResultType[]];
  customData?: CustomDataType;
}
export interface GetVariableResultType {
  attributeStatus: GetVariableStatusEnumType;
  attributeStatusInfo?: StatusInfoType;
  attributeType?: AttributeEnumType;
  attributeValue?: string;
  component: ComponentType;
  variable: VariableType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface ComponentType {
  evse?: EVSEType;
  name: string;
  instance?: string;
  customData?: CustomDataType;
}
export interface EVSEType {
  id: number;
  connectorId?: number;
  customData?: CustomDataType;
}
export interface VariableType {
  name: string;
  instance?: string;
  customData?: CustomDataType;
}
