// Generated by scripts/generate-ocpp.ts. Do not edit.

export type GenericStatusEnumType = "Accepted" | "Rejected";
export type ChargingRateUnitEnumType = "W" | "A";
export type OperationModeEnumType =
  | "Idle"
  | "ChargingOnly"
  | "CentralSetpoint"
  | "ExternalSetpoint"
  | "ExternalLimits"
  | "CentralFrequency"
  | "LocalFrequency"
  | "LocalLoadBalancing";

export interface GetCompositeScheduleResponseV21 {
  status: GenericStatusEnumType;
  statusInfo?: StatusInfoType;
  schedule?: CompositeScheduleType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface CompositeScheduleType {
  evseId: number;
  duration: number;
  scheduleStart: string;
  chargingRateUnit: ChargingRateUnitEnumType;
  chargingSchedulePeriod: [
    ChargingSchedulePeriodType,
    ...ChargingSchedulePeriodType[],
  ];
  customData?: CustomDataType;
}
export interface ChargingSchedulePeriodType {
  startPeriod: number;
  limit?: number;
  limit_L2?: number;
  limit_L3?: number;
  numberPhases?: number;
  phaseToUse?: number;
  dischargeLimit?: number;
  dischargeLimit_L2?: number;
  dischargeLimit_L3?: number;
  setpoint?: number;
  setpoint_L2?: number;
  setpoint_L3?: number;
  setpointReactive?: number;
  setpointReactive_L2?: number;
  setpointReactive_L3?: number;
  preconditioningRequest?: boolean;
  evseSleep?: boolean;
  v2xBaseline?: number;
  operationMode?: OperationModeEnumType;
  v2xFreqWattCurve?:
    | [V2XFreqWattPointType]
    | [V2XFreqWattPointType, V2XFreqWattPointType]
    | [V2XFreqWattPointType, V2XFreqWattPointType, V2XFreqWattPointType]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ];
  v2xSignalWattCurve?:
    | [V2XSignalWattPointType]
    | [V2XSignalWattPointType, V2XSignalWattPointType]
    | [V2XSignalWattPointType, V2XSignalWattPointType, V2XSignalWattPointType]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ];
  customData?: CustomDataType;
}
export interface V2XFreqWattPointType {
  frequency: number;
  power: number;
  customData?: CustomDataType;
}
export interface V2XSignalWattPointType {
  signal: number;
  power: number;
  customData?: CustomDataType;
}
