// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ReportBaseEnumType =
  "ConfigurationInventory" | "FullInventory" | "SummaryInventory";

export interface GetBaseReportRequestV21 {
  requestId: number;
  reportBase: ReportBaseEnumType;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
