// Generated by scripts/generate-ocpp.ts. Do not edit.

export type GetInstalledCertificateStatusEnumType = "Accepted" | "NotFound";
export type HashAlgorithmEnumType = "SHA256" | "SHA384" | "SHA512";
export type GetCertificateIdUseEnumType =
  | "V2GRootCertificate"
  | "MORootCertificate"
  | "CSMSRootCertificate"
  | "V2GCertificateChain"
  | "ManufacturerRootCertificate"
  | "OEMRootCertificate";

export interface GetInstalledCertificateIdsResponseV21 {
  status: GetInstalledCertificateStatusEnumType;
  statusInfo?: StatusInfoType;
  certificateHashDataChain?: [
    CertificateHashDataChainType,
    ...CertificateHashDataChainType[],
  ];
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface CertificateHashDataChainType {
  certificateHashData: CertificateHashDataType;
  certificateType: GetCertificateIdUseEnumType;
  childCertificateHashData?:
    | [CertificateHashDataType]
    | [CertificateHashDataType, CertificateHashDataType]
    | [
        CertificateHashDataType,
        CertificateHashDataType,
        CertificateHashDataType,
      ]
    | [
        CertificateHashDataType,
        CertificateHashDataType,
        CertificateHashDataType,
        CertificateHashDataType,
      ];
  customData?: CustomDataType;
}
export interface CertificateHashDataType {
  hashAlgorithm: HashAlgorithmEnumType;
  issuerNameHash: string;
  issuerKeyHash: string;
  serialNumber: string;
  customData?: CustomDataType;
}
