// Generated by scripts/generate-ocpp.ts. Do not edit.

export type DERControlEnumType =
  | "EnterService"
  | "FreqDroop"
  | "FreqWatt"
  | "FixedPFAbsorb"
  | "FixedPFInject"
  | "FixedVar"
  | "Gradients"
  | "HFMustTrip"
  | "HFMayTrip"
  | "HVMustTrip"
  | "HVMomCess"
  | "HVMayTrip"
  | "LimitMaxDischarge"
  | "LFMustTrip"
  | "LVMustTrip"
  | "LVMomCess"
  | "LVMayTrip"
  | "PowerMonitoringMustTrip"
  | "VoltVar"
  | "VoltWatt"
  | "WattPF"
  | "WattVar";

export interface GetDERControlRequestV21 {
  requestId: number;
  isDefault?: boolean;
  controlType?: DERControlEnumType;
  controlId?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
