// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ChargingProfilePurposeEnumType =
  | "ChargingStationExternalConstraints"
  | "ChargingStationMaxProfile"
  | "TxDefaultProfile"
  | "TxProfile"
  | "PriorityCharging"
  | "LocalGeneration";

export interface GetChargingProfilesRequestV21 {
  requestId: number;
  evseId?: number;
  chargingProfile: ChargingProfileCriterionType;
  customData?: CustomDataType;
}
export interface ChargingProfileCriterionType {
  chargingProfilePurpose?: ChargingProfilePurposeEnumType;
  stackLevel?: number;
  chargingProfileId?: [number, ...number[]];
  chargingLimitSource?:
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string];
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
