// Generated by scripts/generate-ocpp.ts. Do not edit.

export type GetDisplayMessagesStatusEnumType = "Accepted" | "Unknown";

export interface GetDisplayMessagesResponseV21 {
  status: GetDisplayMessagesStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
