// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface GetTariffsRequestV21 {
  evseId: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
