// Generated by scripts/generate-ocpp.ts. Do not edit.

export type AttributeEnumType = "Actual" | "Target" | "MinSet" | "MaxSet";

export interface GetVariablesRequestV21 {
  getVariableData: [GetVariableDataType, ...GetVariableDataType[]];
  customData?: CustomDataType;
}
export interface GetVariableDataType {
  attributeType?: AttributeEnumType;
  component: ComponentType;
  variable: VariableType;
  customData?: CustomDataType;
}
export interface ComponentType {
  evse?: EVSEType;
  name: string;
  instance?: string;
  customData?: CustomDataType;
}
export interface EVSEType {
  id: number;
  connectorId?: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface VariableType {
  name: string;
  instance?: string;
  customData?: CustomDataType;
}
