// Generated by scripts/generate-ocpp.ts. Do not edit.

export type GetCertificateIdUseEnumType =
  | "V2GRootCertificate"
  | "MORootCertificate"
  | "CSMSRootCertificate"
  | "V2GCertificateChain"
  | "ManufacturerRootCertificate"
  | "OEMRootCertificate";

export interface GetInstalledCertificateIdsRequestV21 {
  certificateType?: [
    GetCertificateIdUseEnumType,
    ...GetCertificateIdUseEnumType[],
  ];
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
