// Generated by scripts/generate-ocpp.ts. Do not edit.

export type HashAlgorithmEnumType = "SHA256" | "SHA384" | "SHA512";
export type CertificateStatusSourceEnumType = "CRL" | "OCSP";

export interface GetCertificateChainStatusRequestV21 {
  certificateStatusRequests:
    | [CertificateStatusRequestInfoType]
    | [CertificateStatusRequestInfoType, CertificateStatusRequestInfoType]
    | [
        CertificateStatusRequestInfoType,
        CertificateStatusRequestInfoType,
        CertificateStatusRequestInfoType,
      ]
    | [
        CertificateStatusRequestInfoType,
        CertificateStatusRequestInfoType,
        CertificateStatusRequestInfoType,
        CertificateStatusRequestInfoType,
      ];
  customData?: CustomDataType;
}
export interface CertificateStatusRequestInfoType {
  certificateHashData: CertificateHashDataType;
  source: CertificateStatusSourceEnumType;
  urls:
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string];
  customData?: CustomDataType;
}
export interface CertificateHashDataType {
  hashAlgorithm: HashAlgorithmEnumType;
  issuerNameHash: string;
  issuerKeyHash: string;
  serialNumber: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
