// Generated by scripts/generate-ocpp.ts. Do not edit.

export type HashAlgorithmEnumType = "SHA256" | "SHA384" | "SHA512";

export interface GetCertificateStatusRequestV21 {
  ocspRequestData: OCSPRequestDataType;
  customData?: CustomDataType;
}
export interface OCSPRequestDataType {
  hashAlgorithm: HashAlgorithmEnumType;
  issuerNameHash: string;
  issuerKeyHash: string;
  serialNumber: string;
  responderURL: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
