// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ChargingRateUnitEnumType = "W" | "A";

export interface GetCompositeScheduleRequestV21 {
  duration: number;
  chargingRateUnit?: ChargingRateUnitEnumType;
  evseId: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
