// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface GetLocalListVersionResponseV21 {
  versionNumber: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
