// Generated by scripts/generate-ocpp.ts. Do not edit.

export type DERControlStatusEnumType =
  | "Accepted"
  | "Rejected"
  | "NotSupported"
  | "NotFound";

export interface GetDERControlResponseV21 {
  status: DERControlStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
