// Generated by scripts/generate-ocpp.ts. Do not edit.

export type Iso15118EVCertificateStatusEnumType = "Accepted" | "Failed";

export interface Get15118EVCertificateResponseV21 {
  status: Iso15118EVCertificateStatusEnumType;
  statusInfo?: StatusInfoType;
  exiResponse: string;
  remainingContracts?: number;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
