// Generated by scripts/generate-ocpp.ts. Do not edit.

export type CertificateActionEnumType = "Install" | "Update";

export interface Get15118EVCertificateRequestV21 {
  iso15118SchemaVersion: string;
  action: CertificateActionEnumType;
  exiRequest: string;
  maximumContractCertificateChains?: number;
  prioritizedEMAIDs?:
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | [string, string, string, string, string, string]
    | [string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string];
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
