// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface HeartbeatResponseV21 {
  currentTime: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
