// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface HeartbeatRequestV21 {
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
