// Generated by scripts/generate-ocpp.ts. Do not edit.

export type InstallCertificateStatusEnumType =
  "Accepted" | "Rejected" | "Failed";

export interface InstallCertificateResponseV21 {
  status: InstallCertificateStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
