// Generated by scripts/generate-ocpp.ts. Do not edit.

export type MeasurandEnumType =
  | "Current.Export"
  | "Current.Export.Offered"
  | "Current.Export.Minimum"
  | "Current.Import"
  | "Current.Import.Offered"
  | "Current.Import.Minimum"
  | "Current.Offered"
  | "Display.PresentSOC"
  | "Display.MinimumSOC"
  | "Display.TargetSOC"
  | "Display.MaximumSOC"
  | "Display.RemainingTimeToMinimumSOC"
  | "Display.RemainingTimeToTargetSOC"
  | "Display.RemainingTimeToMaximumSOC"
  | "Display.ChargingComplete"
  | "Display.BatteryEnergyCapacity"
  | "Display.InletHot"
  | "Energy.Active.Export.Interval"
  | "Energy.Active.Export.Register"
  | "Energy.Active.Import.Interval"
  | "Energy.Active.Import.Register"
  | "Energy.Active.Import.CableLoss"
  | "Energy.Active.Import.LocalGeneration.Register"
  | "Energy.Active.Net"
  | "Energy.Active.Setpoint.Interval"
  | "Energy.Apparent.Export"
  | "Energy.Apparent.Import"
  | "Energy.Apparent.Net"
  | "Energy.Reactive.Export.Interval"
  | "Energy.Reactive.Export.Register"
  | "Energy.Reactive.Import.Interval"
  | "Energy.Reactive.Import.Register"
  | "Energy.Reactive.Net"
  | "EnergyRequest.Target"
  | "EnergyRequest.Minimum"
  | "EnergyRequest.Maximum"
  | "EnergyRequest.Minimum.V2X"
  | "EnergyRequest.Maximum.V2X"
  | "EnergyRequest.Bulk"
  | "Frequency"
  | "Power.Active.Export"
  | "Power.Active.Import"
  | "Power.Active.Setpoint"
  | "Power.Active.Residual"
  | "Power.Export.Minimum"
  | "Power.Export.Offered"
  | "Power.Factor"
  | "Power.Import.Offered"
  | "Power.Import.Minimum"
  | "Power.Offered"
  | "Power.Reactive.Export"
  | "Power.Reactive.Import"
  | "SoC"
  | "Voltage"
  | "Voltage.Minimum"
  | "Voltage.Maximum";
export type ReadingContextEnumType =
  | "Interruption.Begin"
  | "Interruption.End"
  | "Other"
  | "Sample.Clock"
  | "Sample.Periodic"
  | "Transaction.Begin"
  | "Transaction.End"
  | "Trigger";
export type PhaseEnumType =
  | "L1"
  | "L2"
  | "L3"
  | "N"
  | "L1-N"
  | "L2-N"
  | "L3-N"
  | "L1-L2"
  | "L2-L3"
  | "L3-L1";
export type LocationEnumType =
  | "Body"
  | "Cable"
  | "EV"
  | "Inlet"
  | "Outlet"
  | "Upstream";

export interface MeterValuesRequestV21 {
  evseId: number;
  meterValue: [MeterValueType, ...MeterValueType[]];
  customData?: CustomDataType;
}
export interface MeterValueType {
  sampledValue: [SampledValueType, ...SampledValueType[]];
  timestamp: string;
  customData?: CustomDataType;
}
export interface SampledValueType {
  value: number;
  measurand?: MeasurandEnumType;
  context?: ReadingContextEnumType;
  phase?: PhaseEnumType;
  location?: LocationEnumType;
  signedMeterValue?: SignedMeterValueType;
  unitOfMeasure?: UnitOfMeasureType;
  customData?: CustomDataType;
}
export interface SignedMeterValueType {
  signedMeterData: string;
  signingMethod?: string;
  encodingMethod: string;
  publicKey?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface UnitOfMeasureType {
  unit?: string;
  multiplier?: number;
  customData?: CustomDataType;
}
