// Generated by scripts/generate-ocpp.ts. Do not edit.

export type NotifyAllowedEnergyTransferStatusEnumType = "Accepted" | "Rejected";

export interface NotifyAllowedEnergyTransferResponseV21 {
  status: NotifyAllowedEnergyTransferStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
