// Generated by scripts/generate-ocpp.ts. Do not edit.

export type MessagePriorityEnumType = "AlwaysFront" | "InFront" | "NormalCycle";
export type MessageStateEnumType =
  "Charging" | "Faulted" | "Idle" | "Unavailable" | "Suspended" | "Discharging";
export type MessageFormatEnumType =
  "ASCII" | "HTML" | "URI" | "UTF8" | "QRCODE";

export interface NotifyDisplayMessagesRequestV21 {
  messageInfo?: [MessageInfoType, ...MessageInfoType[]];
  requestId: number;
  tbc?: boolean;
  customData?: CustomDataType;
}
export interface MessageInfoType {
  display?: ComponentType;
  id: number;
  priority: MessagePriorityEnumType;
  state?: MessageStateEnumType;
  startDateTime?: string;
  endDateTime?: string;
  transactionId?: string;
  message: MessageContentType;
  messageExtra?:
    | [MessageContentType]
    | [MessageContentType, MessageContentType]
    | [MessageContentType, MessageContentType, MessageContentType]
    | [
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
      ];
  customData?: CustomDataType;
}
export interface ComponentType {
  evse?: EVSEType;
  name: string;
  instance?: string;
  customData?: CustomDataType;
}
export interface EVSEType {
  id: number;
  connectorId?: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface MessageContentType {
  format: MessageFormatEnumType;
  language?: string;
  content: string;
  customData?: CustomDataType;
}
