// Generated by scripts/generate-ocpp.ts. Do not edit.

export type NotifyEVChargingNeedsStatusEnumType =
  "Accepted" | "Rejected" | "Processing" | "NoChargingProfile";

export interface NotifyEVChargingNeedsResponseV21 {
  status: NotifyEVChargingNeedsStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
