// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ChargingRateUnitEnumType = "W" | "A";
export type OperationModeEnumType =
  | "Idle"
  | "ChargingOnly"
  | "CentralSetpoint"
  | "ExternalSetpoint"
  | "ExternalLimits"
  | "CentralFrequency"
  | "LocalFrequency"
  | "LocalLoadBalancing";
export type CostKindEnumType =
  | "CarbonDioxideEmission"
  | "RelativePricePercentage"
  | "RenewableGenerationPercentage";

export interface NotifyChargingLimitRequestV21 {
  chargingSchedule?: [ChargingScheduleType, ...ChargingScheduleType[]];
  evseId?: number;
  chargingLimit: ChargingLimitType;
  customData?: CustomDataType;
}
export interface ChargingScheduleType {
  id: number;
  limitAtSoC?: LimitAtSoCType;
  startSchedule?: string;
  duration?: number;
  chargingRateUnit: ChargingRateUnitEnumType;
  minChargingRate?: number;
  powerTolerance?: number;
  signatureId?: number;
  digestValue?: string;
  useLocalTime?: boolean;
  chargingSchedulePeriod: [
    ChargingSchedulePeriodType,
    ...ChargingSchedulePeriodType[],
  ];
  randomizedDelay?: number;
  salesTariff?: SalesTariffType;
  absolutePriceSchedule?: AbsolutePriceScheduleType;
  priceLevelSchedule?: PriceLevelScheduleType;
  customData?: CustomDataType;
}
export interface LimitAtSoCType {
  soc: number;
  limit: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface ChargingSchedulePeriodType {
  startPeriod: number;
  limit?: number;
  limit_L2?: number;
  limit_L3?: number;
  numberPhases?: number;
  phaseToUse?: number;
  dischargeLimit?: number;
  dischargeLimit_L2?: number;
  dischargeLimit_L3?: number;
  setpoint?: number;
  setpoint_L2?: number;
  setpoint_L3?: number;
  setpointReactive?: number;
  setpointReactive_L2?: number;
  setpointReactive_L3?: number;
  preconditioningRequest?: boolean;
  evseSleep?: boolean;
  v2xBaseline?: number;
  operationMode?: OperationModeEnumType;
  v2xFreqWattCurve?:
    | [V2XFreqWattPointType]
    | [V2XFreqWattPointType, V2XFreqWattPointType]
    | [V2XFreqWattPointType, V2XFreqWattPointType, V2XFreqWattPointType]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ]
    | [
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
        V2XFreqWattPointType,
      ];
  v2xSignalWattCurve?:
    | [V2XSignalWattPointType]
    | [V2XSignalWattPointType, V2XSignalWattPointType]
    | [V2XSignalWattPointType, V2XSignalWattPointType, V2XSignalWattPointType]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ]
    | [
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
        V2XSignalWattPointType,
      ];
  customData?: CustomDataType;
}
export interface V2XFreqWattPointType {
  frequency: number;
  power: number;
  customData?: CustomDataType;
}
export interface V2XSignalWattPointType {
  signal: number;
  power: number;
  customData?: CustomDataType;
}
export interface SalesTariffType {
  id: number;
  salesTariffDescription?: string;
  numEPriceLevels?: number;
  salesTariffEntry: [SalesTariffEntryType, ...SalesTariffEntryType[]];
  customData?: CustomDataType;
}
export interface SalesTariffEntryType {
  relativeTimeInterval: RelativeTimeIntervalType;
  ePriceLevel?: number;
  consumptionCost?:
    | [ConsumptionCostType]
    | [ConsumptionCostType, ConsumptionCostType]
    | [ConsumptionCostType, ConsumptionCostType, ConsumptionCostType];
  customData?: CustomDataType;
}
export interface RelativeTimeIntervalType {
  start: number;
  duration?: number;
  customData?: CustomDataType;
}
export interface ConsumptionCostType {
  startValue: number;
  cost: [CostType] | [CostType, CostType] | [CostType, CostType, CostType];
  customData?: CustomDataType;
}
export interface CostType {
  costKind: CostKindEnumType;
  amount: number;
  amountMultiplier?: number;
  customData?: CustomDataType;
}
export interface AbsolutePriceScheduleType {
  timeAnchor: string;
  priceScheduleID: number;
  priceScheduleDescription?: string;
  currency: string;
  language: string;
  priceAlgorithm: string;
  minimumCost?: RationalNumberType;
  maximumCost?: RationalNumberType;
  priceRuleStacks: [PriceRuleStackType, ...PriceRuleStackType[]];
  taxRules?:
    | [TaxRuleType]
    | [TaxRuleType, TaxRuleType]
    | [TaxRuleType, TaxRuleType, TaxRuleType]
    | [TaxRuleType, TaxRuleType, TaxRuleType, TaxRuleType]
    | [TaxRuleType, TaxRuleType, TaxRuleType, TaxRuleType, TaxRuleType]
    | [
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
      ]
    | [
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
      ]
    | [
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
      ]
    | [
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
      ]
    | [
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
        TaxRuleType,
      ];
  overstayRuleList?: OverstayRuleListType;
  additionalSelectedServices?:
    | [AdditionalSelectedServicesType]
    | [AdditionalSelectedServicesType, AdditionalSelectedServicesType]
    | [
        AdditionalSelectedServicesType,
        AdditionalSelectedServicesType,
        AdditionalSelectedServicesType,
      ]
    | [
        AdditionalSelectedServicesType,
        AdditionalSelectedServicesType,
        AdditionalSelectedServicesType,
        AdditionalSelectedServicesType,
      ]
    | [
        AdditionalSelectedServicesType,
        AdditionalSelectedServicesType,
        AdditionalSelectedServicesType,
        AdditionalSelectedServicesType,
        AdditionalSelectedServicesType,
      ];
  customData?: CustomDataType;
}
export interface RationalNumberType {
  exponent: number;
  value: number;
  customData?: CustomDataType;
}
export interface PriceRuleStackType {
  duration: number;
  priceRule:
    | [PriceRuleType]
    | [PriceRuleType, PriceRuleType]
    | [PriceRuleType, PriceRuleType, PriceRuleType]
    | [PriceRuleType, PriceRuleType, PriceRuleType, PriceRuleType]
    | [
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
      ]
    | [
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
      ]
    | [
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
      ]
    | [
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
        PriceRuleType,
      ];
  customData?: CustomDataType;
}
export interface PriceRuleType {
  parkingFeePeriod?: number;
  carbonDioxideEmission?: number;
  renewableGenerationPercentage?: number;
  energyFee: RationalNumberType;
  parkingFee?: RationalNumberType;
  powerRangeStart: RationalNumberType;
  customData?: CustomDataType;
}
export interface TaxRuleType {
  taxRuleID: number;
  taxRuleName?: string;
  taxIncludedInPrice?: boolean;
  appliesToEnergyFee: boolean;
  appliesToParkingFee: boolean;
  appliesToOverstayFee: boolean;
  appliesToMinimumMaximumCost: boolean;
  taxRate: RationalNumberType;
  customData?: CustomDataType;
}
export interface OverstayRuleListType {
  overstayPowerThreshold?: RationalNumberType;
  overstayRule:
    | [OverstayRuleType]
    | [OverstayRuleType, OverstayRuleType]
    | [OverstayRuleType, OverstayRuleType, OverstayRuleType]
    | [OverstayRuleType, OverstayRuleType, OverstayRuleType, OverstayRuleType]
    | [
        OverstayRuleType,
        OverstayRuleType,
        OverstayRuleType,
        OverstayRuleType,
        OverstayRuleType,
      ];
  overstayTimeThreshold?: number;
  customData?: CustomDataType;
}
export interface OverstayRuleType {
  overstayFee: RationalNumberType;
  overstayRuleDescription?: string;
  startTime: number;
  overstayFeePeriod: number;
  customData?: CustomDataType;
}
export interface AdditionalSelectedServicesType {
  serviceFee: RationalNumberType;
  serviceName: string;
  customData?: CustomDataType;
}
export interface PriceLevelScheduleType {
  priceLevelScheduleEntries: [
    PriceLevelScheduleEntryType,
    ...PriceLevelScheduleEntryType[],
  ];
  timeAnchor: string;
  priceScheduleId: number;
  priceScheduleDescription?: string;
  numberOfPriceLevels: number;
  customData?: CustomDataType;
}
export interface PriceLevelScheduleEntryType {
  duration: number;
  priceLevel: number;
  customData?: CustomDataType;
}
export interface ChargingLimitType {
  chargingLimitSource: string;
  isLocalGeneration?: boolean;
  isGridCritical?: boolean;
  customData?: CustomDataType;
}
