// Generated by scripts/generate-ocpp.ts. Do not edit.

export type PaymentStatusEnumType =
  "Settled" | "Canceled" | "Rejected" | "Failed";

export interface NotifySettlementRequestV21 {
  transactionId?: string;
  pspRef: string;
  status: PaymentStatusEnumType;
  statusInfo?: string;
  settlementAmount: number;
  settlementTime: string;
  receiptId?: string;
  receiptUrl?: string;
  vatCompany?: AddressType;
  vatNumber?: string;
  customData?: CustomDataType;
}
export interface AddressType {
  name: string;
  address1: string;
  address2?: string;
  city: string;
  postalCode?: string;
  country: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
