// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface NotifyDERStartStopRequestV21 {
  controlId: string;
  started: boolean;
  timestamp: string;
  supersededIds?: [string, ...string[]];
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
