// Generated by scripts/generate-ocpp.ts. Do not edit.

export type EnergyTransferModeEnumType =
  | "AC_single_phase"
  | "AC_two_phase"
  | "AC_three_phase"
  | "DC"
  | "AC_BPT"
  | "AC_BPT_DER"
  | "AC_DER"
  | "DC_BPT"
  | "DC_ACDP"
  | "DC_ACDP_BPT"
  | "WPT";

export interface NotifyAllowedEnergyTransferRequestV21 {
  transactionId: string;
  allowedEnergyTransfer: [
    EnergyTransferModeEnumType,
    ...EnergyTransferModeEnumType[],
  ];
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
