// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface NotifyPeriodicEventStreamRequestV21 {
  data: [StreamDataElementType, ...StreamDataElementType[]];
  id: number;
  pending: number;
  basetime: string;
  customData?: CustomDataType;
}
export interface StreamDataElementType {
  t: number;
  v: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
