// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface NotifyPriorityChargingRequestV21 {
  transactionId: string;
  activated: boolean;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
