// Generated by scripts/generate-ocpp.ts. Do not edit.

export type MonitorEnumType =
  | "UpperThreshold"
  | "LowerThreshold"
  | "Delta"
  | "Periodic"
  | "PeriodicClockAligned"
  | "TargetDelta"
  | "TargetDeltaRelative";
export type EventNotificationEnumType =
  | "HardWiredNotification"
  | "HardWiredMonitor"
  | "PreconfiguredMonitor"
  | "CustomMonitor";

export interface NotifyMonitoringReportRequestV21 {
  monitor?: [MonitoringDataType, ...MonitoringDataType[]];
  requestId: number;
  tbc?: boolean;
  seqNo: number;
  generatedAt: string;
  customData?: CustomDataType;
}
export interface MonitoringDataType {
  component: ComponentType;
  variable: VariableType;
  variableMonitoring: [VariableMonitoringType, ...VariableMonitoringType[]];
  customData?: CustomDataType;
}
export interface ComponentType {
  evse?: EVSEType;
  name: string;
  instance?: string;
  customData?: CustomDataType;
}
export interface EVSEType {
  id: number;
  connectorId?: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface VariableType {
  name: string;
  instance?: string;
  customData?: CustomDataType;
}
export interface VariableMonitoringType {
  id: number;
  transaction: boolean;
  value: number;
  type: MonitorEnumType;
  severity: number;
  eventNotificationType: EventNotificationEnumType;
  customData?: CustomDataType;
}
