// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface NotifyWebPaymentStartedRequestV21 {
  evseId: number;
  timeout: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
