// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface NotifySettlementResponseV21 {
  receiptUrl?: string;
  receiptId?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
