// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface PullDynamicScheduleUpdateRequestV21 {
  chargingProfileId: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
