// Generated by scripts/generate-ocpp.ts. Do not edit.

export type PowerDuringCessationEnumType = "Active" | "Reactive";
export type DERUnitEnumType =
  | "Not_Applicable"
  | "PctMaxW"
  | "PctMaxVar"
  | "PctWAvail"
  | "PctVarAvail"
  | "PctEffectiveV";
export type DERControlEnumType =
  | "EnterService"
  | "FreqDroop"
  | "FreqWatt"
  | "FixedPFAbsorb"
  | "FixedPFInject"
  | "FixedVar"
  | "Gradients"
  | "HFMustTrip"
  | "HFMayTrip"
  | "HVMustTrip"
  | "HVMomCess"
  | "HVMayTrip"
  | "LimitMaxDischarge"
  | "LFMustTrip"
  | "LVMustTrip"
  | "LVMomCess"
  | "LVMayTrip"
  | "PowerMonitoringMustTrip"
  | "VoltVar"
  | "VoltWatt"
  | "WattPF"
  | "WattVar";

export interface ReportDERControlRequestV21 {
  curve?: [DERCurveGetType, ...DERCurveGetType[]];
  enterService?: [EnterServiceGetType, ...EnterServiceGetType[]];
  fixedPFAbsorb?: [FixedPFGetType, ...FixedPFGetType[]];
  fixedPFInject?: [FixedPFGetType, ...FixedPFGetType[]];
  fixedVar?: [FixedVarGetType, ...FixedVarGetType[]];
  freqDroop?: [FreqDroopGetType, ...FreqDroopGetType[]];
  gradient?: [GradientGetType, ...GradientGetType[]];
  limitMaxDischarge?: [LimitMaxDischargeGetType, ...LimitMaxDischargeGetType[]];
  requestId: number;
  tbc?: boolean;
  customData?: CustomDataType;
}
export interface DERCurveGetType {
  curve: DERCurveType;
  id: string;
  curveType: DERControlEnumType;
  isDefault: boolean;
  isSuperseded: boolean;
  customData?: CustomDataType;
}
export interface DERCurveType {
  curveData:
    | [DERCurvePointsType]
    | [DERCurvePointsType, DERCurvePointsType]
    | [DERCurvePointsType, DERCurvePointsType, DERCurvePointsType]
    | [
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
      ]
    | [
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
      ]
    | [
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
      ]
    | [
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
      ]
    | [
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
      ]
    | [
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
      ]
    | [
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
        DERCurvePointsType,
      ];
  hysteresis?: HysteresisType;
  priority: number;
  reactivePowerParams?: ReactivePowerParamsType;
  voltageParams?: VoltageParamsType;
  yUnit: DERUnitEnumType;
  responseTime?: number;
  startTime?: string;
  duration?: number;
  customData?: CustomDataType;
}
export interface DERCurvePointsType {
  x: number;
  y: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface HysteresisType {
  hysteresisHigh?: number;
  hysteresisLow?: number;
  hysteresisDelay?: number;
  hysteresisGradient?: number;
  customData?: CustomDataType;
}
export interface ReactivePowerParamsType {
  vRef?: number;
  autonomousVRefEnable?: boolean;
  autonomousVRefTimeConstant?: number;
  customData?: CustomDataType;
}
export interface VoltageParamsType {
  hv10MinMeanValue?: number;
  hv10MinMeanTripDelay?: number;
  powerDuringCessation?: PowerDuringCessationEnumType;
  customData?: CustomDataType;
}
export interface EnterServiceGetType {
  enterService: EnterServiceType;
  id: string;
  customData?: CustomDataType;
}
export interface EnterServiceType {
  priority: number;
  highVoltage: number;
  lowVoltage: number;
  highFreq: number;
  lowFreq: number;
  delay?: number;
  randomDelay?: number;
  rampRate?: number;
  customData?: CustomDataType;
}
export interface FixedPFGetType {
  fixedPF: FixedPFType;
  id: string;
  isDefault: boolean;
  isSuperseded: boolean;
  customData?: CustomDataType;
}
export interface FixedPFType {
  priority: number;
  displacement: number;
  excitation: boolean;
  startTime?: string;
  duration?: number;
  customData?: CustomDataType;
}
export interface FixedVarGetType {
  fixedVar: FixedVarType;
  id: string;
  isDefault: boolean;
  isSuperseded: boolean;
  customData?: CustomDataType;
}
export interface FixedVarType {
  priority: number;
  setpoint: number;
  unit: DERUnitEnumType;
  startTime?: string;
  duration?: number;
  customData?: CustomDataType;
}
export interface FreqDroopGetType {
  freqDroop: FreqDroopType;
  id: string;
  isDefault: boolean;
  isSuperseded: boolean;
  customData?: CustomDataType;
}
export interface FreqDroopType {
  priority: number;
  overFreq: number;
  underFreq: number;
  overDroop: number;
  underDroop: number;
  responseTime: number;
  startTime?: string;
  duration?: number;
  customData?: CustomDataType;
}
export interface GradientGetType {
  gradient: GradientType;
  id: string;
  customData?: CustomDataType;
}
export interface GradientType {
  priority: number;
  gradient: number;
  softGradient: number;
  customData?: CustomDataType;
}
export interface LimitMaxDischargeGetType {
  id: string;
  isDefault: boolean;
  isSuperseded: boolean;
  limitMaxDischarge: LimitMaxDischargeType;
  customData?: CustomDataType;
}
export interface LimitMaxDischargeType {
  priority: number;
  pctMaxDischargePower?: number;
  powerMonitoringMustTrip?: DERCurveType;
  startTime?: string;
  duration?: number;
  customData?: CustomDataType;
}
