// Generated by scripts/generate-ocpp.ts. Do not edit.

export type RequestStartStopStatusEnumType = "Accepted" | "Rejected";

export interface RequestStopTransactionResponseV21 {
  status: RequestStartStopStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
