// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ReserveNowStatusEnumType =
  "Accepted" | "Faulted" | "Occupied" | "Rejected" | "Unavailable";

export interface ReserveNowResponseV21 {
  status: ReserveNowStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
