// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ResetStatusEnumType = "Accepted" | "Rejected" | "Scheduled";

export interface ResetResponseV21 {
  status: ResetStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
