// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ResetEnumType = "Immediate" | "OnIdle" | "ImmediateAndResume";

export interface ResetRequestV21 {
  type: ResetEnumType;
  evseId?: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
