// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface ReserveNowRequestV21 {
  id: number;
  expiryDateTime: string;
  connectorType?: string;
  idToken: IdTokenType;
  evseId?: number;
  groupIdToken?: IdTokenType;
  customData?: CustomDataType;
}
export interface IdTokenType {
  additionalInfo?: [AdditionalInfoType, ...AdditionalInfoType[]];
  idToken: string;
  type: string;
  customData?: CustomDataType;
}
export interface AdditionalInfoType {
  additionalIdToken: string;
  type: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
