// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ReservationUpdateStatusEnumType =
  | "Expired"
  | "Removed"
  | "NoTransaction";

export interface ReservationStatusUpdateRequestV21 {
  reservationId: number;
  reservationUpdateStatus: ReservationUpdateStatusEnumType;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
