// Generated by scripts/generate-ocpp.ts. Do not edit.

export type AuthorizationStatusEnumType =
  | "Accepted"
  | "Blocked"
  | "ConcurrentTx"
  | "Expired"
  | "Invalid"
  | "NoCredit"
  | "NotAllowedTypeEVSE"
  | "NotAtThisLocation"
  | "NotAtThisTime"
  | "Unknown";
export type MessageFormatEnumType =
  "ASCII" | "HTML" | "URI" | "UTF8" | "QRCODE";
export type UpdateEnumType = "Differential" | "Full";

export interface SendLocalListRequestV21 {
  localAuthorizationList?: [AuthorizationData, ...AuthorizationData[]];
  versionNumber: number;
  updateType: UpdateEnumType;
  customData?: CustomDataType;
}
export interface AuthorizationData {
  idToken: IdTokenType;
  idTokenInfo?: IdTokenInfoType;
  customData?: CustomDataType;
}
export interface IdTokenType {
  additionalInfo?: [AdditionalInfoType, ...AdditionalInfoType[]];
  idToken: string;
  type: string;
  customData?: CustomDataType;
}
export interface AdditionalInfoType {
  additionalIdToken: string;
  type: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface IdTokenInfoType {
  status: AuthorizationStatusEnumType;
  cacheExpiryDateTime?: string;
  chargingPriority?: number;
  groupIdToken?: IdTokenType;
  language1?: string;
  language2?: string;
  evseId?: [number, ...number[]];
  personalMessage?: MessageContentType;
  customData?: CustomDataType;
}
export interface MessageContentType {
  format: MessageFormatEnumType;
  language?: string;
  content: string;
  customData?: CustomDataType;
}
