// Generated by scripts/generate-ocpp.ts. Do not edit.

export type SendLocalListStatusEnumType =
  | "Accepted"
  | "Failed"
  | "VersionMismatch";

export interface SendLocalListResponseV21 {
  status: SendLocalListStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
