// Generated by scripts/generate-ocpp.ts. Do not edit.

export type TariffSetStatusEnumType =
  | "Accepted"
  | "Rejected"
  | "TooManyElements"
  | "ConditionNotSupported"
  | "DuplicateTariffId";

export interface SetDefaultTariffResponseV21 {
  status: TariffSetStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
