// Generated by scripts/generate-ocpp.ts. Do not edit.

export type SetNetworkProfileStatusEnumType =
  "Accepted" | "Rejected" | "Failed";

export interface SetNetworkProfileResponseV21 {
  status: SetNetworkProfileStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
