// Generated by scripts/generate-ocpp.ts. Do not edit.

export type APNAuthenticationEnumType = "PAP" | "CHAP" | "NONE" | "AUTO";
export type OCPPVersionEnumType =
  "OCPP12" | "OCPP15" | "OCPP16" | "OCPP20" | "OCPP201" | "OCPP21";
export type OCPPInterfaceEnumType =
  | "Wired0"
  | "Wired1"
  | "Wired2"
  | "Wired3"
  | "Wireless0"
  | "Wireless1"
  | "Wireless2"
  | "Wireless3"
  | "Any";
export type OCPPTransportEnumType = "SOAP" | "JSON";
export type VPNEnumType = "IKEv2" | "IPSec" | "L2TP" | "PPTP";

export interface SetNetworkProfileRequestV21 {
  configurationSlot: number;
  connectionData: NetworkConnectionProfileType;
  customData?: CustomDataType;
}
export interface NetworkConnectionProfileType {
  apn?: APNType;
  ocppVersion?: OCPPVersionEnumType;
  ocppInterface: OCPPInterfaceEnumType;
  ocppTransport: OCPPTransportEnumType;
  messageTimeout: number;
  ocppCsmsUrl: string;
  securityProfile: number;
  identity?: string;
  basicAuthPassword?: string;
  vpn?: VPNType;
  customData?: CustomDataType;
}
export interface APNType {
  apn: string;
  apnUserName?: string;
  apnPassword?: string;
  simPin?: number;
  preferredNetwork?: string;
  useOnlyPreferredNetwork?: boolean;
  apnAuthentication: APNAuthenticationEnumType;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface VPNType {
  server: string;
  user: string;
  group?: string;
  password: string;
  key: string;
  type: VPNEnumType;
  customData?: CustomDataType;
}
