// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ChargingProfileStatusEnumType = "Accepted" | "Rejected";

export interface SetChargingProfileResponseV21 {
  status: ChargingProfileStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
