// Generated by scripts/generate-ocpp.ts. Do not edit.

export type MonitorEnumType =
  | "UpperThreshold"
  | "LowerThreshold"
  | "Delta"
  | "Periodic"
  | "PeriodicClockAligned"
  | "TargetDelta"
  | "TargetDeltaRelative";

export interface SetVariableMonitoringRequestV21 {
  setMonitoringData: [SetMonitoringDataType, ...SetMonitoringDataType[]];
  customData?: CustomDataType;
}
export interface SetMonitoringDataType {
  id?: number;
  periodicEventStream?: PeriodicEventStreamParamsType;
  transaction?: boolean;
  value: number;
  type: MonitorEnumType;
  severity: number;
  component: ComponentType;
  variable: VariableType;
  customData?: CustomDataType;
}
export interface PeriodicEventStreamParamsType {
  interval?: number;
  values?: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface ComponentType {
  evse?: EVSEType;
  name: string;
  instance?: string;
  customData?: CustomDataType;
}
export interface EVSEType {
  id: number;
  connectorId?: number;
  customData?: CustomDataType;
}
export interface VariableType {
  name: string;
  instance?: string;
  customData?: CustomDataType;
}
