// Generated by scripts/generate-ocpp.ts. Do not edit.

export type MessageFormatEnumType =
  | "ASCII"
  | "HTML"
  | "URI"
  | "UTF8"
  | "QRCODE";
export type DayOfWeekEnumType =
  | "Monday"
  | "Tuesday"
  | "Wednesday"
  | "Thursday"
  | "Friday"
  | "Saturday"
  | "Sunday";
export type EvseKindEnumType = "AC" | "DC";

export interface SetDefaultTariffRequestV21 {
  evseId: number;
  tariff: TariffType;
  customData?: CustomDataType;
}
export interface TariffType {
  tariffId: string;
  description?:
    | [MessageContentType]
    | [MessageContentType, MessageContentType]
    | [MessageContentType, MessageContentType, MessageContentType]
    | [
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
      ]
    | [
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
      ]
    | [
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
      ]
    | [
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
      ]
    | [
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
      ]
    | [
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
      ]
    | [
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
        MessageContentType,
      ];
  currency: string;
  energy?: TariffEnergyType;
  validFrom?: string;
  chargingTime?: TariffTimeType;
  idleTime?: TariffTimeType;
  fixedFee?: TariffFixedType;
  reservationTime?: TariffTimeType;
  reservationFixed?: TariffFixedType;
  minCost?: PriceType;
  maxCost?: PriceType;
  customData?: CustomDataType;
}
export interface MessageContentType {
  format: MessageFormatEnumType;
  language?: string;
  content: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface TariffEnergyType {
  prices: [TariffEnergyPriceType, ...TariffEnergyPriceType[]];
  taxRates?:
    | [TaxRateType]
    | [TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType, TaxRateType];
  customData?: CustomDataType;
}
export interface TariffEnergyPriceType {
  priceKwh: number;
  conditions?: TariffConditionsType;
  customData?: CustomDataType;
}
export interface TariffConditionsType {
  startTimeOfDay?: string;
  endTimeOfDay?: string;
  dayOfWeek?:
    | [DayOfWeekEnumType]
    | [DayOfWeekEnumType, DayOfWeekEnumType]
    | [DayOfWeekEnumType, DayOfWeekEnumType, DayOfWeekEnumType]
    | [
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
      ]
    | [
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
      ]
    | [
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
      ]
    | [
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
      ];
  validFromDate?: string;
  validToDate?: string;
  evseKind?: EvseKindEnumType;
  minEnergy?: number;
  maxEnergy?: number;
  minCurrent?: number;
  maxCurrent?: number;
  minPower?: number;
  maxPower?: number;
  minTime?: number;
  maxTime?: number;
  minChargingTime?: number;
  maxChargingTime?: number;
  minIdleTime?: number;
  maxIdleTime?: number;
  customData?: CustomDataType;
}
export interface TaxRateType {
  type: string;
  tax: number;
  stack?: number;
  customData?: CustomDataType;
}
export interface TariffTimeType {
  prices: [TariffTimePriceType, ...TariffTimePriceType[]];
  taxRates?:
    | [TaxRateType]
    | [TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType, TaxRateType];
  customData?: CustomDataType;
}
export interface TariffTimePriceType {
  priceMinute: number;
  conditions?: TariffConditionsType;
  customData?: CustomDataType;
}
export interface TariffFixedType {
  prices: [TariffFixedPriceType, ...TariffFixedPriceType[]];
  taxRates?:
    | [TaxRateType]
    | [TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType, TaxRateType];
  customData?: CustomDataType;
}
export interface TariffFixedPriceType {
  conditions?: TariffConditionsFixedType;
  priceFixed: number;
  customData?: CustomDataType;
}
export interface TariffConditionsFixedType {
  startTimeOfDay?: string;
  endTimeOfDay?: string;
  dayOfWeek?:
    | [DayOfWeekEnumType]
    | [DayOfWeekEnumType, DayOfWeekEnumType]
    | [DayOfWeekEnumType, DayOfWeekEnumType, DayOfWeekEnumType]
    | [
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
      ]
    | [
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
      ]
    | [
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
      ]
    | [
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
        DayOfWeekEnumType,
      ];
  validFromDate?: string;
  validToDate?: string;
  evseKind?: EvseKindEnumType;
  paymentBrand?: string;
  paymentRecognition?: string;
  customData?: CustomDataType;
}
export interface PriceType {
  exclTax?: number;
  inclTax?: number;
  taxRates?:
    | [TaxRateType]
    | [TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType, TaxRateType];
  customData?: CustomDataType;
}
