// Generated by scripts/generate-ocpp.ts. Do not edit.

export type GenericDeviceModelStatusEnumType =
  "Accepted" | "Rejected" | "NotSupported" | "EmptyResultSet";

export interface SetMonitoringBaseResponseV21 {
  status: GenericDeviceModelStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
