// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface SetMonitoringLevelRequestV21 {
  severity: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
