// Generated by scripts/generate-ocpp.ts. Do not edit.

export type CertificateSigningUseEnumType =
  | "ChargingStationCertificate"
  | "V2GCertificate"
  | "V2G20Certificate";
export type HashAlgorithmEnumType = "SHA256" | "SHA384" | "SHA512";

export interface SignCertificateRequestV21 {
  csr: string;
  certificateType?: CertificateSigningUseEnumType;
  hashRootCertificate?: CertificateHashDataType;
  requestId?: number;
  customData?: CustomDataType;
}
export interface CertificateHashDataType {
  hashAlgorithm: HashAlgorithmEnumType;
  issuerNameHash: string;
  issuerKeyHash: string;
  serialNumber: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
