// Generated by scripts/generate-ocpp.ts. Do not edit.

export type ConnectorStatusEnumType =
  "Available" | "Occupied" | "Reserved" | "Unavailable" | "Faulted";

export interface StatusNotificationRequestV21 {
  timestamp: string;
  connectorStatus: ConnectorStatusEnumType;
  evseId: number;
  connectorId: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
