// Generated by scripts/generate-ocpp.ts. Do not edit.

export type CostDimensionEnumType =
  | "Energy"
  | "MaxCurrent"
  | "MinCurrent"
  | "MaxPower"
  | "MinPower"
  | "IdleTIme"
  | "ChargingTime";
export type TariffCostEnumType = "NormalCost" | "MinCost" | "MaxCost";
export type TransactionEventEnumType = "Ended" | "Started" | "Updated";
export type MeasurandEnumType =
  | "Current.Export"
  | "Current.Export.Offered"
  | "Current.Export.Minimum"
  | "Current.Import"
  | "Current.Import.Offered"
  | "Current.Import.Minimum"
  | "Current.Offered"
  | "Display.PresentSOC"
  | "Display.MinimumSOC"
  | "Display.TargetSOC"
  | "Display.MaximumSOC"
  | "Display.RemainingTimeToMinimumSOC"
  | "Display.RemainingTimeToTargetSOC"
  | "Display.RemainingTimeToMaximumSOC"
  | "Display.ChargingComplete"
  | "Display.BatteryEnergyCapacity"
  | "Display.InletHot"
  | "Energy.Active.Export.Interval"
  | "Energy.Active.Export.Register"
  | "Energy.Active.Import.Interval"
  | "Energy.Active.Import.Register"
  | "Energy.Active.Import.CableLoss"
  | "Energy.Active.Import.LocalGeneration.Register"
  | "Energy.Active.Net"
  | "Energy.Active.Setpoint.Interval"
  | "Energy.Apparent.Export"
  | "Energy.Apparent.Import"
  | "Energy.Apparent.Net"
  | "Energy.Reactive.Export.Interval"
  | "Energy.Reactive.Export.Register"
  | "Energy.Reactive.Import.Interval"
  | "Energy.Reactive.Import.Register"
  | "Energy.Reactive.Net"
  | "EnergyRequest.Target"
  | "EnergyRequest.Minimum"
  | "EnergyRequest.Maximum"
  | "EnergyRequest.Minimum.V2X"
  | "EnergyRequest.Maximum.V2X"
  | "EnergyRequest.Bulk"
  | "Frequency"
  | "Power.Active.Export"
  | "Power.Active.Import"
  | "Power.Active.Setpoint"
  | "Power.Active.Residual"
  | "Power.Export.Minimum"
  | "Power.Export.Offered"
  | "Power.Factor"
  | "Power.Import.Offered"
  | "Power.Import.Minimum"
  | "Power.Offered"
  | "Power.Reactive.Export"
  | "Power.Reactive.Import"
  | "SoC"
  | "Voltage"
  | "Voltage.Minimum"
  | "Voltage.Maximum";
export type ReadingContextEnumType =
  | "Interruption.Begin"
  | "Interruption.End"
  | "Other"
  | "Sample.Clock"
  | "Sample.Periodic"
  | "Transaction.Begin"
  | "Transaction.End"
  | "Trigger";
export type PhaseEnumType =
  | "L1"
  | "L2"
  | "L3"
  | "N"
  | "L1-N"
  | "L2-N"
  | "L3-N"
  | "L1-L2"
  | "L2-L3"
  | "L3-L1";
export type LocationEnumType =
  "Body" | "Cable" | "EV" | "Inlet" | "Outlet" | "Upstream";
export type TriggerReasonEnumType =
  | "AbnormalCondition"
  | "Authorized"
  | "CablePluggedIn"
  | "ChargingRateChanged"
  | "ChargingStateChanged"
  | "CostLimitReached"
  | "Deauthorized"
  | "EnergyLimitReached"
  | "EVCommunicationLost"
  | "EVConnectTimeout"
  | "EVDeparted"
  | "EVDetected"
  | "LimitSet"
  | "MeterValueClock"
  | "MeterValuePeriodic"
  | "OperationModeChanged"
  | "RemoteStart"
  | "RemoteStop"
  | "ResetCommand"
  | "RunningCost"
  | "SignedDataReceived"
  | "SoCLimitReached"
  | "StopAuthorized"
  | "TariffChanged"
  | "TariffNotAccepted"
  | "TimeLimitReached"
  | "Trigger"
  | "TxResumed"
  | "UnlockCommand";
export type PreconditioningStatusEnumType =
  "Unknown" | "Ready" | "NotReady" | "Preconditioning";
export type ChargingStateEnumType =
  "EVConnected" | "Charging" | "SuspendedEV" | "SuspendedEVSE" | "Idle";
export type ReasonEnumType =
  | "DeAuthorized"
  | "EmergencyStop"
  | "EnergyLimitReached"
  | "EVDisconnected"
  | "GroundFault"
  | "ImmediateReset"
  | "MasterPass"
  | "Local"
  | "LocalOutOfCredit"
  | "Other"
  | "OvercurrentFault"
  | "PowerLoss"
  | "PowerQuality"
  | "Reboot"
  | "Remote"
  | "SOCLimitReached"
  | "StoppedByEV"
  | "TimeLimitReached"
  | "Timeout"
  | "ReqEnergyTransferRejected";
export type OperationModeEnumType =
  | "Idle"
  | "ChargingOnly"
  | "CentralSetpoint"
  | "ExternalSetpoint"
  | "ExternalLimits"
  | "CentralFrequency"
  | "LocalFrequency"
  | "LocalLoadBalancing";

export interface TransactionEventRequestV21 {
  costDetails?: CostDetailsType;
  eventType: TransactionEventEnumType;
  meterValue?: [MeterValueType, ...MeterValueType[]];
  timestamp: string;
  triggerReason: TriggerReasonEnumType;
  seqNo: number;
  offline?: boolean;
  numberOfPhasesUsed?: number;
  cableMaxCurrent?: number;
  reservationId?: number;
  preconditioningStatus?: PreconditioningStatusEnumType;
  evseSleep?: boolean;
  transactionInfo: TransactionType;
  evse?: EVSEType;
  idToken?: IdTokenType;
  customData?: CustomDataType;
}
export interface CostDetailsType {
  chargingPeriods?: [ChargingPeriodType, ...ChargingPeriodType[]];
  totalCost: TotalCostType;
  totalUsage: TotalUsageType;
  failureToCalculate?: boolean;
  failureReason?: string;
  customData?: CustomDataType;
}
export interface ChargingPeriodType {
  dimensions?: [CostDimensionType, ...CostDimensionType[]];
  tariffId?: string;
  startPeriod: string;
  customData?: CustomDataType;
}
export interface CostDimensionType {
  type: CostDimensionEnumType;
  volume: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
export interface TotalCostType {
  currency: string;
  typeOfCost: TariffCostEnumType;
  fixed?: PriceType;
  energy?: PriceType;
  chargingTime?: PriceType;
  idleTime?: PriceType;
  reservationTime?: PriceType;
  reservationFixed?: PriceType;
  total: TotalPriceType;
  customData?: CustomDataType;
}
export interface PriceType {
  exclTax?: number;
  inclTax?: number;
  taxRates?:
    | [TaxRateType]
    | [TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType]
    | [TaxRateType, TaxRateType, TaxRateType, TaxRateType, TaxRateType];
  customData?: CustomDataType;
}
export interface TaxRateType {
  type: string;
  tax: number;
  stack?: number;
  customData?: CustomDataType;
}
export interface TotalPriceType {
  exclTax?: number;
  inclTax?: number;
  customData?: CustomDataType;
}
export interface TotalUsageType {
  energy: number;
  chargingTime: number;
  idleTime: number;
  reservationTime?: number;
  customData?: CustomDataType;
}
export interface MeterValueType {
  sampledValue: [SampledValueType, ...SampledValueType[]];
  timestamp: string;
  customData?: CustomDataType;
}
export interface SampledValueType {
  value: number;
  measurand?: MeasurandEnumType;
  context?: ReadingContextEnumType;
  phase?: PhaseEnumType;
  location?: LocationEnumType;
  signedMeterValue?: SignedMeterValueType;
  unitOfMeasure?: UnitOfMeasureType;
  customData?: CustomDataType;
}
export interface SignedMeterValueType {
  signedMeterData: string;
  signingMethod?: string;
  encodingMethod: string;
  publicKey?: string;
  customData?: CustomDataType;
}
export interface UnitOfMeasureType {
  unit?: string;
  multiplier?: number;
  customData?: CustomDataType;
}
export interface TransactionType {
  transactionId: string;
  chargingState?: ChargingStateEnumType;
  timeSpentCharging?: number;
  stoppedReason?: ReasonEnumType;
  remoteStartId?: number;
  operationMode?: OperationModeEnumType;
  tariffId?: string;
  transactionLimit?: TransactionLimitType;
  customData?: CustomDataType;
}
export interface TransactionLimitType {
  maxCost?: number;
  maxEnergy?: number;
  maxTime?: number;
  maxSoC?: number;
  customData?: CustomDataType;
}
export interface EVSEType {
  id: number;
  connectorId?: number;
  customData?: CustomDataType;
}
export interface IdTokenType {
  additionalInfo?: [AdditionalInfoType, ...AdditionalInfoType[]];
  idToken: string;
  type: string;
  customData?: CustomDataType;
}
export interface AdditionalInfoType {
  additionalIdToken: string;
  type: string;
  customData?: CustomDataType;
}
