// Generated by scripts/generate-ocpp.ts. Do not edit.

export type MessageTriggerEnumType =
  | "BootNotification"
  | "LogStatusNotification"
  | "FirmwareStatusNotification"
  | "Heartbeat"
  | "MeterValues"
  | "SignChargingStationCertificate"
  | "SignV2GCertificate"
  | "SignV2G20Certificate"
  | "StatusNotification"
  | "TransactionEvent"
  | "SignCombinedCertificate"
  | "PublishFirmwareStatusNotification"
  | "CustomTrigger";

export interface TriggerMessageRequestV21 {
  evse?: EVSEType;
  requestedMessage: MessageTriggerEnumType;
  customTrigger?: string;
  customData?: CustomDataType;
}
export interface EVSEType {
  id: number;
  connectorId?: number;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
