// Generated by scripts/generate-ocpp.ts. Do not edit.

export type TriggerMessageStatusEnumType =
  "Accepted" | "Rejected" | "NotImplemented";

export interface TriggerMessageResponseV21 {
  status: TriggerMessageStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
