// Generated by scripts/generate-ocpp.ts. Do not edit.

export type UnlockStatusEnumType =
  | "Unlocked"
  | "UnlockFailed"
  | "OngoingAuthorizedTransaction"
  | "UnknownConnector";

export interface UnlockConnectorResponseV21 {
  status: UnlockStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
