// Generated by scripts/generate-ocpp.ts. Do not edit.

export type UnpublishFirmwareStatusEnumType =
  "DownloadOngoing" | "NoFirmware" | "Unpublished";

export interface UnpublishFirmwareResponseV21 {
  status: UnpublishFirmwareStatusEnumType;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
