// Generated by scripts/generate-ocpp.ts. Do not edit.

export type UpdateFirmwareStatusEnumType =
  | "Accepted"
  | "Rejected"
  | "AcceptedCanceled"
  | "InvalidCertificate"
  | "RevokedCertificate";

export interface UpdateFirmwareResponseV21 {
  status: UpdateFirmwareStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
