// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface UpdateFirmwareRequestV21 {
  retries?: number;
  retryInterval?: number;
  requestId: number;
  firmware: FirmwareType;
  customData?: CustomDataType;
}
export interface FirmwareType {
  location: string;
  retrieveDateTime: string;
  installDateTime?: string;
  signingCertificate?: string;
  signature?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
