// Generated by scripts/generate-ocpp.ts. Do not edit.

export type PriorityChargingStatusEnumType =
  | "Accepted"
  | "Rejected"
  | "NoProfile";

export interface UsePriorityChargingResponseV21 {
  status: PriorityChargingStatusEnumType;
  statusInfo?: StatusInfoType;
  customData?: CustomDataType;
}
export interface StatusInfoType {
  reasonCode: string;
  additionalInfo?: string;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
