// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface UsePriorityChargingRequestV21 {
  transactionId: string;
  activate: boolean;
  customData?: CustomDataType;
}
export interface CustomDataType {
  vendorId: string;
  [k: string]: unknown;
}
