// Generated by scripts/generate-ocpp.ts. Do not edit.

export type CertificateSignedStatusEnumType = "Accepted" | "Rejected";

export interface CertificateSignedResponseV16 {
  status: CertificateSignedStatusEnumType;
}
