// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface ClearChargingProfileRequestV16 {
  id?: number;
  connectorId?: number;
  chargingProfilePurpose?:
    "ChargePointMaxProfile" | "TxDefaultProfile" | "TxProfile";
  stackLevel?: number;
}
