// Generated by scripts/generate-ocpp.ts. Do not edit.

export type DeleteCertificateStatusEnumType =
  "Accepted" | "Failed" | "NotFound";

export interface DeleteCertificateResponseV16 {
  status: DeleteCertificateStatusEnumType;
}
