// Generated by scripts/generate-ocpp.ts. Do not edit.

export type TriggerMessageStatusEnumType =
  "Accepted" | "Rejected" | "NotImplemented";

export interface ExtendedTriggerMessageResponseV16 {
  status: TriggerMessageStatusEnumType;
}
