// Generated by scripts/generate-ocpp.ts. Do not edit.

export type MessageTriggerEnumType =
  | "BootNotification"
  | "LogStatusNotification"
  | "FirmwareStatusNotification"
  | "Heartbeat"
  | "MeterValues"
  | "SignChargePointCertificate"
  | "StatusNotification";

export interface ExtendedTriggerMessageRequestV16 {
  requestedMessage: MessageTriggerEnumType;
  connectorId?: number;
}
