// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface FirmwareStatusNotificationRequestV16 {
  status:
    | "Downloaded"
    | "DownloadFailed"
    | "Downloading"
    | "Idle"
    | "InstallationFailed"
    | "Installing"
    | "Installed";
}
