// Generated by scripts/generate-ocpp.ts. Do not edit.

export type LogStatusEnumType = "Accepted" | "Rejected" | "AcceptedCanceled";

export interface GetLogResponseV16 {
  status: LogStatusEnumType;
  filename?: string;
}
