// Generated by scripts/generate-ocpp.ts. Do not edit.

export type HashAlgorithmEnumType = "SHA256" | "SHA384" | "SHA512";
export type GetInstalledCertificateStatusEnumType = "Accepted" | "NotFound";

export interface GetInstalledCertificateIdsResponseV16 {
  certificateHashData?: [CertificateHashDataType, ...CertificateHashDataType[]];
  status: GetInstalledCertificateStatusEnumType;
}
export interface CertificateHashDataType {
  hashAlgorithm: HashAlgorithmEnumType;
  issuerNameHash: string;
  issuerKeyHash: string;
  serialNumber: string;
}
