// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface GetConfigurationResponseV16 {
  configurationKey?: {
    key: string;
    readonly: boolean;
    value?: string;
  }[];
  unknownKey?: string[];
}
