// Generated by scripts/generate-ocpp.ts. Do not edit.

export type CertificateUseEnumType =
  "CentralSystemRootCertificate" | "ManufacturerRootCertificate";

export interface GetInstalledCertificateIdsRequestV16 {
  certificateType: CertificateUseEnumType;
}
