// Generated by scripts/generate-ocpp.ts. Do not edit.

export type LogEnumType = "DiagnosticsLog" | "SecurityLog";

export interface GetLogRequestV16 {
  log: LogParametersType;
  logType: LogEnumType;
  requestId: number;
  retries?: number;
  retryInterval?: number;
}
export interface LogParametersType {
  remoteLocation: string;
  oldestTimestamp?: string;
  latestTimestamp?: string;
}
