// Generated by scripts/generate-ocpp.ts. Do not edit.

export type InstallCertificateStatusEnumType =
  "Accepted" | "Failed" | "Rejected";

export interface InstallCertificateResponseV16 {
  status: InstallCertificateStatusEnumType;
}
