// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface ReserveNowRequestV16 {
  connectorId: number;
  expiryDate: string;
  idTag: string;
  parentIdTag?: string;
  reservationId: number;
}
