// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface SendLocalListRequestV16 {
  listVersion: number;
  localAuthorizationList?: {
    idTag: string;
    idTagInfo?: {
      expiryDate?: string;
      parentIdTag?: string;
      status: "Accepted" | "Blocked" | "Expired" | "Invalid" | "ConcurrentTx";
    };
  }[];
  updateType: "Differential" | "Full";
}
