// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface SignedUpdateFirmwareRequestV16 {
  retries?: number;
  retryInterval?: number;
  requestId: number;
  firmware: FirmwareType;
}
export interface FirmwareType {
  location: string;
  retrieveDateTime: string;
  installDateTime?: string;
  signingCertificate: string;
  signature: string;
}
