// Generated by scripts/generate-ocpp.ts. Do not edit.

export type FirmwareStatusEnumType =
  | "Downloaded"
  | "DownloadFailed"
  | "Downloading"
  | "DownloadScheduled"
  | "DownloadPaused"
  | "Idle"
  | "InstallationFailed"
  | "Installing"
  | "Installed"
  | "InstallRebooting"
  | "InstallScheduled"
  | "InstallVerificationFailed"
  | "InvalidSignature"
  | "SignatureVerified";

export interface SignedFirmwareStatusNotificationRequestV16 {
  status: FirmwareStatusEnumType;
  requestId?: number;
}
