// Generated by scripts/generate-ocpp.ts. Do not edit.

export type UpdateFirmwareStatusEnumType =
  | "Accepted"
  | "Rejected"
  | "AcceptedCanceled"
  | "InvalidCertificate"
  | "RevokedCertificate";

export interface SignedUpdateFirmwareResponseV16 {
  status: UpdateFirmwareStatusEnumType;
}
