// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface StartTransactionRequestV16 {
  connectorId: number;
  idTag: string;
  meterStart: number;
  reservationId?: number;
  timestamp: string;
}
