// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface StartTransactionResponseV16 {
  idTagInfo: {
    expiryDate?: string;
    parentIdTag?: string;
    status: "Accepted" | "Blocked" | "Expired" | "Invalid" | "ConcurrentTx";
  };
  transactionId: number;
}
