// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface StopTransactionResponseV16 {
  idTagInfo?: {
    expiryDate?: string;
    parentIdTag?: string;
    status: "Accepted" | "Blocked" | "Expired" | "Invalid" | "ConcurrentTx";
  };
}
