// Generated by scripts/generate-ocpp.ts. Do not edit.

export interface TriggerMessageRequestV16 {
  requestedMessage:
    | "BootNotification"
    | "DiagnosticsStatusNotification"
    | "FirmwareStatusNotification"
    | "Heartbeat"
    | "MeterValues"
    | "StatusNotification";
  connectorId?: number;
}
