// Generated by scripts/generate-ocpp.ts. Do not edit.

import { v16Schemas } from "./v16/schemas";
import { v201Schemas } from "./v201/schemas";
import { v21Schemas } from "./v21/schemas";

export const schemas: {
  v16: Record<string, object>;
  v201: Record<string, object>;
  v21: Record<string, object>;
} = {
  v16: v16Schemas,
  v201: v201Schemas,
  v21: v21Schemas,
};
