// Generated by scripts/generate-ocpp.ts. Do not edit.

import Ajv from "ajv";
import type { AnySchema, AnySchemaObject, ValidateFunction } from "ajv";
import draft06MetaSchema from "ajv/dist/refs/json-schema-draft-06.json";
import Ajv04 from "ajv-draft-04";

interface SchemaCompiler {
  compile(schema: AnySchema): ValidateFunction;
}

const ajvOptions = {
  allErrors: true,
  strict: false,
  strictSchema: false,
  validateFormats: false,
};

const draft04Ajv = new Ajv04(ajvOptions) as SchemaCompiler;
const draft06AjvInstance = new Ajv(ajvOptions);
draft06AjvInstance.addMetaSchema(draft06MetaSchema as AnySchemaObject);
const draft06Ajv = draft06AjvInstance as SchemaCompiler;
const draft04Cache = new WeakMap<object, ValidateFunction>();
const draft06Cache = new WeakMap<object, ValidateFunction>();

function isDraft04Schema(schema: object): boolean {
  const schemaVersion = (schema as { $schema?: unknown }).$schema;

  return (
    typeof schemaVersion === "string" && schemaVersion.includes("draft-04")
  );
}

function validatorCache(schema: object): WeakMap<object, ValidateFunction> {
  return isDraft04Schema(schema) ? draft04Cache : draft06Cache;
}

function validatorCompiler(schema: object): SchemaCompiler {
  return isDraft04Schema(schema) ? draft04Ajv : draft06Ajv;
}

function validatorFor(schema: object): ValidateFunction {
  const cache = validatorCache(schema);
  const cached = cache.get(schema);

  if (cached) {
    return cached;
  }

  const compiled = validatorCompiler(schema).compile(schema as AnySchema);
  cache.set(schema, compiled);

  return compiled;
}

export function validateOCPPPayload(schema: object, data: unknown): boolean {
  if (data == null) {
    return false;
  }

  return validatorFor(schema)(data) === true;
}

export function validationErrors(schema: object, data: unknown): string[] {
  const validate = validatorFor(schema);

  if (validate(data)) {
    return [];
  }

  return (validate.errors ?? []).map((error) =>
    `${error.instancePath} ${error.message ?? ""}`.trim(),
  );
}
